import { Feather } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import { router } from "expo-router";
import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { colors } from "@/constants/colors";
import { radius, spacing } from "@/constants/spacing";
import { fonts, fontSize } from "@/constants/typography";
import { CombineIcon } from "@/components/ui/CombineIcon";
import { useFarm } from "@/lib/context/FarmContext";
import { useApiModules } from "@/lib/hooks/useApiModules";
import { useApiFetch } from "@/lib/hooks/useApiFetch";
import {
  isBarrelType as _isBarrelType,
  isIdleBarrel as _isIdleBarrel,
  isApproachingNeutral as _isApproachingNeutral,
} from "@/lib/utils/vesselAlerts";

type FarmSector = "arable" | "beef" | "dairy" | "pigs" | "poultry" | "livestock";

// ── Vessel Register alert helpers ─────────────────────────────────────────────

interface WineryVesselSummary {
  vessel_type: string | null;
  status: string | null;
  empty_since: string | null;
  fill_number: number | null;
  fill_count: number | null;
}

// ─────────────────────────────────────────────────────────────────────────────

interface RecordOption {
  id: string;
  title: string;
  description: string;
  icon?: string;
  IconComponent?: React.ComponentType<{ size: number; color: string }>;
  color: string;
  bgColor: string;
  route: string;
  moduleKeys?: string[];
  requiresSectors?: FarmSector[];
}

const recordOptions: RecordOption[] = [
  {
    id: "task-inbox",
    title: "My Task Inbox",
    description: "View tasks assigned to you by the farm manager and mark them as complete",
    icon: "check-square",
    color: "#22c55e",
    bgColor: "#f0fdf4",
    route: "/task-inbox",
  },
  {
    id: "photo",
    title: "Photo Capture",
    description: "Take geotagged photos for evidence and compliance documentation",
    icon: "camera",
    color: colors.textSecondary,
    bgColor: colors.borderLight,
    route: "/photo-capture",
  },
  {
    id: "scan-asset",
    title: "Scan QR Code",
    description: "Scan any BDE Farm Trac QR label — fields, animals, equipment or storage — to pull up the record and log quickly",
    icon: "maximize",
    color: "#0f766e",
    bgColor: "#CCFBF1",
    route: "/scan-asset",
  },
  {
    id: "accident-report",
    title: "Accident / Incident Report",
    description: "Report a workplace accident, near miss, dangerous occurrence or occupational disease — captures GPS, photo evidence and RIDDOR flag",
    icon: "alert-triangle",
    color: colors.error,
    bgColor: colors.errorBg,
    route: "/accident-report",
  },
  {
    id: "right-to-work",
    title: "Right to Work Check",
    description: "Record a pre-employment RTW check — document type, reference, expiry and who carried out the check",
    icon: "user-check",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/right-to-work",
    moduleKeys: ["staff-training"],
  },
  {
    id: "spray",
    title: "Spray Record",
    description: "Log pesticide, herbicide, or fungicide applications with GPS coordinates",
    icon: "droplet",
    color: colors.info,
    bgColor: colors.infoBg,
    route: "/spray-record",
    moduleKeys: ["sprays-inputs"],
  },
  {
    id: "lerap-assessment",
    title: "LERAP Assessment",
    description: "Record a CRD LERAP assessment for Category B products applied near surface water — generates a LERAP document reference",
    icon: "shield",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    route: "/lerap-assessment",
    moduleKeys: ["sprays-inputs"],
  },
  {
    id: "nvz",
    title: "NVZ Fertiliser Application",
    description: "Log organic and synthetic fertiliser applications in Nitrate Vulnerable Zones",
    icon: "zap",
    color: colors.accent,
    bgColor: colors.warningBg,
    route: "/nvz-application",
    moduleKeys: ["sprays-inputs"],
  },
  {
    id: "spray-stocktake",
    title: "Spray Store Stocktake",
    description: "Count physical spray product stock and compare against system records to spot discrepancies",
    icon: "droplet",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    route: "/spray-stocktake",
    moduleKeys: ["sprays-inputs"],
  },
  {
    id: "weather",
    title: "Weather Entry",
    description: "Record daily weather observations for compliance records",
    icon: "cloud",
    color: colors.accent,
    bgColor: colors.warningBg,
    route: "/weather-entry",
    moduleKeys: ["weather-tracking"],
  },
  {
    id: "crop",
    title: "Crop Event",
    description: "Record drilling, harvesting, cultivation, and field inspections",
    icon: "layers",
    color: colors.fieldGreen,
    bgColor: colors.successBg,
    route: "/crop-event",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "soil",
    title: "Soil Sample",
    description: "Log soil sampling data with GPS location and analysis results",
    icon: "thermometer",
    color: colors.fieldBrown,
    bgColor: "#FEF3C7",
    route: "/soil-sample",
    moduleKeys: ["soil-management"],
  },
  {
    id: "soil-sensor",
    title: "Soil Sensor Reading",
    description: "Log a timestamped moisture, temperature, or EC reading from a registered continuous monitoring probe",
    icon: "activity",
    color: "#16a34a",
    bgColor: "#f0fdf4",
    route: "/soil-sensor-reading",
    moduleKeys: ["soil-management"],
  },
  {
    id: "harvest",
    title: "Harvest Record — Combine",
    description: "Combine operator: log the field, crop, yield, moisture and timing for a harvest session",
    IconComponent: CombineIcon,
    color: colors.fieldGold,
    bgColor: "#FEF3C7",
    route: "/harvest-record",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "transport-run",
    title: "Transport Run — Driver",
    description: "Driver: log each trailer load — select today's harvest session, vehicle, storage destination",
    icon: "truck",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    route: "/transport-run",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "dispatch-plans",
    title: "Dispatch Plans",
    description: "View today's and upcoming dispatch plans — start movements, mark complete and log loads against a plan",
    icon: "calendar",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    route: "/dispatch-plans",
    moduleKeys: ["haulage-transport"],
  },
  {
    id: "haulage-confirm",
    title: "Confirm Crop Dispatch",
    description: "Confirm a haulier collecting crop — store/bin, commodity, quantity, buyer, destination, dispatch docket and sign-off",
    icon: "check-circle",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    route: "/haulage-confirm",
    moduleKeys: ["haulage-transport", "field-crop-management"],
  },
  {
    id: "grain-stocktake",
    title: "Grain Store Stocktake",
    description: "Record a physical probe measurement per bin and compare against system stock levels",
    icon: "package",
    color: "#d97706",
    bgColor: "#fffbeb",
    route: "/grain-stocktake",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "service-job",
    title: "Log Service Job",
    description: "Record a contracting or service job completed for another farm — customer, job type, hours, equipment, rate and sign-off",
    icon: "tool",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/service-job",
    moduleKeys: ["haulage-transport"],
  },
  {
    id: "raise-purchase-order",
    title: "Raise Purchase Order",
    description: "Create a purchase order for a supplier — line items, estimated value, expected delivery; held for manager approval if any product requires it",
    icon: "shopping-cart",
    color: "#059669",
    bgColor: "#ecfdf5",
    route: "/raise-purchase-order",
    moduleKeys: ["stock-suppliers"],
  },
  {
    id: "purchase-orders",
    title: "View Purchase Orders",
    description: "Browse your farm's purchase orders by status — Outstanding, Awaiting Approval, Sent, Partially Received, Fully Received",
    icon: "list",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    route: "/purchase-orders",
    moduleKeys: ["stock-suppliers"],
  },
  {
    id: "seed-drilling",
    title: "Seed Drilling Record",
    description: "Record crop drilling — field, crop variety, seed lot, seed rate, treatment and area drilled",
    icon: "wind",
    color: colors.fieldGreen,
    bgColor: colors.successBg,
    route: "/seed-drilling",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "field-operation",
    title: "Field Operation",
    description: "Log cultivation, tillage, lime spreading, rolling, cover crops and drainage — with depth, passes and implement",
    icon: "layers",
    color: colors.fieldBrown,
    bgColor: "#FEF3C7",
    route: "/field-operation",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "field-inspection",
    title: "Field Crop Inspection",
    description: "Crop walking notes — pest and disease observations, growth stage and action flags",
    icon: "search",
    color: colors.primary,
    bgColor: colors.successBg,
    route: "/field-inspection",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "crop-trials-gps",
    title: "Crop Trials GPS Plot",
    description: "Walk to a trial plot and capture your live GPS coordinates — updates the plot location on the dashboard instantly",
    icon: "map-pin",
    color: "#65a30d",
    bgColor: "#f7fee7",
    route: "/crop-trials",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "seed-store",
    title: "Seed Store",
    description: "Log seed batches as they arrive — TGW, bag weight, quantity received and stock remaining by crop",
    icon: "package",
    color: colors.fieldGreen,
    bgColor: colors.successBg,
    route: "/seed-store",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "seed-rate-calculator",
    title: "Seed Rate Calculator",
    description: "Work out a starting seed rate (kg/ha) from target plant population, TGW, soil type and drilling date",
    icon: "percent",
    color: colors.fieldGreen,
    bgColor: colors.successBg,
    route: "/seed-rate-calculator",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "field-crop-assignment",
    title: "Crop Rotation Notes",
    description: "Add rotation reason tags and notes to a field's crop assignment for a given year",
    icon: "repeat",
    color: colors.primary,
    bgColor: colors.successBg,
    route: "/field-crop-assignment",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "medicine",
    title: "Medicine Record",
    description: "Log veterinary medicines, dosage, withdrawal periods and batch numbers",
    icon: "package",
    color: colors.error,
    bgColor: colors.errorBg,
    route: "/medicine-record",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "livestock-check",
    title: "Livestock Health Check",
    description: "Daily welfare inspection — condition score, mortalities, feed and water",
    icon: "heart",
    color: colors.fieldGreen,
    bgColor: colors.successBg,
    route: "/livestock-check",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "isolation-daily-check",
    title: "Isolation Health Check",
    description: "Log a daily health check against an active incoming stock isolation record — status, temperature, and any action taken",
    icon: "shield",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/isolation-daily-check",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "livestock-movement",
    title: "Livestock Movement",
    description: "Record on/off-farm movements with CPH details — syncs to dashboard where cattle go to BCMS and sheep/goats/deer go to LIS with one click",
    icon: "repeat",
    color: colors.info,
    bgColor: colors.infoBg,
    route: "/livestock-movement",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "tb-test",
    title: "TB Test Record",
    description: "Log tuberculin skin test results — vet details, animals tested, reactors and restrictions — syncs to dashboard TB register",
    icon: "activity",
    color: colors.error,
    bgColor: "#fee2e2",
    route: "/tb-test",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "welfare-outcome",
    title: "Welfare Outcome Assessment",
    description: "Red Tractor welfare outcome metrics — BCS, lameness, cleanliness, husbandry checks and corrective actions",
    icon: "heart",
    color: colors.success,
    bgColor: colors.successBg ?? "#dcfce7",
    route: "/welfare-outcome",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sire-register",
    title: "Sire Register",
    description: "View and add bulls and rams — owned, hired in, or loaned — with health and fertility records",
    icon: "target",
    color: colors.primary,
    bgColor: colors.primaryMuted + "33",
    route: "/sire-register",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "straw-inventory",
    title: "Straw Inventory",
    description: "Log AI straw deliveries by batch number — track stock levels and verify donor details at service time",
    icon: "package",
    color: "#0ea5e9",
    bgColor: "#e0f2fe",
    route: "/straw-inventory",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "silage-cut-record",
    title: "Silage / Haylage Cut",
    description: "Record each cut or wrapped-bale batch going into store — quantity, DM%, clamp name and source field for stock balance tracking",
    icon: "wind",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/silage-cut-record",
    moduleKeys: ["field-crop-management", "environmental"],
    requiresSectors: ["arable", "livestock"],
  },
  {
    id: "straw-baling",
    title: "Baling Operation",
    description: "Record the baler's field session — bales produced, machine, operator and weather. First step of the straw workflow.",
    icon: "tool",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/straw-baling",
    moduleKeys: ["field-crop-management"],
    requiresSectors: ["arable"],
  },
  {
    id: "straw-journeys",
    title: "Straw Cartage Journey",
    description: "Log each trailer load moving bales from field to storage — running balance tracks bales remaining in field.",
    icon: "truck",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/straw-journeys",
    moduleKeys: ["field-crop-management"],
    requiresSectors: ["arable"],
  },
  {
    id: "straw-bales",
    title: "Straw Bale Batch",
    description: "Create an inventory batch for bales arriving at a storage location — fire safety monitoring and Red Tractor traceability.",
    icon: "layers",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/straw-bales",
    moduleKeys: ["field-crop-management"],
    requiresSectors: ["arable"],
  },
  {
    id: "straw-sale",
    title: "Straw Sale",
    description: "Log a farm-gate or account bale sale — buyer, straw type, quantity, price per bale and haulier details. Invoice ref auto-generated on sync.",
    icon: "shopping-cart",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/straw-sale",
    moduleKeys: ["field-crop-management"],
    requiresSectors: ["arable"],
  },
  {
    id: "lambing-record",
    title: "Lambing Record",
    description: "Record birth details, lambing ease score, up to 4 lambs, colostrum management, and fostering — Red Tractor Sheep Assurance required",
    icon: "sun",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/lambing-record",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sheep-mating-record",
    title: "Sheep Mating / Tupping Record",
    description: "Record ram details, ewes exposed, tupping dates, expected lambing date, raddle colour changes and mating method",
    icon: "heart",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-mating-record",
    moduleKeys: ["sheep-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sheep-scanning-record",
    title: "Sheep Scanning Record",
    description: "Record pregnancy scan results — barren, singles, doubles and triplets+ with automatic scanning percentage calculation",
    icon: "zap",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-scanning-record",
    moduleKeys: ["sheep-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sheep-weigh-record",
    title: "Sheep Weigh-In Record",
    description: "Record flock weights by age class — average, lowest, highest, target weight, DLWG and body condition score",
    icon: "bar-chart-2",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-weigh-record",
    moduleKeys: ["sheep-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sheep-cull-record",
    title: "Sheep Cull / Market Record",
    description: "Record culls and sales — reason, destination CPH, deadweight, kill-out %, finish grade and price per head",
    icon: "trending-down",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-cull-record",
    moduleKeys: ["sheep-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sheep-vaccination-record",
    title: "Sheep Vaccination Record",
    description: "Log vaccination events — product, batch number, dose, route, withdrawal period and next due date",
    icon: "shield",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-vaccination-record",
    moduleKeys: ["sheep-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "sheep-disease-monitoring",
    title: "Sheep Disease Monitoring",
    description: "Record disease monitoring results — Scrapie NSP, MV, Johne's, foot rot, toxoplasmosis, EAE and faecal egg counts",
    icon: "activity",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-disease-monitoring",
    moduleKeys: ["sheep-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "mortality-record",
    title: "Animal Mortality Record",
    description: "Log individual animal deaths — cause, disposal method, BCMS notification and vet attendance",
    icon: "alert-triangle",
    color: colors.error,
    bgColor: colors.errorBg,
    route: "/mortality-record",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "casualty-slaughter",
    title: "Casualty / Emergency Slaughter",
    description: "Record on-farm emergency killing — method, WASK/WATOK certificate reference, carcase disposal and vet involvement",
    icon: "alert-triangle",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/casualty-slaughter",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "feed-record",
    title: "Feed Record",
    description: "Log feed deliveries with supplier, batch number and quantity for Red Tractor traceability",
    icon: "package",
    color: "#059669",
    bgColor: "#D1FAE5",
    route: "/feed-record",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "water-quality",
    title: "Water Quality Record",
    description: "Log water source and annual test results — required for pigs, poultry and non-mains supplies",
    icon: "droplet",
    color: colors.info,
    bgColor: colors.infoBg,
    route: "/water-quality",
    moduleKeys: ["livestock-management"],
    requiresSectors: ["livestock"],
  },
  {
    id: "calving-record",
    title: "Calving Record",
    description: "Record birth details, calf outcome, calving ease score, and colostrum management",
    icon: "heart",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/calving-record",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "mastitis-record",
    title: "Mastitis Record",
    description: "Log clinical mastitis cases — quarters affected, clinical grade, and treatment",
    icon: "alert-circle",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/mastitis-record",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "mastitis-history",
    title: "Mastitis History",
    description: "View 12-month case trend and browse past mastitis records by month",
    icon: "bar-chart-2",
    color: "#2563eb",
    bgColor: "#dbeafe",
    route: "/mastitis-history",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "dry-cow-therapy",
    title: "Dry Cow Therapy Record",
    description: "Log DCT treatments at dry-off — antibiotic tube, teat sealant, POM-V authorisation, and withdrawal periods",
    icon: "droplet",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/dry-cow-therapy",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "body-condition-score",
    title: "Body Condition Score",
    description: "Record BCS assessments per cow or group on the 1–5 scale with action tracking",
    icon: "bar-chart-2",
    color: "#2563eb",
    bgColor: "#dbeafe",
    route: "/body-condition-score",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "mobility-scoring",
    title: "Mobility Scoring",
    description: "Herd-wide lameness assessment using the AHDB 0–3 scale with automatic prevalence calculation",
    icon: "trending-up",
    color: "#059669",
    bgColor: "#D1FAE5",
    route: "/mobility-scoring",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "nmr-recording-visit",
    title: "NMR Recording Visit",
    description: "Log monthly NMR recorder visit results — herd averages for yield, fat%, protein%, SCC, and F:P ratio",
    icon: "clipboard-list",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/nmr-recording-visit",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "sheep-milk-record",
    title: "Sheep Milk Record",
    description: "Record daily or per-collection sheep milk volumes, fat %, protein %, SCC (1,500k/mL limit) and TBC — syncs to Sheep Dairy module",
    icon: "droplet",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/sheep-milk-record",
    moduleKeys: ["sheep-dairy"],
  },
  {
    id: "mv-monitoring",
    title: "MV Monitoring (Maedi Visna)",
    description: "Record flock MV/MVA test results — animals tested, positives, accreditation scheme status and lab reference",
    icon: "activity",
    color: "#16a34a",
    bgColor: "#d1fae5",
    route: "/mv-monitoring",
    moduleKeys: ["sheep-dairy"],
  },
  {
    id: "goat-milk-record",
    title: "Goat Milk Record",
    description: "Record daily or per-collection goat milk volumes, fat %, protein %, SCC (1,000k/mL limit) and TBC — syncs to Goat Dairy module",
    icon: "droplet",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-milk-record",
    moduleKeys: ["goat-dairy"],
  },
  {
    id: "kidding-record",
    title: "Kidding Record",
    description: "Record goat kidding — doe ID, litter size, kid outcomes, kidding ease score, sire and colostrum management",
    icon: "heart",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/kidding-record",
    moduleKeys: ["goat-dairy"],
  },
  {
    id: "cae-monitoring",
    title: "CAE Monitoring",
    description: "Record Caprine Arthritis Encephalitis test results — ELISA/AGID method, herd status, lab reference and CAEV-free scheme accreditation",
    icon: "activity",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/cae-monitoring",
    moduleKeys: ["goat-dairy"],
  },
  {
    id: "goat-mating-record",
    title: "Goat Mating Record",
    description: "Record buck details, does exposed, mating dates, expected kidding date, progesterone sponge use and mating method",
    icon: "heart",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-mating-record",
    moduleKeys: ["goat-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "goat-scanning-record",
    title: "Goat Scanning Record",
    description: "Record pregnancy scan results — barren, singles, doubles and triples with automatic scanning percentage calculation",
    icon: "zap",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-scanning-record",
    moduleKeys: ["goat-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "goat-weigh-record",
    title: "Goat Weigh-In Record",
    description: "Record herd weights by age class — average, lowest, highest, target weight, DLWG and body condition score",
    icon: "bar-chart-2",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-weigh-record",
    moduleKeys: ["goat-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "goat-cull-record",
    title: "Goat Cull / Market Record",
    description: "Record culls and sales — reason, destination CPH, deadweight, kill-out %, finish grade and price per head",
    icon: "trending-down",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-cull-record",
    moduleKeys: ["goat-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "goat-vaccination-record",
    title: "Goat Vaccination Record",
    description: "Log vaccination events — product, batch number, dose, route, withdrawal period and next due date",
    icon: "shield",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-vaccination-record",
    moduleKeys: ["goat-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "goat-disease-monitoring",
    title: "Goat Disease Monitoring",
    description: "Record monitoring results — CAE/CAEV, CLA, Johne's, foot rot, cryptosporidiosis, toxoplasmosis, mycoplasma and faecal egg counts",
    icon: "activity",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/goat-disease-monitoring",
    moduleKeys: ["goat-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "venison-cull-record",
    title: "Venison Cull Record",
    description: "Log a stalking or culling event — species, sex, age class, beat location, larder/carcass numbers, liveweight, gralloch weight, carcass weight, kill-out %, cull reason, food safety inspection result, and notifiable disease flag with APHA advisory",
    icon: "target",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/venison-cull-record",
    moduleKeys: ["venison-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "venison-carcass-sale",
    title: "Venison Carcass Sale",
    description: "Record a venison carcass processing or sale event — facility type (on-farm larder, AGHE, licensed GHE), species, carcass numbers, grade, destination, buyer, price/kg, total value, invoice reference and Wild Game Declaration number",
    icon: "shopping-cart",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/venison-carcass-sale",
    moduleKeys: ["venison-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "venison-herd-survey",
    title: "Deer Population Survey",
    description: "Log a herd population count — driven count, thermal imaging, fixed point, ADE aerial, thermal drone or camera trap census; male/female/young/total counts, M:F ratio, recruitment rate % and weather conditions",
    icon: "users",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/venison-herd-survey",
    moduleKeys: ["venison-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "venison-health-record",
    title: "Venison Health Record",
    description: "Record vaccination events, bTB SICCT skin tests, bTB gamma-interferon blood tests, post mortems and vet treatments — bTB result, APHA reference, withdrawal period and notifiable disease advisory",
    icon: "activity",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/venison-health-record",
    moduleKeys: ["venison-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "venison-firearms-cert",
    title: "Firearms / Stalking Certificate",
    description: "Add or update a stalker's certificate — Section 1 FC, Section 2 SGC, DSC1, DSC2, Scottish Stalking Certificate, WGMI Hunter Food Hygiene, or Larder Hygiene; expiry date and status for the dashboard expiry alert system",
    icon: "shield",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/venison-firearms-cert",
    moduleKeys: ["venison-production"],
    requiresSectors: ["livestock"],
  },
  {
    id: "organic-venison-feed",
    title: "Organic Venison Feed Record",
    description: "Log supplementary feed or mineral inputs for organic farmed deer — organic approval status (Certified Organic, Approved for Organic Use, Derogation Required, Not Permitted), certifier approval reference, quantity and herd/area",
    icon: "package",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-venison-feed",
    moduleKeys: ["organic-venison"],
  },
  {
    id: "organic-venison-derogation",
    title: "Organic Venison Derogation",
    description: "Record an input derogation case — input name and type, certifier, regulatory basis, justification with OFIS availability evidence, application date, approval status, decision date, expiry and conditions",
    icon: "file-text",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-venison-derogation",
    moduleKeys: ["organic-venison"],
  },
  {
    id: "pig-red-tractor",
    title: "Pig Red Tractor Assessment",
    description: "19-point Red Tractor compliance checklist — welfare plan, medicines, movements, biosecurity, enrichment, welfare and facilities",
    icon: "shield",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-red-tractor",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-welfare-check",
    title: "Pig Welfare Check",
    description: "Red Tractor daily pen inspection — behaviour, bedding, tail biting, feed, water and welfare outcome",
    icon: "shield",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-welfare-check",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-farrowing",
    title: "Pig Farrowing Record",
    description: "Record litter size, born alive, stillborn, mummified, birth weights, farrowing ease and colostrum management",
    icon: "heart",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-farrowing",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-vaccination-record",
    title: "Pig Vaccination Record",
    description: "Record flock vaccinations by disease category — PRRS, PCV2, Enzootic Pneumonia (MH), Erysipelas/PPV, E. coli/Clostridial, APP, Swine Influenza, PED; licensed UK vaccine presets, batch number, withdrawal period, vet-prescribed flag and next due date",
    icon: "shield",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-vaccination-record",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-medicine-treatment",
    title: "Pig Medicine Treatment",
    description: "AMTRA-compliant medicine record — product, batch, route, dose, diagnosis, prescribing vet and withdrawal period with auto-calculated clearance date",
    icon: "package",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-medicine-treatment",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-movement",
    title: "Pig Movement (EAML2)",
    description: "Record pig on/off movements — from/to CPH, EAML2 reference, haulier, vehicle and C&D biosecurity declaration",
    icon: "repeat",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-movement",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-fci",
    title: "Pig Food Chain Information",
    description: "Pre-slaughter FCI document — vet medicine declaration, withdrawal period clearance, lameness/casualty status and feed withdrawal hours",
    icon: "file-text",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-fci",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-feed-consumption",
    title: "Pig Feed Consumption",
    description: "Log daily feed usage by group — feed type, quantity (kg), batch/lot number for traceability and Red Tractor auditing",
    icon: "bar-chart-2",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-feed-consumption",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-vet-assessment",
    title: "Pig Vet Health Assessment",
    description: "Record vet health visits — BCS, lameness, respiratory health, skin condition, tail biting prevalence, clinical findings and recommendations",
    icon: "user-check",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-vet-assessment",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-tail-biting",
    title: "Pig Tail Biting Risk Assessment",
    description: "Mandatory Red Tractor written assessment — risk factors, enrichment provision, mixing frequency, active biting severity and interventions",
    icon: "alert-triangle",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-tail-biting",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-inventory",
    title: "Pig Inventory Count",
    description: "Record herd census by age group — sows, boars, piglets, weaners, growers and finishers — for APHA returns and Red Tractor audit",
    icon: "hash",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-inventory",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "pig-death",
    title: "Pig Death Record",
    description: "Log pig deaths with cause, disposal method, vet attendance and APHA notification — ABP compliance and on-farm mortality records",
    icon: "alert-triangle",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/pig-death",
    moduleKeys: ["pig-production"],
    requiresSectors: ["pigs"],
  },
  {
    id: "poultry-biosecurity-cleanout",
    title: "Poultry Cleanout Biosecurity",
    description: "Step-by-step biosecurity checklist for whole-house cleanout — litter, washing, disinfection, fumigation, vermin, water and footbaths",
    icon: "check-square",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-biosecurity-cleanout",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-welfare-check",
    title: "Poultry Welfare Check",
    description: "Red Tractor daily house inspection — temperature, litter, ammonia, mortalities and bird behaviour",
    icon: "feather",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-welfare-check",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-thinning",
    title: "Poultry Thinning Record",
    description: "Log thinning event — birds removed, live weights, catching times, vehicle reg and DOAs at loading",
    icon: "feather",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-thinning",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-daily-mortality",
    title: "Poultry Daily Mortality",
    description: "Log daily mortality and culled bird counts with cause of death — feeds the running mortality percentage for Red Tractor compliance",
    icon: "alert-triangle",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-daily-mortality",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-vaccination-record",
    title: "Poultry Vaccination Record",
    description: "Record flock vaccinations by disease category — ND, IB, Marek's, Gumboro/IBD, aMPV/TRT, ILT, EDS, Salmonella, MG, Fowl Pox; licensed UK vaccine presets, batch number, withdrawal period, vet-prescribed flag and next due date; syncs to Vaccination Programme tab in dashboard",
    icon: "shield",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-vaccination-record",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-treatment",
    title: "Poultry Treatment Record",
    description: "Record veterinary medicine use — product, dose, route, batch number, prescribing vet and withdrawal period",
    icon: "package",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-treatment",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-env-log",
    title: "Environmental Monitoring Log",
    description: "Record temperature, humidity, ammonia, CO₂, ventilation rate and lighting hours — triggers an alert if ammonia exceeds 20 ppm",
    icon: "thermometer",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-env-log",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-broiler-welfare",
    title: "Broiler Welfare Index (BWI)",
    description: "Score footpad dermatitis, hock burn, gait and plumage — calculates BWI outcome for Red Tractor scheme compliance",
    icon: "shield",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-broiler-welfare",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-fci",
    title: "Food Chain Information (FCI)",
    description: "Complete the legal FCI declaration required before every batch goes to slaughter — covers health, medications and withdrawal periods",
    icon: "file-text",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-fci",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "placement-quality",
    title: "Chick / Poult Placement Quality",
    description: "Record chick quality assessment at placement — overall score, uniformity, culls, arrival temperature, and hatchery notification",
    icon: "check-circle",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/placement-quality",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-transfer",
    title: "Inter-Site Transfer",
    description: "Record movement of birds between holdings you own or manage — destination, quantity, reason, and transport details",
    icon: "arrow-right-left",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-transfer",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "poultry-transport-welfare",
    title: "Transport Welfare Log",
    description: "Log transport welfare conditions for WATD compliance — vehicle, journey details, welfare checks, and overall assessment",
    icon: "shield",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-transport-welfare",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "spray-notification",
    title: "Spray Notification Log",
    description: "Log pre-spray beekeeper or neighbour notification — method, recipient, and confirmation received",
    icon: "bell",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    route: "/spray-notification",
    moduleKeys: ["sprays-inputs"],
  },
  {
    id: "grassland-grazing",
    title: "Grazing Event",
    description: "Log a grazing event — field, entry and exit dates, species, animal count, and pre/post-grazing cover",
    icon: "sun",
    color: colors.fieldGreen,
    bgColor: colors.successBg,
    route: "/grassland-grazing",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "vine-register",
    title: "FSA Vine Register",
    description: "View your FSA Vine Register entries — registered varieties, areas, GI classification and status. Includes an RPA reference warning when SBI number or Viticulture sector is missing.",
    icon: "list",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-register",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-spray-diary",
    title: "Vineyard Spray Diary",
    description: "Log a spray application on a vineyard block — product, MAPP number, rate, area treated, weather conditions and operator details, with photo evidence of application conditions",
    icon: "droplet",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-spray-diary",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-spray-diary-history",
    title: "Spray Diary History",
    description: "View past vineyard spray diary entries, attach or review application photos, and change the block link on any record",
    icon: "clock",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-spray-diary-history",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-scouting",
    title: "Vineyard Disease Scouting",
    description: "Walkabout disease & pest pressure log — downy mildew, powdery mildew, botrytis, phomopsis, leafhopper, vine weevil and notifiable organisms (Xylella, Phytophthora viticola)",
    icon: "eye",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-scouting",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-scouting-history",
    title: "Scouting History",
    description: "View past vineyard disease scouting records and change the block link on any record",
    icon: "clock",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-scouting-history",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-phenology",
    title: "Vine Phenology Observation",
    description: "Record BBCH growth stage observations — from bud burst through to leaf fall — used to time spray applications and canopy operations",
    icon: "sun",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-phenology",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-operation",
    title: "Vineyard Operation",
    description: "Log canopy management activities: pruning (with bud counts), shoot thinning, leaf removal, topping, wire lifting and soil cultivation",
    icon: "scissors",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-operation",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-operation-history",
    title: "Operations History",
    description: "View, edit and delete past vineyard operation records — update block links or remove entries logged in error",
    icon: "clock",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-operations-history",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-harvest",
    title: "Vine Harvest Record",
    description: "Capture per-block vintage data: yield, must chemistry (Brix, pH, TA, potential alcohol), grape condition, botrytis presence and destination winery",
    icon: "shopping-bag",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-harvest",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-harvest-history",
    title: "Harvest History",
    description: "View, edit block links, and delete past harvest records — review yield and must chemistry across all vintages",
    icon: "clock",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-harvest-history",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-block-photos",
    title: "Block Photo Gallery",
    description: "View and add photos for a vineyard block — take a new shot in the field or pick from your camera roll to build a visual record of each block",
    icon: "image",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-block-photos",
    moduleKeys: ["viticulture"],
  },
  {
    id: "vine-age-refusal",
    title: "Age Verification Refusal",
    description: "Log a Challenge 25 refusal — staff member, location, customer's estimated age, ID outcome and supervisor notification. Required by premises licence conditions.",
    icon: "shield",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/vine-age-refusal",
    moduleKeys: ["viticulture"],
  },
  {
    id: "winery-reception",
    title: "Winery Grape Reception",
    description: "Log incoming grape deliveries at the winery gate — gross/tare weights, must analysis (Brix, pH, TA), grape condition and acceptance decision",
    icon: "truck",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/winery-reception",
    moduleKeys: ["viticulture"],
  },
  {
    id: "winery-pressing",
    title: "Pressing Record",
    description: "Log a pressing run — grape weight, press type, free-run vs press juice volumes, Brix readings, settling vessel and any additions made at press",
    icon: "layers",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/winery-pressing",
    moduleKeys: ["viticulture"],
  },
  {
    id: "winery-fermentation",
    title: "Fermentation Monitoring",
    description: "Daily cellar-floor readings — Brix, SG, temperature, pH, TA and volatile acidity per tank, with alerts for stuck fermentation and VA threshold breaches",
    icon: "activity",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/winery-fermentation",
    moduleKeys: ["viticulture"],
  },
  {
    id: "winery-cellar-ops",
    title: "Cellar Operations Log",
    description: "Log any cellar intervention — racking, topping up, sulfiting, fining, filtering, blending, stabilisation and chemistry adjustments",
    icon: "tool",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/winery-cellar-ops",
    moduleKeys: ["viticulture"],
  },
  {
    id: "winery-so2",
    title: "SO₂ Test Entry",
    description: "Record free and total SO₂ results by wine type — organic limits auto-loaded (Red 100, White/Rosé 150, Sparkling 185 mg/L) with instant compliance status and over-limit task alerts",
    icon: "zap",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/winery-so2",
    moduleKeys: ["viticulture"],
  },
  {
    id: "winery-vessel-register",
    title: "Vessel Register",
    description: "View all cellar vessels and barrels — fill tier (New oak / 2nd / 3rd / Neutral), idle alerts for barrels empty over 90 days, and approaching-neutral warnings for fill 4+",
    icon: "database",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/winery-vessel-register",
    moduleKeys: ["viticulture"],
  },
  {
    id: "visitor",
    title: "Visitor Log",
    description: "Quick-log farm visitors with biosecurity compliance checks",
    icon: "users",
    color: "#8B5CF6",
    bgColor: "#EDE9FE",
    route: "/visitor-log",
    moduleKeys: ["biosecurity"],
  },
  {
    id: "pest-control",
    title: "Pest Control Visit",
    description: "Log bait stations, trap checks, pest activity and control actions",
    icon: "alert-circle",
    color: colors.fieldBrown,
    bgColor: "#FEF3C7",
    route: "/pest-control-visit",
    moduleKeys: ["biosecurity"],
  },
  {
    id: "cleaning",
    title: "Cleaning & Disinfection",
    description: "Record cleaning and disinfection of livestock buildings, vehicles and equipment",
    icon: "wind",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    route: "/cleaning-record",
    moduleKeys: ["biosecurity"],
  },
  {
    id: "add-farm-location",
    title: "Add Farm Location",
    description: "Register a new building or storage area on site — GPS coordinates captured automatically for the Farm Map",
    icon: "map-pin",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    route: "/add-farm-location",
    moduleKeys: ["biosecurity"],
  },
  {
    id: "disease-incident",
    title: "Disease & Incident Report",
    description: "Log a disease suspicion, notifiable disease alert, welfare concern or environmental incident — captures GPS, actions taken and APHA reference",
    icon: "alert-triangle",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/disease-incident",
    moduleKeys: ["biosecurity", "livestock-management"],
  },
  {
    id: "fly-tipping",
    title: "Fly-Tipping Incident Report",
    description: "Record illegal waste dumping on your land — location, waste types, hazard assessment and authority reporting",
    icon: "alert-triangle",
    color: "#DC2626",
    bgColor: "#FEE2E2",
    route: "/fly-tipping",
    moduleKeys: ["risk-waste"],
  },
  {
    id: "encampments",
    title: "Unauthorized Encampment",
    description: "Log a trespass encampment — vehicle & person count, police / council notification, legal action and remediation",
    icon: "home",
    color: "#B45309",
    bgColor: "#FEF3C7",
    route: "/encampments",
    moduleKeys: ["risk-waste"],
  },
  {
    id: "waste-disposal",
    title: "Waste Disposal Record",
    description: "Log farm waste collections — waste type, carrier licence, transfer note number and disposal site",
    icon: "trash-2",
    color: "#7C3AED",
    bgColor: "#EDE9FE",
    route: "/waste-disposal",
    moduleKeys: ["risk-waste"],
  },
  {
    id: "organic-inspection",
    title: "Organic Inspection Record",
    description: "Record an organic inspection — certifier, outcome, non-conformances and follow-up actions",
    icon: "clipboard-check",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-inspection",
    moduleKeys: ["organic-compliance"],
  },
  {
    id: "organic-input",
    title: "Organic Input Register",
    description: "Log approved organic inputs — product, supplier, quantity and certification approval reference",
    icon: "package",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-input",
    moduleKeys: ["organic-compliance"],
  },
  {
    id: "organic-milk-collection",
    title: "Organic Milk Collection",
    description: "Record each milk collection — volume, fat %, protein %, SCC, TBC, collection docket ref and organic certification status",
    icon: "droplet",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-milk-collection",
    moduleKeys: ["organic-compliance"],
  },
  {
    id: "organic-sheep-flock-conversion",
    title: "Organic Sheep Flock Conversion",
    description: "Record ewes entering organic conversion — breed, certifier, conversion start date, certification ref and parallel production status",
    icon: "refresh-cw",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-sheep-flock-conversion",
    moduleKeys: ["organic-sheep-dairy"],
  },
  {
    id: "organic-sheep-milk-collection",
    title: "Organic Sheep Milk Collection",
    description: "Record organic sheep milk collections — volume, fat %, protein %, SCC (1,500k limit), organic status, docket ref and premium price",
    icon: "droplet",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-sheep-milk-collection",
    moduleKeys: ["organic-sheep-dairy"],
  },
  {
    id: "organic-sheep-feed",
    title: "Organic Sheep Feed Record",
    description: "Log organic-approved feed inputs for ewes — product, supplier approval number, organic %, certifier ref and derogation reference",
    icon: "package",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-sheep-feed",
    moduleKeys: ["organic-sheep-dairy"],
  },
  {
    id: "organic-sheep-treatment",
    title: "Organic Sheep Treatment",
    description: "Record vet medicines for organic ewes — product, category, dose, standard and doubled withdrawal periods with certifier notification",
    icon: "alert-circle",
    color: "#15803D",
    bgColor: "#DCFCE7",
    route: "/organic-sheep-treatment",
    moduleKeys: ["organic-sheep-dairy"],
  },
  {
    id: "organic-goat-flock-conversion",
    title: "Organic Goat Herd Conversion",
    description: "Record does entering organic conversion — breed, certifier, conversion start date, certification ref and parallel production status",
    icon: "refresh-cw",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-goat-flock-conversion",
    moduleKeys: ["organic-goat-dairy"],
  },
  {
    id: "organic-goat-milk-collection",
    title: "Organic Goat Milk Collection",
    description: "Record organic goat milk collections — volume, fat %, protein %, SCC (1,000k limit), organic status, docket ref and premium price",
    icon: "droplet",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-goat-milk-collection",
    moduleKeys: ["organic-goat-dairy"],
  },
  {
    id: "organic-goat-feed",
    title: "Organic Goat Feed Record",
    description: "Log organic-approved feed inputs for does — product, supplier approval number, organic %, certifier ref and derogation reference",
    icon: "package",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-goat-feed",
    moduleKeys: ["organic-goat-dairy"],
  },
  {
    id: "organic-goat-treatment",
    title: "Organic Goat Treatment",
    description: "Record vet medicines for organic does — product, category, dose, standard and doubled withdrawal periods with certifier notification",
    icon: "alert-circle",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-goat-treatment",
    moduleKeys: ["organic-goat-dairy"],
  },
  {
    id: "equipment-defect",
    title: "Equipment Defect Report",
    description: "Report machinery faults, flag unsafe equipment and record corrective actions",
    icon: "tool",
    color: "#7C3AED",
    bgColor: "#EDE9FE",
    route: "/equipment-defect",
    moduleKeys: ["equipment-management"],
  },
  {
    id: "environmental-feature",
    title: "Register Environmental Feature",
    description: "Register a hedgerow, pond, ditch, woodland, SSSI area or buffer strip — GPS location, dimensions and management practice",
    icon: "map-pin",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/environmental-feature",
    moduleKeys: ["environmental"],
  },
  {
    id: "environmental-event",
    title: "Environmental Management Event",
    description: "Log hedge trimming, pond clearance, mowing, scrub clearance and other habitat management activities",
    icon: "feather",
    color: "#16a34a",
    bgColor: "#dcfce7",
    route: "/environmental-event",
    moduleKeys: ["environmental"],
  },
  {
    id: "land-eligibility",
    title: "Land Eligibility Declaration",
    description: "RTFO/ISCC field land-use declaration — confirm no peatland, wetland or forest conversion after 2008",
    icon: "map",
    color: "#16a34a",
    bgColor: "#dcfce7",
    route: "/land-eligibility",
    moduleKeys: ["biofuel-rtfo"],
  },
  {
    id: "biofuel-delivery",
    title: "Biofuel Crop Delivery",
    description: "Log biofuel crop consignment — buyer, RTFO ref, quantity and sustainability scheme",
    icon: "truck",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/biofuel-delivery",
    moduleKeys: ["biofuel-rtfo"],
  },
  {
    id: "irrigation-meter",
    title: "Irrigation Meter Reading",
    description: "Log abstraction meter readings with usage calculation, pump condition check and GPS location",
    icon: "droplet",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/irrigation-meter",
    moduleKeys: ["water-irrigation"],
  },
  {
    id: "irrigation-advisor",
    title: "Irrigation Advisor",
    description: "SMD water-balance advisor — view soil moisture status and log irrigation applications from each scenario",
    icon: "thermometer",
    color: "#0369a1",
    bgColor: "#e0f2fe",
    route: "/irrigation-advisor",
    moduleKeys: ["water-irrigation"],
  },
  {
    id: "irrigation-history",
    title: "Irrigation History",
    description: "View all logged irrigation applications — date, field, depth and method — including records added via the Advisor",
    icon: "clock",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/irrigation-history",
    moduleKeys: ["water-irrigation"],
  },
  {
    id: "fuel-drawdown",
    title: "Fuel Draw-Down",
    description: "Record fuel drawn from a tank — log the vehicle or machine, quantity and qualifying activity for HMRC red diesel compliance",
    icon: "droplet",
    color: "#b45309",
    bgColor: "#fef3c7",
    route: "/fuel-drawdown",
    moduleKeys: ["fuel-energy"],
  },
  {
    id: "fuel-meter-reading",
    title: "Grid Energy Meter Reading",
    description: "Log electricity, gas or mains LPG meter readings with consumption calculation for Red Tractor and HMRC records",
    icon: "zap",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/fuel-meter-reading",
    moduleKeys: ["fuel-energy"],
  },
  {
    id: "fuel-stock-check",
    title: "Fuel Tank Stock Check",
    description: "Record a physical dip-stick or sight-gauge stock check on any fuel tank — variance alerts flag potential theft or leaks",
    icon: "thermometer",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/fuel-stock-check",
    moduleKeys: ["fuel-energy"],
  },
  {
    id: "fuel-tank-delivery",
    title: "Fuel Tank Delivery",
    description: "Log a tanker delivery — supplier, quantity, unit price, delivery note number and photograph the docket on the spot for HMRC audit trail",
    icon: "truck",
    color: "#0369a1",
    bgColor: "#e0f2fe",
    route: "/fuel-tank-delivery",
    moduleKeys: ["fuel-energy"],
  },
  {
    id: "ai-reproduction",
    title: "AI & Reproduction Record",
    description: "Log artificial insemination, natural service or embryo transfer events and pregnancy check results",
    icon: "activity",
    color: "#16a34a",
    bgColor: "#dcfce7",
    route: "/ai-reproduction",
    moduleKeys: ["livestock-management", "dairy-management"],
  },
  {
    id: "vet-prescription",
    title: "Veterinary Prescription",
    description: "Record a vet-written prescription for the audit trail — drug, dose, withdrawal periods and RCVS details",
    icon: "file-text",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/vet-prescription",
    moduleKeys: ["livestock-management", "dairy-management", "pig-production", "poultry-production"],
  },
  {
    id: "grain-quality-test",
    title: "Grain Quality Test",
    description: "Record moisture, protein, specific weight, Hagberg and mycotoxin results for grain in store",
    icon: "bar-chart-2",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/grain-quality-test",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "grain-temperature",
    title: "Grain Temperature Reading",
    description: "Monitor stored grain temperature at multiple sensor positions and log corrective actions",
    icon: "thermometer",
    color: "#f59e0b",
    bgColor: "#fef9c3",
    route: "/grain-temperature",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "storage-movement",
    title: "Grain Store Movement",
    description: "Log an inter-store transfer, drying loss, or stock adjustment — syncs to the Storage Locations balance on the dashboard",
    icon: "arrow-right-circle",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    route: "/storage-movement",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "grain-lots",
    title: "Grain Lots in Store",
    description: "View all active third-party lots — customer, commodity, balance, bay and movement history at a glance",
    icon: "layers",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/grain-lots",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "third-party-grain-intake",
    title: "Third-Party Grain Intake",
    description: "Book in a customer's grain delivery at the weighbridge — commodity, quality, vehicle reg, lot reference and bay allocation",
    icon: "download",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/third-party-grain-intake",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "third-party-grain-outloading",
    title: "Grain Outloading",
    description: "Record grain leaving a customer's lot — select the active lot, quantity, vehicle, destination and delivery note",
    icon: "upload",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/third-party-grain-outloading",
    moduleKeys: ["field-crop-management"],
  },
  {
    id: "egg-production",
    title: "Egg Production Record",
    description: "Daily egg collection, lay rate calculation, grading totals and packing records",
    icon: "circle",
    color: "#f59e0b",
    bgColor: "#fef3c7",
    route: "/egg-production",
    moduleKeys: ["poultry-production"],
    requiresSectors: ["poultry"],
  },
  {
    id: "slurry-event",
    title: "Slurry / Manure Spreading",
    description: "Record in-field spreading events with source store, application method, NVZ closed-period check and soil condition — species-specific material type enforced",
    icon: "wind",
    color: "#92400e",
    bgColor: "#fef3c7",
    route: "/slurry-event",
    moduleKeys: ["environmental"],
  },
  {
    id: "slurry-fill-event",
    title: "Slurry Store Fill / Intake",
    description: "Log material received into a store — volume, source and material type locked to store configuration for species-specific enforcement",
    icon: "arrow-down",
    color: "#065f46",
    bgColor: "#d1fae5",
    route: "/slurry-fill-event",
    moduleKeys: ["environmental"],
  },
  {
    id: "sfi-action",
    title: "SFI / ELMs Action",
    description: "Log an SFI or ELMs agreement action — scheme, action code, land parcel, eligible area, payment rate and compliance status",
    icon: "sun",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/sfi-action",
    moduleKeys: ["environmental"],
  },
  {
    id: "sprayer-calibration",
    title: "Sprayer Calibration Record",
    description: "Record nozzle checks, output volumes, pressure, speed and NSTS certification details",
    icon: "wind",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/sprayer-calibration",
    moduleKeys: ["equipment-management", "sprays-inputs"],
  },
  {
    id: "maintenance-log",
    title: "Maintenance / Service Log",
    description: "Log repairs, services and inspections for any farm asset — hours, parts, labour and next service",
    icon: "tool",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/maintenance-log",
    moduleKeys: ["equipment-management"],
  },
  {
    id: "horticulture-record",
    title: "Fresh Produce Activity Record",
    description: "Planting, transplanting, harvesting, thinning or soil prep — with seed lot, density and GPS",
    icon: "layers",
    color: "#16a34a",
    bgColor: "#dcfce7",
    route: "/horticulture-record",
    moduleKeys: ["fresh-produce"],
  },
  {
    id: "horticulture-harvest-grade",
    title: "Fresh Produce Harvest Grade & Quality",
    description: "Class 1/2 split, rejection rates, pack-out, lot traceability and cold store allocation",
    icon: "package",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/horticulture-harvest-grade",
    moduleKeys: ["fresh-produce"],
  },
  {
    id: "fresh-produce-intake",
    title: "Fresh Produce Intake QC",
    description: "Log incoming produce condition, temperature, pre-cooling times and lot traceability at the packhouse door",
    icon: "clipboard",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    route: "/fresh-produce-intake",
    moduleKeys: ["fresh-produce"],
  },
  {
    id: "cold-store-temp",
    title: "Cold Store Temperature Log",
    description: "Daily cold store and blast chiller temperature readings with out-of-range alerts and corrective action",
    icon: "thermometer",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/cold-store-temp",
    moduleKeys: ["fresh-produce"],
  },
  {
    id: "organic-arable-input",
    title: "Organic Arable Input Record",
    description: "Log fertiliser, amendment or permitted crop protection applied — Annex II substance picker with Permitted / Restricted / Derogation Required status",
    icon: "package",
    color: "#2563eb",
    bgColor: "#eff6ff",
    route: "/organic-arable-input",
    moduleKeys: ["organic-arable"],
  },
  {
    id: "organic-arable-seed",
    title: "Organic Arable Seed Purchase",
    description: "Record organic certified or derogation seed — lot number, supplier, treatment status and certifier reference",
    icon: "box",
    color: "#7c3aed",
    bgColor: "#f5f3ff",
    route: "/organic-arable-seed",
    moduleKeys: ["organic-arable"],
  },
  {
    id: "organic-arable-stock-movement",
    title: "Organic Arable Seed Stock Movement",
    description: "Log goods-in receipts, seed used in field, stock adjustments or waste disposals — running balance updated automatically",
    icon: "layers",
    color: "#0891b2",
    bgColor: "#ecfeff",
    route: "/organic-arable-stock-movement",
    moduleKeys: ["organic-arable"],
  },
  {
    id: "slurry-inspection",
    title: "Slurry Store Inspection",
    description: "Record a periodic slurry store structural inspection — store condition, capacity check, bund integrity, leakage risk and corrective actions",
    icon: "check-circle",
    color: "#92400e",
    bgColor: "#fef3c7",
    route: "/slurry-inspection",
    moduleKeys: ["environmental"],
  },
  {
    id: "silage-inspection",
    title: "Silage Clamp Inspection",
    description: "Record a silage/haylage clamp structural inspection — effluent containment, cover sheet, wall condition and corrective actions",
    icon: "shield",
    color: "#65a30d",
    bgColor: "#ecfccb",
    route: "/silage-inspection",
    moduleKeys: ["environmental"],
  },
  {
    id: "silage-additive",
    title: "Silage Additive / Inoculant",
    description: "Log an additive or inoculant applied at clamp filling — product, batch number, application rate and operator",
    icon: "droplet",
    color: "#0d9488",
    bgColor: "#ccfbf1",
    route: "/silage-additive",
    moduleKeys: ["environmental"],
  },
  {
    id: "silage-quality-test",
    title: "Silage Quality / DM% Test",
    description: "Record a silage quality analysis — dry matter %, pH, ME, crude protein and lab reference",
    icon: "clipboard",
    color: "#b45309",
    bgColor: "#fef3c7",
    route: "/silage-quality-test",
    moduleKeys: ["environmental"],
  },
  {
    id: "carbon-entry",
    title: "GHG Emission Entry",
    description: "Record emission sources using DEFRA 2024 conversion factors — fuels, livestock, fertilisers, transport and more. tCO₂e auto-calculated.",
    icon: "zap",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/carbon-entry",
    moduleKeys: ["carbon-sustainability", "environmental"],
  },
  {
    id: "carbon-sequestration",
    title: "Carbon Sequestration",
    description: "Record woodland, hedgerow, peatland and other habitats sequestering carbon. Area × Woodland Carbon Code factor gives an instant tCO₂e estimate.",
    icon: "wind",
    color: "#16a34a",
    bgColor: "#dcfce7",
    route: "/carbon-sequestration",
    moduleKeys: ["carbon-sustainability", "environmental"],
  },
  {
    id: "carbon-reduction-action",
    title: "Carbon Reduction Action",
    description: "Log a planned or in-progress action to cut farm emissions — category, funding type, grant reference, responsible person and contractor.",
    icon: "trending-down",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/carbon-reduction-action",
    moduleKeys: ["carbon-sustainability", "environmental"],
  },
  {
    id: "carbon-audit",
    title: "Carbon Audit Record",
    description: "Record a formal farm carbon audit — auditor type, audit tool, verification status, supply chain customer and full scope 1/2/3 tCO₂e figures.",
    icon: "clipboard",
    color: "#0369a1",
    bgColor: "#e0f2fe",
    route: "/carbon-audit",
    moduleKeys: ["carbon-sustainability", "environmental"],
  },
  {
    id: "bng-record",
    title: "Biodiversity Net Gain (BNG)",
    description: "Log a BNG habitat baseline, post-creation or annual monitoring record with Defra Metric 4.0 unit calculations and compliance status.",
    icon: "feather",
    color: "#7c3aed",
    bgColor: "#f3e8ff",
    route: "/bng-record",
    moduleKeys: ["carbon-sustainability", "environmental"],
  },
  {
    id: "diversification-record",
    title: "Farm Diversification Record",
    description: "Bookings, check-ins, income, inspections and visitor records for farm stays, events, shops and other enterprises",
    icon: "home",
    color: "#db2777",
    bgColor: "#fce7f3",
    route: "/diversification-record",
    moduleKeys: ["farm-diversification"],
  },
  {
    id: "equine-health-event",
    title: "Equine Health Event",
    description: "Log vaccinations, worming, farrier visits, dental checks and vet visits for horses and ponies on the yard",
    icon: "heart",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/equine-health-event",
    moduleKeys: ["farm-diversification"],
  },
  {
    id: "shooting-record",
    title: "Shooting & Game Record",
    description: "Log shoot days, bag counts by species, gamekeeper details, game dealer and income for driven and rough shoots",
    icon: "target",
    color: "#78350f",
    bgColor: "#fef3c7",
    route: "/shooting-record",
    moduleKeys: ["farm-diversification"],
  },
  {
    id: "food-hygiene-inspection",
    title: "Food Hygiene Inspection",
    description: "Record EHO visits, HACCP audits and allergen compliance checks — food hygiene rating, findings and corrective actions",
    icon: "shield",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/food-hygiene-inspection",
    moduleKeys: ["farm-diversification"],
  },
  {
    id: "staff-training",
    title: "Staff Training Record",
    description: "Certifications, inductions and competency records — PA1/2/6, first aid, NPTC chainsaw and more",
    icon: "award",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    route: "/staff-training",
    moduleKeys: ["staff-training"],
  },
  {
    id: "ppe-issue",
    title: "PPE Issue Record",
    description: "Issue personal protective equipment to staff — records type, size, manufacturer, serial and return status",
    icon: "shield",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/ppe-issue",
    moduleKeys: ["staff-training"],
  },
  {
    id: "coshh-assessment",
    title: "COSHH Assessment",
    description: "Structured COSHH risk assessment — hazard classification, exposure risk, PPE, storage, disposal and emergency procedures",
    icon: "shield",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/coshh-assessment",
    moduleKeys: ["staff-training"],
  },
  {
    id: "labour-timesheet",
    title: "Labour Timesheet Entry",
    description: "Log staff hours against operations, fields and dates — syncs to dashboard Timesheets tab; working time is checked against the 48-hour WTR rolling average",
    icon: "clock",
    color: "#4f46e5",
    bgColor: "#ede9fe",
    route: "/labour-timesheet",
    moduleKeys: ["staff-training"],
  },
  {
    id: "leave-request",
    title: "Request Annual Leave",
    description: "Submit a leave request (annual leave, compassionate leave, unpaid leave or other) to your manager — they approve or decline from the dashboard and you receive a text message with the outcome",
    icon: "calendar",
    color: "#059669",
    bgColor: "#d1fae5",
    route: "/leave-request",
    moduleKeys: ["staff-training"],
  },
  {
    id: "grain-sale",
    title: "Grain Sale",
    description: "Record a grain sale — commodity, buyer, tonnage, price, moisture and quality results",
    icon: "bar-chart-2",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/grain-sale",
    moduleKeys: ["financial-records"],
  },
  {
    id: "livestock-purchase",
    title: "Livestock Purchase Invoice",
    description: "Record a livestock purchase — supplier, CPH, market, species, head count and invoice amount",
    icon: "shopping-cart",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/livestock-purchase",
    moduleKeys: ["financial-records"],
  },
  {
    id: "livestock-sale",
    title: "Livestock Sale",
    description: "Record a deadweight kill sheet or mart auction sale — species, head count, grade and payment",
    icon: "package",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/livestock-sale",
    moduleKeys: ["financial-records"],
  },
  {
    id: "direct-sale",
    title: "Direct / Farm Gate Sale",
    description: "Log a farm shop, box scheme, farmers market or wholesale sale — product, quantity, price and payment status",
    icon: "shopping-bag",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/direct-sale",
    moduleKeys: ["financial-records"],
  },
  {
    id: "milk-statement",
    title: "Milk Statement",
    description: "Record monthly milk statement — litres supplied, pence per litre, butterfat, protein, SCC and net payment",
    icon: "droplet",
    color: "#1d4ed8",
    bgColor: "#dbeafe",
    route: "/milk-statement",
    moduleKeys: ["financial-records"],
    requiresSectors: ["dairy"],
  },
  {
    id: "johnes-monitoring",
    title: "Johne's Disease Monitoring",
    description: "Record bulk milk ELISA or blood test results, JMM enrolment status, risk level and vet sign-off for Johne's disease monitoring",
    icon: "activity",
    color: "#1d4ed8",
    bgColor: "#dbeafe",
    route: "/johnes-monitoring",
    moduleKeys: ["dairy-management"],
    requiresSectors: ["dairy"],
  },
  {
    id: "campylobacter-monitoring",
    title: "Campylobacter Monitoring",
    description: "Log boot swab, neck skin or caecal samples — record FSA bands, ZAP trigger status and lab results for Red Tractor broiler/turkey compliance",
    icon: "shield",
    color: "#dc2626",
    bgColor: "#fee2e2",
    route: "/campylobacter-monitoring",
    moduleKeys: ["poultry-management"],
  },
  {
    id: "borehole-water-test",
    title: "Borehole Water Test",
    description: "Record borehole or well water test results — bacteriological, chemical and overall pass/fail with static and pumping water levels",
    icon: "droplet",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    route: "/borehole-water-test",
    moduleKeys: ["water-irrigation"],
  },
  {
    id: "fresh-produce-water-test",
    title: "Irrigation Water Quality Test",
    description: "Record irrigation water test results — E.coli, total coliform, salmonella, cryptosporidium, pH and nitrates for Red Tractor / GlobalG.A.P. compliance",
    icon: "droplet",
    color: "#15803d",
    bgColor: "#dcfce7",
    route: "/fresh-produce-water-test",
    moduleKeys: ["fresh-produce"],
  },
  {
    id: "poultry-ncp-test",
    title: "NCP Salmonella Test",
    description: "Record NCP Salmonella flock test — sample type, lab reference, result, serotype isolated and APHA notification status",
    icon: "activity",
    color: "#d97706",
    bgColor: "#fef3c7",
    route: "/poultry-ncp-test",
    moduleKeys: ["poultry-production", "organic-poultry"],
  },
  {
    id: "organic-poultry-access",
    title: "Organic Poultry — Outdoor Access",
    description: "Log outdoor range access compliance for organic poultry — flock ref, birds on range, range area, stocking density and vegetation condition",
    icon: "sun",
    color: "#16a34a",
    bgColor: "#dcfce7",
    route: "/organic-poultry-access",
    moduleKeys: ["organic-poultry"],
  },
  {
    id: "organic-poultry-feed",
    title: "Organic Poultry Feed Record",
    description: "Log organic feed deliveries for poultry flocks — product, organic approval status, certifier reference, batch number, quantity and supplier",
    icon: "package",
    color: "#0f766e",
    bgColor: "#ccfbf1",
    route: "/organic-poultry-feed",
    moduleKeys: ["organic-poultry"],
  },
  {
    id: "ahwr-review",
    title: "Annual Health & Welfare Review",
    description: "Record AHWR with your vet — key findings, health priorities, action points and next review date for all livestock species",
    icon: "clipboard",
    color: "#0891b2",
    bgColor: "#cffafe",
    route: "/ahwr-review",
    moduleKeys: ["livestock-management", "sheep-production", "beef-production", "goat-production", "pig-production", "poultry-production", "organic-livestock", "organic-dairy", "organic-sheep-dairy", "organic-goat-dairy", "organic-venison", "organic-poultry"],
  },
  {
    id: "hive-inspection",
    title: "Hive Inspection",
    description: "Log a beehive inspection — queen status, brood pattern, varroa count, food stores, temperament and colony health assessment",
    icon: "hexagon",
    color: "#f59e0b",
    bgColor: "#fef3c7",
    route: "/hive-inspection",
    moduleKeys: ["beekeeping"],
  },
];

function hasSector(farm: { sectorArable?: boolean; sectorBeef?: boolean; sectorDairy?: boolean; sectorPigs?: boolean; sectorPoultry?: boolean } | null, sectors: FarmSector[]): boolean {
  if (!farm) return true;
  return sectors.some((s) => {
    if (s === "livestock") return !!(farm.sectorBeef || farm.sectorDairy || farm.sectorPigs || farm.sectorPoultry);
    if (s === "arable") return !!farm.sectorArable;
    if (s === "beef") return !!farm.sectorBeef;
    if (s === "dairy") return !!farm.sectorDairy;
    if (s === "pigs") return !!farm.sectorPigs;
    if (s === "poultry") return !!farm.sectorPoultry;
    return true;
  });
}

export default function RecordScreen() {
  const insets = useSafeAreaInsets();
  const { currentFarm } = useFarm();
  const { activeModuleKeys, loading: modulesLoading, resolvedFarmId } = useApiModules(currentFarm?.id);

  const moduleSet = new Set(activeModuleKeys);
  const modulesLoaded = activeModuleKeys.length > 0;

  // Background fetch for Vessel Register alert badge counts — only for viticulture farms.
  // Require resolvedFarmId to match currentFarm.id so we never fire this request during the
  // transition window after a farm switch (when activeModuleKeys still reflect the old farm).
  const shouldFetchVessels =
    !modulesLoading &&
    resolvedFarmId === currentFarm?.id &&
    moduleSet.has("viticulture");
  const { records: vesselRecords } = useApiFetch<WineryVesselSummary>(
    shouldFetchVessels ? currentFarm?.id : undefined,
    "/api/farms/:farmId/winery-vessels"
  );

  const vesselAlertCounts = React.useMemo(() => {
    let idleCount = 0;
    let neutralCount = 0;
    let noFillsCount = 0;
    for (const v of vesselRecords) {
      if (_isBarrelType(v.vessel_type) && String(v.status ?? "active") === "active") {
        if (_isIdleBarrel(v.empty_since, currentFarm?.idleBarrelDays)) idleCount++;
        if (_isApproachingNeutral(v.fill_number, currentFarm?.approachingNeutralFills)) neutralCount++;
        if (Number(v.fill_count ?? 0) === 0) noFillsCount++;
      }
    }
    return { idleCount, neutralCount, noFillsCount };
  }, [vesselRecords, currentFarm?.idleBarrelDays, currentFarm?.approachingNeutralFills]);

  const visibleOptions = recordOptions.filter((option) => {
    if (option.requiresSectors && !hasSector(currentFarm, option.requiresSectors)) {
      return false;
    }
    if (option.moduleKeys && modulesLoaded) {
      return option.moduleKeys.some((k) => moduleSet.has(k));
    }
    return true;
  });

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <Text style={styles.title}>New Record</Text>
        <Text style={styles.subtitle}>Select the type of record to create</Text>
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentInsetAdjustmentBehavior="automatic"
        contentContainerStyle={styles.scrollContent}
      >
        {visibleOptions.map((option) => (
          <RecordOptionCard
            key={option.id}
            option={option}
            vesselAlertCounts={option.id === "winery-vessel-register" ? vesselAlertCounts : undefined}
          />
        ))}
        <View style={{ height: 100 }} />
      </ScrollView>
    </View>
  );
}

function RecordOptionCard({
  option,
  vesselAlertCounts,
}: {
  option: RecordOption;
  vesselAlertCounts?: { idleCount: number; neutralCount: number; noFillsCount: number };
}) {
  const handlePress = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    router.push(option.route as never);
  };

  const showVesselBadge =
    vesselAlertCounts != null &&
    (vesselAlertCounts.idleCount > 0 || vesselAlertCounts.neutralCount > 0 || vesselAlertCounts.noFillsCount > 0);

  // Build badge label, e.g. "2 idle · 1 neutral · 3 no fills"
  const vesselBadgeLabel = showVesselBadge
    ? [
        vesselAlertCounts!.idleCount > 0
          ? `${vesselAlertCounts!.idleCount} idle`
          : null,
        vesselAlertCounts!.neutralCount > 0
          ? `${vesselAlertCounts!.neutralCount} neutral`
          : null,
        vesselAlertCounts!.noFillsCount > 0
          ? `${vesselAlertCounts!.noFillsCount} no fills`
          : null,
      ]
        .filter(Boolean)
        .join(" · ")
    : null;

  // Use red when there are idle barrels, amber when only neutral/no-fills
  const badgeIsRed =
    showVesselBadge && vesselAlertCounts!.idleCount > 0;

  return (
    <Pressable
      onPress={handlePress}
      style={({ pressed }) => [
        styles.card,
        { opacity: pressed ? 0.95 : 1, transform: [{ scale: pressed ? 0.98 : 1 }] },
      ]}
    >
      <View style={[styles.cardIcon, { backgroundColor: option.bgColor }]}>
        {option.IconComponent ? (
          <option.IconComponent size={24} color={option.color} />
        ) : (
          <Feather name={option.icon as keyof typeof Feather.glyphMap} size={24} color={option.color} />
        )}
      </View>
      <View style={styles.cardContent}>
        <Text style={styles.cardTitle}>{option.title}</Text>
        <Text style={styles.cardDescription}>{option.description}</Text>
        {showVesselBadge && (
          <View
            style={[
              styles.vesselAlertBadge,
              { backgroundColor: badgeIsRed ? colors.errorBg : colors.warningBg },
            ]}
          >
            <Feather
              name="alert-triangle"
              size={11}
              color={badgeIsRed ? colors.error : colors.accentDark}
            />
            <Text
              style={[
                styles.vesselAlertBadgeText,
                { color: badgeIsRed ? colors.error : colors.accentDark },
              ]}
            >
              {vesselBadgeLabel}
            </Text>
          </View>
        )}
      </View>
      <Feather name="chevron-right" size={20} color={colors.textTertiary} />
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
  },
  title: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xxl,
    color: colors.text,
  },
  subtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSize.md,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 2,
  },
  cardIcon: {
    width: 48,
    height: 48,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  cardContent: {
    flex: 1,
    marginHorizontal: spacing.md,
  },
  cardTitle: {
    fontFamily: fonts.semiBold,
    fontSize: fontSize.lg,
    color: colors.text,
  },
  cardDescription: {
    fontFamily: fonts.regular,
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    marginTop: spacing.xs,
    lineHeight: 18,
  },
  vesselAlertBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start",
    marginTop: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    borderRadius: radius.full,
  },
  vesselAlertBadgeText: {
    fontSize: fontSize.xs,
    fontFamily: fonts.semiBold,
  },
});
