import PDFDocument from "pdfkit";

// ─── Shared colours & helpers ────────────────────────────────────────────────

const GREEN = "#1a6b3a";
const DARK  = "#111827";
const MID   = "#374151";
const LIGHT = "#6b7280";
const RULE  = "#e5e7eb";
const BLUE  = "#1d4ed8";

function bufferFromDoc(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

function headerBar(doc: InstanceType<typeof PDFDocument>, title: string, subtitle: string) {
  doc.rect(0, 0, doc.page.width, 72).fill(GREEN);
  doc.fillColor("#ffffff")
    .font("Helvetica-Bold").fontSize(16).text("BDE Farm Trac", 48, 18)
    .font("Helvetica").fontSize(9).text("Red Tractor Compliance Platform", 48, 38);
  doc.font("Helvetica-Bold").fontSize(13)
    .text(title, doc.page.width - 300, 18, { width: 252, align: "right" });
  doc.font("Helvetica").fontSize(9)
    .text(subtitle, doc.page.width - 300, 38, { width: 252, align: "right" });
  doc.fillColor(DARK);
  doc.y = 90;
}

function sectionHeading(doc: InstanceType<typeof PDFDocument>, label: string) {
  const y = doc.y + 10;
  doc.rect(48, y, doc.page.width - 96, 20).fill("#f0fdf4");
  doc.fillColor(GREEN).font("Helvetica-Bold").fontSize(8)
    .text(label.toUpperCase(), 54, y + 6, { characterSpacing: 0.8 });
  doc.fillColor(DARK);
  doc.y = y + 26;
}

function twoColRow(doc: InstanceType<typeof PDFDocument>, left: string, right: string, y: number) {
  const half = (doc.page.width - 96) / 2;
  doc.font("Helvetica").fontSize(9).fillColor(LIGHT).text(left, 48, y, { width: half - 8 });
  doc.font("Helvetica").fontSize(9).fillColor(DARK).text(right || "—", 48 + half, y, { width: half });
  return doc.currentLineHeight(true) + 6;
}

function tableHeader(doc: InstanceType<typeof PDFDocument>, cols: { label: string; width: number }[], x: number, y: number) {
  let cx = x;
  doc.rect(x, y, cols.reduce((a, c) => a + c.width, 0), 18).fill("#f0fdf4");
  cols.forEach(col => {
    doc.fillColor(GREEN).font("Helvetica-Bold").fontSize(7.5)
      .text(col.label.toUpperCase(), cx + 4, y + 5, { width: col.width - 8, characterSpacing: 0.5 });
    cx += col.width;
  });
  return y + 18;
}

function tableRow(
  doc: InstanceType<typeof PDFDocument>,
  cols: { width: number }[],
  values: string[],
  x: number,
  y: number,
  shade: boolean
): number {
  const rowH = 16;
  if (shade) doc.rect(x, y, cols.reduce((a, c) => a + c.width, 0), rowH).fill("#f9fafb");
  let cx = x;
  values.forEach((v, i) => {
    doc.fillColor(DARK).font("Helvetica").fontSize(8)
      .text(v || "—", cx + 4, y + 4, { width: cols[i].width - 8, lineBreak: false });
    cx += cols[i].width;
  });
  return y + rowH;
}

function footer(doc: InstanceType<typeof PDFDocument>) {
  const y = doc.page.height - 36;
  doc.rect(0, y - 6, doc.page.width, 42).fill("#f9fafb");
  doc.fillColor(LIGHT).font("Helvetica").fontSize(7.5)
    .text(`Generated by BDE Farm Trac · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })} · Confidential`, 48, y + 2, { align: "center", width: doc.page.width - 96 });
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface FarmInfo {
  name: string;
  address?: string | null;
  postcode?: string | null;
  cphNumber?: string | null;
  sbiNumber?: string | null;
  farmManager?: string | null;
  tenantName: string;
  tenantEmail: string;
}

export interface DeliveryRecord {
  id: number;
  deliveryDate: string;
  buyerName: string;
  buyerRtfoRef?: string | null;
  cropType: string;
  quantityTonnes?: string | null;
  fieldNames?: string[] | null;
  certificationRef?: string | null;
  sustainabilityDeclarationRef?: string | null;
  sustainabilityScheme?: string | null;
  ghgSavingPercent?: string | null;
  notes?: string | null;
}

export interface CertRecord {
  scheme: string;
  certificationNumber?: string | null;
  issuingBody?: string | null;
  issueDate?: string | null;
  expiryDate?: string | null;
  status: string;
  rtfoOperatorNumber?: string | null;
}

export interface FieldDeclarationRecord {
  fieldName: string;
  landUseIn2008: string;
  eligibilityStatus: string;
  convertedAfter2008: boolean;
  highCarbonStockRisk: boolean;
  highBiodiversityRisk: boolean;
  declarationDate?: string | null;
  declaredBy?: string | null;
}

export interface GhgSummaryData {
  nvzApplicationCount: number;
  totalNitrogenKgHa: string;
  sprayApplicationCount: number;
  harvestRecordCount: number;
  totalHarvestTonnes: string;
  biofuelDeliveryCount: number;
  totalBiofuelTonnes: string;
}

// ─── 1. Sustainability Declaration PDF ───────────────────────────────────────

export async function generateSustainabilityDeclaration(
  farm: FarmInfo,
  delivery: DeliveryRecord,
  cert: CertRecord | null,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 48, info: { Title: "Sustainability Declaration" } });

  headerBar(doc, "SUSTAINABILITY DECLARATION", "RTFO / ISCC Scheme");

  // Reference box
  doc.rect(48, doc.y, doc.page.width - 96, 32).stroke(RULE);
  const refY = doc.y + 8;
  doc.font("Helvetica").fontSize(8).fillColor(LIGHT)
    .text("Declaration Reference", 56, refY)
    .text("Delivery Date", 220, refY)
    .text("Generated", 360, refY);
  doc.font("Helvetica-Bold").fontSize(9).fillColor(DARK)
    .text(delivery.sustainabilityDeclarationRef || `SD-${String(delivery.id).padStart(4, "0")}`, 56, refY + 10)
    .text(new Date(delivery.deliveryDate).toLocaleDateString("en-GB"), 220, refY + 10)
    .text(new Date().toLocaleDateString("en-GB"), 360, refY + 10);
  doc.y += 50;

  // ── Section 1: Producer (Farm) Details ──
  sectionHeading(doc, "1. Producer Details");
  const rows1: [string, string][] = [
    ["Business / Farm Name", farm.tenantName],
    ["Farm / Holding Name", farm.name],
    ["Farm Manager", farm.farmManager || ""],
    ["CPH Number", farm.cphNumber || ""],
    ["SBI Number", farm.sbiNumber || ""],
    ["Address", [farm.address, farm.postcode].filter(Boolean).join(", ")],
  ];
  let y = doc.y;
  rows1.forEach(([k, v]) => { y += twoColRow(doc, k, v, y); });
  doc.y = y + 4;

  if (cert) {
    sectionHeading(doc, "1a. Sustainability Certification");
    const rows1a: [string, string][] = [
      ["Certification Scheme", cert.scheme],
      ["Certificate Number", cert.certificationNumber || ""],
      ["Issuing Body", cert.issuingBody || ""],
      ["Certificate Expiry", cert.expiryDate ? new Date(cert.expiryDate).toLocaleDateString("en-GB") : ""],
      ["RTFO Operator Number", cert.rtfoOperatorNumber || ""],
    ];
    y = doc.y;
    rows1a.forEach(([k, v]) => { y += twoColRow(doc, k, v, y); });
    doc.y = y + 4;
  }

  // ── Section 2: Buyer Details ──
  sectionHeading(doc, "2. Buyer (Obligated Supplier) Details");
  const rows2: [string, string][] = [
    ["Buyer / Company Name", delivery.buyerName],
    ["RTF Obligation Number (DfT)", delivery.buyerRtfoRef || ""],
  ];
  y = doc.y;
  rows2.forEach(([k, v]) => { y += twoColRow(doc, k, v, y); });
  doc.y = y + 4;

  // ── Section 3: Feedstock / Consignment Details ──
  sectionHeading(doc, "3. Feedstock & Consignment Details");
  const rows3: [string, string][] = [
    ["Crop / Feedstock Type", delivery.cropType],
    ["Quantity Delivered (tonnes)", delivery.quantityTonnes ? `${Number(delivery.quantityTonnes).toFixed(3)} t` : ""],
    ["Delivery Date", new Date(delivery.deliveryDate).toLocaleDateString("en-GB")],
    ["Source Fields", (delivery.fieldNames || []).join(", ") || "See farm records"],
    ["Certification Reference", delivery.certificationRef || ""],
  ];
  y = doc.y;
  rows3.forEach(([k, v]) => { y += twoColRow(doc, k, v, y); });
  doc.y = y + 4;

  // ── Section 4: Sustainability Criteria ──
  sectionHeading(doc, "4. Sustainability Criteria");
  const rows4: [string, string][] = [
    ["Sustainability Scheme", delivery.sustainabilityScheme || cert?.scheme || ""],
    ["GHG Emission Saving (%)", delivery.ghgSavingPercent ? `${delivery.ghgSavingPercent}%` : ""],
    ["Land Eligibility", "Declared eligible — 2008 land use on file. Not high-carbon-stock or high-biodiversity land."],
    ["Feedstock Origin", "UK-grown crop produced on declared farm holding"],
  ];
  y = doc.y;
  rows4.forEach(([k, v]) => { y += twoColRow(doc, k, v, y); });
  doc.y = y + 4;

  if (delivery.notes) {
    sectionHeading(doc, "Additional Notes");
    doc.font("Helvetica").fontSize(9).fillColor(MID)
      .text(delivery.notes, 48, doc.y, { width: doc.page.width - 96 });
    doc.y += 12;
  }

  // ── Declaration Statement ──
  doc.y += 8;
  const stmtY = doc.y;
  doc.rect(48, stmtY, doc.page.width - 96, 2).fill(GREEN);
  doc.y = stmtY + 10;
  doc.font("Helvetica-Bold").fontSize(9).fillColor(GREEN)
    .text("DECLARATION", 48, doc.y);
  doc.y += 14;
  const scheme = delivery.sustainabilityScheme || cert?.scheme || "an approved sustainability scheme";
  doc.font("Helvetica").fontSize(8.5).fillColor(MID)
    .text(
      `I declare that the feedstock described in this document has been produced in accordance with the sustainability criteria of ${scheme} ` +
      `and meets the requirements of the Renewable Transport Fuel Obligations Order 2007 (as amended). ` +
      `The land on which this crop was grown was not peatland, wetland, continuously forested land, or other high-carbon-stock or ` +
      `high-biodiversity habitat in January 2008. All information in this declaration is accurate and true to the best of my knowledge.`,
      48, doc.y, { width: doc.page.width - 96, lineGap: 2 }
    );
  doc.y += 60;

  // ── Signature Block ──
  const sigY = doc.y;
  const col = (doc.page.width - 96) / 3;
  ["Signed (Producer)", "Print Name", "Date"].forEach((label, i) => {
    const x = 48 + i * col;
    doc.font("Helvetica").fontSize(8).fillColor(LIGHT).text(label, x, sigY);
    doc.rect(x, sigY + 12, col - 12, 24).stroke(RULE);
  });
  doc.y = sigY + 50;

  // For entries that have farm manager filled, pre-print the name
  if (farm.farmManager) {
    doc.font("Helvetica").fontSize(8).fillColor(LIGHT)
      .text(`(${farm.farmManager})`, 48 + col, sigY + 38);
  }

  footer(doc);
  return bufferFromDoc(doc);
}

// ─── 2. RTFO Audit Pack PDF ──────────────────────────────────────────────────

export async function generateAuditPack(
  farm: FarmInfo,
  certs: CertRecord[],
  fields: FieldDeclarationRecord[],
  deliveries: DeliveryRecord[],
  ghg: GhgSummaryData,
  periodLabel: string,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 48, info: { Title: "RTFO Compliance Audit Pack" } });

  // ── Cover Page ──
  doc.rect(0, 0, doc.page.width, doc.page.height).fill("#f0fdf4");
  doc.rect(0, 0, doc.page.width, 8).fill(GREEN);
  doc.rect(0, doc.page.height - 8, doc.page.width, 8).fill(GREEN);

  doc.fillColor(GREEN).font("Helvetica-Bold").fontSize(28)
    .text("RTFO Compliance", 60, 140)
    .text("Audit Pack", 60, 175);
  doc.fillColor(LIGHT).font("Helvetica").fontSize(12)
    .text("Renewable Transport Fuel Obligation", 60, 215);

  doc.rect(60, 260, doc.page.width - 120, 1).fill(GREEN);
  doc.y = 280;

  const coverRows: [string, string][] = [
    ["Farm / Holding", farm.name],
    ["Business", farm.tenantName],
    ["Farm Manager", farm.farmManager || ""],
    ["CPH Number", farm.cphNumber || ""],
    ["SBI Number", farm.sbiNumber || ""],
    ["Address", [farm.address, farm.postcode].filter(Boolean).join(", ")],
    ["Audit Period", periodLabel],
    ["Report Generated", new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })],
  ];
  coverRows.forEach(([k, v]) => {
    doc.fillColor(LIGHT).font("Helvetica").fontSize(10).text(k, 60, doc.y, { width: 200 });
    doc.fillColor(DARK).font("Helvetica-Bold").fontSize(10).text(v || "—", 260, doc.y, { width: 280 });
    doc.y += 22;
  });

  doc.rect(60, doc.page.height - 80, doc.page.width - 120, 1).fill(RULE);
  doc.fillColor(LIGHT).font("Helvetica").fontSize(8)
    .text("Generated by BDE Farm Trac — Red Tractor Compliance Platform", 60, doc.page.height - 68, {
      width: doc.page.width - 120, align: "center"
    });

  // ── Page 2: Compliance Overview ──
  doc.addPage({ size: "A4", margin: 48 });
  headerBar(doc, "SECTION 1 — OVERVIEW", `Audit Pack · ${farm.name}`);

  sectionHeading(doc, "Certification Status");
  if (certs.length === 0) {
    doc.font("Helvetica").fontSize(9).fillColor(LIGHT).text("No certifications on record.", 48, doc.y);
    doc.y += 16;
  } else {
    certs.forEach(cert => {
      const expiry = cert.expiryDate ? new Date(cert.expiryDate).toLocaleDateString("en-GB") : "No expiry set";
      const statusStr = cert.status === "active" ? "ACTIVE" : cert.status.toUpperCase();
      let y = doc.y;
      y += twoColRow(doc, "Scheme", cert.scheme, y);
      y += twoColRow(doc, "Certificate Number", cert.certificationNumber || "", y);
      y += twoColRow(doc, "Issuing Body", cert.issuingBody || "", y);
      y += twoColRow(doc, "Status", statusStr, y);
      y += twoColRow(doc, "Expiry Date", expiry, y);
      if (cert.rtfoOperatorNumber) y += twoColRow(doc, "RTFO Operator Number", cert.rtfoOperatorNumber, y);
      doc.y = y + 8;
    });
  }

  sectionHeading(doc, "Field Eligibility Summary");
  const eligible = fields.filter(f => f.eligibilityStatus === "eligible").length;
  const notEligible = fields.filter(f => f.eligibilityStatus === "not-eligible").length;
  const pending = fields.filter(f => f.eligibilityStatus === "requires-verification").length;
  let y2 = doc.y;
  y2 += twoColRow(doc, "Total Fields Declared", String(fields.length), y2);
  y2 += twoColRow(doc, "Eligible Fields", String(eligible), y2);
  y2 += twoColRow(doc, "Not Eligible Fields", String(notEligible), y2);
  y2 += twoColRow(doc, "Pending Verification", String(pending), y2);
  doc.y = y2 + 8;

  sectionHeading(doc, "Delivery Summary");
  const totalTonnes = deliveries.reduce((s, d) => s + (parseFloat(d.quantityTonnes || "0") || 0), 0);
  let y3 = doc.y;
  y3 += twoColRow(doc, "Total Deliveries", String(deliveries.length), y3);
  y3 += twoColRow(doc, "Total Quantity (tonnes)", totalTonnes.toFixed(3) + " t", y3);
  y3 += twoColRow(doc, "Unique Buyers", String(new Set(deliveries.map(d => d.buyerName)).size), y3);
  doc.y = y3 + 8;

  sectionHeading(doc, "GHG Traceability Data");
  let y4 = doc.y;
  y4 += twoColRow(doc, "NVZ Fertiliser Applications on Record", String(ghg.nvzApplicationCount), y4);
  y4 += twoColRow(doc, "Total Nitrogen Applied (kg)", ghg.totalNitrogenKgHa, y4);
  y4 += twoColRow(doc, "Spray Applications on Record", String(ghg.sprayApplicationCount), y4);
  y4 += twoColRow(doc, "Harvest Records on Record", String(ghg.harvestRecordCount), y4);
  y4 += twoColRow(doc, "Total Harvest Yield (tonnes)", ghg.totalHarvestTonnes + " t", y4);
  doc.y = y4 + 8;
  footer(doc);

  // ── Page 3: Field Eligibility Register ──
  doc.addPage({ size: "A4", margin: 48 });
  headerBar(doc, "SECTION 2 — FIELD REGISTER", "Land Eligibility Declarations");

  doc.font("Helvetica").fontSize(8.5).fillColor(MID)
    .text(
      "The following fields have been declared under the RTFO sustainability criteria. " +
      "All fields must be shown to have been in a non-high-carbon-stock, non-high-biodiversity state in January 2008.",
      48, doc.y, { width: doc.page.width - 96, lineGap: 1.5 }
    );
  doc.y += 16;

  if (fields.length === 0) {
    doc.font("Helvetica").fontSize(9).fillColor(LIGHT).text("No field declarations on record.", 48, doc.y);
  } else {
    const fCols = [
      { label: "Field Name", width: 110 },
      { label: "2008 Land Use", width: 100 },
      { label: "Eligibility", width: 90 },
      { label: "Carbon Risk", width: 70 },
      { label: "Biodiversity Risk", width: 80 },
      { label: "Declared By", width: 92 },
    ];
    const tableW = fCols.reduce((a, c) => a + c.width, 0);
    const startX = (doc.page.width - tableW) / 2;
    let ty = tableHeader(doc, fCols, startX, doc.y);

    fields.forEach((f, i) => {
      if (ty > doc.page.height - 80) {
        footer(doc);
        doc.addPage({ size: "A4", margin: 48 });
        headerBar(doc, "SECTION 2 — FIELD REGISTER (cont.)", "Land Eligibility Declarations");
        ty = tableHeader(doc, fCols, startX, doc.y);
      }
      ty = tableRow(doc, fCols, [
        f.fieldName,
        f.landUseIn2008.replace(/-/g, " "),
        f.eligibilityStatus === "eligible" ? "Eligible" : f.eligibilityStatus === "not-eligible" ? "NOT ELIGIBLE" : "Verify",
        f.highCarbonStockRisk ? "YES" : "No",
        f.highBiodiversityRisk ? "YES" : "No",
        f.declaredBy || "",
      ], startX, ty, i % 2 === 1);
    });
    doc.y = ty + 8;
  }
  footer(doc);

  // ── Page 4: Delivery Record Summary ──
  doc.addPage({ size: "A4", margin: 48 });
  headerBar(doc, "SECTION 3 — DELIVERY RECORDS", "Consignment Summary");

  doc.font("Helvetica").fontSize(8.5).fillColor(MID)
    .text(
      "All biofuel feedstock deliveries recorded for the audit period. Each delivery must be accompanied by a signed Sustainability Declaration.",
      48, doc.y, { width: doc.page.width - 96, lineGap: 1.5 }
    );
  doc.y += 16;

  if (deliveries.length === 0) {
    doc.font("Helvetica").fontSize(9).fillColor(LIGHT).text("No delivery records on record.", 48, doc.y);
  } else {
    const dCols = [
      { label: "Date", width: 64 },
      { label: "Buyer", width: 110 },
      { label: "RTF Ref", width: 80 },
      { label: "Crop", width: 72 },
      { label: "Qty (t)", width: 52 },
      { label: "Scheme", width: 64 },
      { label: "GHG%", width: 40 },
      { label: "SD Ref", width: 78 },
    ];
    const tableW2 = dCols.reduce((a, c) => a + c.width, 0);
    const startX2 = (doc.page.width - tableW2) / 2;
    let ty2 = tableHeader(doc, dCols, startX2, doc.y);

    deliveries.forEach((d, i) => {
      if (ty2 > doc.page.height - 80) {
        footer(doc);
        doc.addPage({ size: "A4", margin: 48 });
        headerBar(doc, "SECTION 3 — DELIVERY RECORDS (cont.)", "Consignment Summary");
        ty2 = tableHeader(doc, dCols, startX2, doc.y);
      }
      ty2 = tableRow(doc, dCols, [
        new Date(d.deliveryDate).toLocaleDateString("en-GB"),
        d.buyerName,
        d.buyerRtfoRef || "",
        d.cropType,
        d.quantityTonnes ? Number(d.quantityTonnes).toFixed(2) : "",
        d.sustainabilityScheme || "",
        d.ghgSavingPercent ? `${d.ghgSavingPercent}%` : "",
        d.sustainabilityDeclarationRef || "",
      ], startX2, ty2, i % 2 === 1);
    });

    // Totals row
    doc.rect(startX2, ty2, tableW2, 18).fill("#e8f5ee");
    doc.fillColor(GREEN).font("Helvetica-Bold").fontSize(8)
      .text(`TOTAL — ${deliveries.length} deliveries · ${totalTonnes.toFixed(3)} t`, startX2 + 4, ty2 + 5, { width: tableW2 - 8 });
    doc.y = ty2 + 26;
  }
  footer(doc);

  return bufferFromDoc(doc);
}
