export interface DefaultArticle {
  title: string;
  slug: string;
  category: string;
  excerpt: string;
  published: boolean;
  sortOrder: number;
  content: string;
}

function toSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

const TITLES: [string, string][] = [
  ["Getting Started with Red Tractor Compliance", "Getting Started"],
  ["Recording Spray Applications", "Sprays & Inputs"],
  ["Managing Your Field Register", "Fields & Crops"],
  ["Equipment Service, MOT & Calibration Records", "Equipment"],
  ["Livestock Movement Records", "Livestock"],
  ["Visitor Logging and Biosecurity Plan", "Biosecurity"],
  ["Staff Training & Certificates", "Staff & Training"],
  ["Inspection Preparation Checklist", "Inspections"],
  ["Understanding COSHH Requirements", "Risk & Waste"],
  ["Financial Record Keeping", "Financial"],
  ["Weather Station Setup", "Weather"],
  ["Document Management Best Practices", "Documents"],
  ["Biofuel / RTFO Compliance Overview", "Biofuel / RTFO"],
  ["ISCC Certification and Land Eligibility", "Biofuel / RTFO"],
  ["Recording Biofuel Deliveries and GHG Savings", "Biofuel / RTFO"],
  ["NVZ Rules, Applications and Risk Assessments", "Nutrient Management"],
  ["Nutrient Management Planning (NMP)", "Nutrient Management"],
  ["Soil Testing and Sampling Records", "Fields & Crops"],
  ["Harvest Records and Yield Tracking", "Fields & Crops"],
  ["Livestock Medicine Records and Withdrawal Periods", "Livestock"],
  ["Pest Control and Cleaning Records", "Biosecurity"],
  ["Using the Mobile App for Field Recording", "Mobile App"],
  ["Livestock Movement Reporting: Scotland, Wales and Northern Ireland", "Livestock"],
  ["Analytical Dashboards and Compliance Snapshots", "Dashboards"],
  ["Sharing Records with Advisors and Inspectors", "Getting Started"],
  ["Logging Field Operations", "Fields & Crops"],
  ["Logging Animal Mortality Records", "Livestock"],
  ["Feed Records and Traceability", "Livestock"],
  ["Water Quality Testing Records", "Livestock"],
  ["Environmental Management — Features, Schemes & Management Events", "Environmental"],
  ["Field Inspections — Logging, Action Flags & Resolution Tracking", "Inspections"],
  ["Farm Buildings & Areas Registry", "Getting Started"],
  ["Understanding Business Reports", "Dashboards"],
  ["SMS Text Alerts — Setup, Who Receives Them & Opting In", "Getting Started"],
  ["Waste Disposal Logging — Records, Carrier Licences & Legal Requirements", "Risk & Waste"],
  ["Week Ahead & Month Ahead — Your Compliance Planner", "Planning"],
  ["Task Board — Managing Staff Task Assignments", "Planning"],
  ["Individual Animal Register and Electronic Identification (EID)", "Livestock"],
  ["Milk Recording and Milk Records", "Livestock"],
  ["Mastitis Records and Treatment Logging", "Livestock"],
  ["Calving Records and Colostrum Management", "Livestock"],
  ["Dry Cow Therapy (DCT) Records", "Livestock"],
  ["Workshop & Asset Management — Overview", "Equipment"],
  ["Scanning QR Codes with the Mobile App", "Mobile App"],
  ["Generating QR Labels for Fields, Animals, and Storage", "Mobile App"],
  ["PAT Testing & Fire Extinguisher Records", "Equipment"],
  ["Workshop Risk Assessments & COSHH", "Risk & Waste"],
  ["Getting Started with Pig Production Records", "Pig Production"],
  ["Pig Movement and Identification", "Pig Production"],
  ["Getting Started with Poultry Production Records", "Poultry Production"],
  ["Salmonella, Biosecurity and Poultry Health Plans", "Poultry Production"],
  ["Getting Started with Horticulture Records", "Horticulture"],
  ["Pre-Harvest Intervals, MRLs and Residue Testing", "Horticulture"],
  ["Carbon & Sustainability Records", "Carbon & Sustainability"],
  ["Farm Diversification Records", "Diversification"],
  ["Water & Irrigation Management", "Water & Irrigation"],
  ["AI & Reproduction Records for Livestock", "Livestock"],
  ["Veterinary Prescriptions & Medicine Book", "Livestock"],
  ["SFI & Agri-Environment Actions", "Environmental"],
  ["Slurry & Manure Management Records", "Environmental"],
  ["Grain Storage Quality Records", "Equipment"],
  ["Fly-Tipping — Recording Incidents, Authority Reporting and Photo Evidence", "Environmental"],
  ["Unauthorized Encampments — Recording, Authority Action and Legal Remedies", "Environmental"],
  ["Crop Trials Register — Setting Up and Managing On-Farm Trials", "Fields & Crops"],
  ["Haulage & Transport — Module Overview", "Haulage"],
  ["Dispatch Plans — Planning and Managing Crop Movements", "Haulage"],
  ["Forward Contracts — Managing Grain Sales & Pricing", "Financial"],
  ["Grain Position — Tracking Your Crop Stock", "Haulage"],
  ["Tail Biting Risk Assessments — Pig Production", "Pig Production"],
  ["Farrowing & Sow Records — Pig Production", "Pig Production"],
  ["Broiler Welfare Indicators (BWI) — Poultry Production", "Poultry Production"],
  ["Right to Work Checks for Farm Employers", "Staff & Training"],
  ["Staff Management & System Access", "Staff & Training"],
  ["Thinning Records — Poultry Production", "Poultry Production"],
  ["Soil Sample Register — Understanding References and Status", "Fields & Crops"],
  ["AI & Reproduction Records — Cattle and Livestock", "Livestock"],
  ["Vet Prescriptions — Storing and Tracking Written Authorisations", "Livestock"],
  ["SFI / ELMS Agreements — Recording and Tracking Agri-Environment Schemes", "Environmental"],
  ["Slurry & Manure Management — Records and Closed Period Compliance", "Environmental"],
  ["Grain Storage Quality — Monitoring and Record Keeping", "Equipment"],
  ["Horticulture Module — Crop Records, Sprays, and Assurance", "Horticulture"],
  ["Carbon & Sustainability — Measuring and Recording Your Farm's Footprint", "Carbon & Sustainability"],
  ["Farm Diversification — Recording Non-Agricultural Activities", "Diversification"],
  ["Water & Irrigation — Abstraction, Usage, and Compliance Records", "Water & Irrigation"],
  ["Equipment Defect Reports — Tracking Faults and Repairs", "Equipment"],
  ["Testing Laboratories — Registering Labs and Linking Test Results", "Getting Started"],
  ["Pig Production Module — Overview", "Pig Production"],
  ["Poultry Production Module — Overview", "Poultry Production"],
  ["Horticulture Module — Overview", "Horticulture"],
  ["Carbon & Sustainability Module — Overview", "Carbon & Sustainability"],
  ["Farm Diversification Module — Overview", "Diversification"],
  ["Water & Irrigation Module — Overview", "Water & Irrigation"],
  ["AI & Reproduction Records — Livestock", "Livestock"],
  ["Sire Register — Recording Donor Bulls, Rams, Boars & Bucks", "Livestock"],
  ["Straw Inventory — Managing AI Semen Deliveries & Stock Levels", "Livestock"],
  ["Lambing Records — Red Tractor Sheep Assurance", "Livestock"],
  ["Vet Prescriptions & Medicines — Red Tractor Requirements", "Livestock"],
  ["SFI / ELMs Actions & Agreements — Environmental Module", "Environmental"],
  ["Slurry & Manure Management — Environmental Module", "Environmental"],
  ["Grain Store Quality Management — Equipment Module", "Equipment"],
  ["Soil Sample Register — Format and Reference Numbers", "Fields & Crops"],
  ["Farm Insurance Register", "Financial"],
  ["Purchase Orders — Raising and Managing POs", "Financial"],
  ["Goods Received Notes (GRN) — Logging Deliveries and Linking to POs", "Financial"],
  ["Batch & Lot Traceability in Spray Application Records", "Sprays & Inputs"],
  ["Farm Planner — Week Ahead & Month Ahead View", "Planning"],
  ["Grants & Funding Register — Tracking FETF and Scheme Applications", "Financial"],
  ["Inspections Module — Tabs, Non-Conformances and Farm Assurance Certificates", "Inspections"],
  ["Risk Assessments — Using Hazard Templates and Recording COSHH Assessments", "Risk & Waste"],
  ["Waste Disposal — EWC Codes and Duty of Care", "Risk & Waste"],
  ["Documents Module — Red Tractor Required Documents Checklist", "Documents"],
  ["Crop Contracts — Recording Grain Marketing Agreements", "Financial"],
  ["Haulage Module — Movement Records, Grain Position and Haulier Directory", "Haulage"],
  ["Mobile App — Offline Data and How Reference Pickers Work", "Mobile App"],
  ["Fuel & Energy Management — HMRC Compliance, Oil Storage, LPG and Grid Energy", "Fuel & Energy"],
  ["Feed Management — UFAS/FEMAS Traceability, Medicated Feed and Stock Levels", "Feed Management"],
  ["Compliance & Plans — Feed Contingency Plan, Disease Log and Feed Recalls", "Feed Management"],
  ["Sales & Trading — Recording Farm Output", "Financial"],
  ["Continuous Soil Monitoring — Sensor Probes and Readings", "Fields & Crops"],
  ["Organic Compliance Overview & Certification Tracking", "Organic"],
  ["Recording Organic Inspections & Attaching Documents", "Organic"],
  ["Organic Input Register & Restricted Inputs", "Organic"],
  ["Field Conversion Tracker & Parallel Production", "Organic"],
  ["Organic Livestock — Herd Register Linkage & Conversion", "Organic"],
  ["Organic Livestock — Treatment Compliance (No Double Entry)", "Organic"],
  ["Organic Dairy — Herd Conversion & Milk Collection Records", "Organic Dairy"],
  ["Organic Dairy — Treatment Compliance & Organic Feed Records", "Organic Dairy"],
  ["TB Testing — Enhanced Data Capture & History", "Livestock"],
  ["Welfare Outcome Assessments — Scoring, Reporting & Mobile Recording", "Livestock"],
  ["Fallen Stock Records — Contractor, Veterinary Details & Invoice Tracking", "Livestock"],
  ["Sheep Dipping Records — Pesticide Certificates & Stock Usage", "Livestock"],
  ["Vet Prescriptions — Linking Treatments to Written Authorisations", "Livestock"],
  ["Department Management — Creating Departments & Assigning Staff", "Staff & Training"],
  ["Task Assignment — Filtering by Department & Viewing Department Tasks", "Staff & Training"],
  ["Contractor H&S File — Reviews, Compliance Tasks & Supplier Badges", "Risk & Waste"],
  ["Task Board — New Task Types & Filtering Completed Tasks by Date", "Planning"],
  ["PPE Register — Where to Find It & How the Three Sub-Registers Work", "Staff & Training"],
  ["PPE Stock Register — Supplier Traceability, Invoice Refs & Stock Levels", "Staff & Training"],
  ["PPE Issue Register — Issuing PPE to Staff & Recording Condition Checks", "Staff & Training"],
  ["PPE Risk Assessments — Recording Assessments Under PPE at Work Regulations 2022", "Staff & Training"],
  ["PPE Compliance Pack — Printing the Full PPE Register for Inspection", "Staff & Training"],
  ["PPE Staff Record — Printing an Individual Staff Member's PPE History", "Staff & Training"],
];

export const DEFAULT_HELP_ARTICLES: DefaultArticle[] = TITLES.map(([title, category], idx) => ({
  title,
  slug: toSlug(title),
  category,
  excerpt: `Help article: ${title}`,
  published: false,
  sortOrder: idx + 1,
  content: `<h2>${title}</h2>\n<p>This article has been imported as a draft. Edit the content in the Admin Portal before publishing.</p>`,
}));
