import { db, lookupItemsTable } from "@workspace/db";
import { eq, and, isNull } from "drizzle-orm";

export interface LookupDefinition {
  label: string;
  description: string;
  authority: string;
  authorityUrl: string | null;
  reviewFrequency: string;
  items: string[] | { label: string; group?: string }[];
}

export const LOOKUP_DEFINITIONS: Record<string, LookupDefinition> = {
  inspection_types: {
    label: "Inspection Types",
    description: "Types of farm inspection and audit",
    authority: "Red Tractor / Local Authority / Organic certifiers",
    authorityUrl: "https://www.redtractor.org.uk",
    reviewFrequency: "Annual",
    items: [
      "Red Tractor",
      "Internal Audit",
      "EHO",
      "Trading Standards",
      "Organic",
      "LEAF Marque",
      "Soil Association",
      "RSPCA Assured",
      "BRC Global Standards",
      "QMS",
      "Countryside Stewardship Walk-Over",
      "Environment Agency",
      "Other",
    ],
  },
  grant_schemes: {
    label: "Grant & Subsidy Schemes",
    description: "UK agricultural grant and subsidy schemes",
    authority: "DEFRA / Rural Payments Agency",
    authorityUrl: "https://www.gov.uk/guidance/farming-grants-and-payments",
    reviewFrequency: "Quarterly",
    items: [
      "Sustainable Farming Incentive (SFI)",
      "Countryside Stewardship (CS)",
      "Basic Payment Scheme (BPS)",
      "Higher Tier Countryside Stewardship",
      "Farming in Protected Landscapes (FiPL)",
      "Environmental Land Management (ELM)",
      "Slurry Infrastructure Grant",
      "Farming Equipment & Technology Fund (FETF)",
      "Productivity & Slurry Grant",
      "Water Management Grant",
      "Livestock Health & Welfare Pathway",
      "AHDB Levy",
      "Other Government Grant",
      "Other",
    ],
  },
  transaction_categories: {
    label: "Transaction Categories",
    description: "Income and expense categories for financial records",
    authority: "Internal BDE / HMRC",
    authorityUrl: "https://www.gov.uk/government/publications/rates-and-allowances-for-agriculture",
    reviewFrequency: "Annual",
    items: [
      "Seeds & Seed Treatments",
      "Fertiliser",
      "Pesticides & Herbicides",
      "Fungicides",
      "Insecticides",
      "Veterinary & Medicine",
      "Feed & Bedding",
      "Fuel",
      "Machinery & Equipment",
      "Labour",
      "Agri-Environment Scheme",
      "Grant / Subsidy",
      "Crop Sales",
      "Livestock Sales",
      "Haulage",
      "Other Income",
      "Other Expense",
    ],
  },
  payment_methods: {
    label: "Payment Methods",
    description: "Financial transaction payment methods",
    authority: "Internal BDE",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: ["Bank Transfer", "Direct Debit", "Cheque", "Cash", "Card", "BACS", "Other"],
  },
  commodity_types: {
    label: "Commodity Types",
    description: "Manage crop and commodity types. Expand to view and add named varieties for each crop type.",
    authority: "AHDB",
    authorityUrl: "https://ahdb.org.uk/cereals-oilseeds",
    reviewFrequency: "Annual",
    items: [
      "Winter Wheat",
      "Spring Wheat",
      "Winter Barley",
      "Spring Barley",
      "Malting Barley",
      "Winter Oats",
      "Spring Oats",
      "Oilseed Rape",
      "Winter Beans",
      "Spring Beans",
      "Peas",
      "Maize",
      "Rye",
      "Triticale",
      "Linseed",
      "Sugar Beet",
      "Other",
    ],
  },
  crop_varieties: {
    label: "Crop Varieties",
    description: "Named varieties for each commodity type — used in crop records, drilling logs, grain sales and stock",
    authority: "AHDB Recommended Lists / NIAB",
    authorityUrl: "https://ahdb.org.uk/cereals-oilseeds/recommended-lists",
    reviewFrequency: "Annual",
    items: [
      { label: "KWS Zyatt", group: "Winter Wheat" },
      { label: "Skyfall", group: "Winter Wheat" },
      { label: "Crusoe", group: "Winter Wheat" },
      { label: "Graham", group: "Winter Wheat" },
      { label: "Extase", group: "Winter Wheat" },
      { label: "Kerrin", group: "Winter Wheat" },
      { label: "Champion", group: "Winter Wheat" },
      { label: "Gleam", group: "Winter Wheat" },
      { label: "KWS Kinetic", group: "Winter Wheat" },
      { label: "Siskin", group: "Winter Wheat" },
      { label: "Mulika", group: "Spring Wheat" },
      { label: "Tybalt", group: "Spring Wheat" },
      { label: "Paragon", group: "Spring Wheat" },
      { label: "KWS Cochise", group: "Spring Wheat" },
      { label: "KWS Orwell", group: "Winter Barley" },
      { label: "Craft", group: "Winter Barley" },
      { label: "SY Venture", group: "Winter Barley" },
      { label: "Bazooka", group: "Winter Barley" },
      { label: "Volume", group: "Winter Barley" },
      { label: "Glacier", group: "Winter Barley" },
      { label: "Laureate", group: "Spring Barley" },
      { label: "Planet", group: "Spring Barley" },
      { label: "Propino", group: "Spring Barley" },
      { label: "Concerto", group: "Spring Barley" },
      { label: "Moonshine", group: "Spring Barley" },
      { label: "KWS Irina", group: "Spring Barley" },
      { label: "Sassy", group: "Spring Barley" },
      { label: "Mascani", group: "Winter Oats" },
      { label: "Bison", group: "Winter Oats" },
      { label: "Gerald", group: "Winter Oats" },
      { label: "Elyann", group: "Spring Oats" },
      { label: "Husky", group: "Spring Oats" },
      { label: "Firth", group: "Spring Oats" },
      { label: "Aileen", group: "Spring Oats" },
      { label: "Architect", group: "Oilseed Rape" },
      { label: "Aspire", group: "Oilseed Rape" },
      { label: "Darling", group: "Oilseed Rape" },
      { label: "Elgar", group: "Oilseed Rape" },
      { label: "Festivity", group: "Oilseed Rape" },
      { label: "Nikita", group: "Oilseed Rape" },
      { label: "Campus", group: "Oilseed Rape" },
      { label: "Tundra", group: "Winter Beans" },
      { label: "Wizard", group: "Winter Beans" },
      { label: "Fuego", group: "Winter Beans" },
      { label: "Lynx", group: "Winter Beans" },
      { label: "Fanfare", group: "Spring Beans" },
      { label: "Vertigo", group: "Spring Beans" },
      { label: "Fuego", group: "Spring Beans" },
      { label: "Gregor", group: "Peas" },
      { label: "Maverick", group: "Peas" },
      { label: "Cassius", group: "Peas" },
      { label: "Bohatyr", group: "Peas" },
      { label: "Ambition", group: "Maize" },
      { label: "Farmflex", group: "Maize" },
      { label: "KWS Frederico", group: "Maize" },
      { label: "LG Aapollo", group: "Maize" },
      { label: "Ronaldinio", group: "Maize" },
      { label: "Alize KWS", group: "Sugar Beet" },
      { label: "Beata KWS", group: "Sugar Beet" },
      { label: "Barsita", group: "Sugar Beet" },
      { label: "Modus", group: "Sugar Beet" },
      { label: "Antares", group: "Linseed" },
      { label: "Cygnus", group: "Linseed" },
      { label: "Palazzo", group: "Rye" },
      { label: "Helltop", group: "Rye" },
      { label: "Dublet", group: "Triticale" },
      { label: "Amarillo", group: "Triticale" },
      { label: "Other / Unknown", group: "Other" },
    ],
  },
  load_types: {
    label: "Load / Haulage Types",
    description: "Types of load for haulage and movement records",
    authority: "Internal BDE",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: ["Grain", "Straw", "Silage", "Livestock", "Fertiliser", "Machinery", "Waste", "Other"],
  },
  spray_product_categories: {
    label: "Spray Product Categories",
    description: "Categories of crop protection products (pesticides)",
    authority: "HSE / MAPP Register / BCPC",
    authorityUrl: "https://www.hse.gov.uk/pesticides/",
    reviewFrequency: "Annual",
    items: [
      "Herbicide",
      "Fungicide",
      "Insecticide",
      "Molluscicide",
      "Growth Regulator",
      "Foliar Feed",
      "Adjuvant",
      "Desiccant",
      "Biostimulant",
      "Other",
    ],
  },
  biofuel_cert_schemes: {
    label: "Biofuel Certification Schemes",
    description: "Sustainability certification schemes for biofuel feedstocks (RTFO compliance)",
    authority: "DfT / ISCC / Bonsucro",
    authorityUrl: "https://www.gov.uk/guidance/renewable-transport-fuel-obligation",
    reviewFrequency: "Annual",
    items: ["ISCC EU", "ISCC UK", "Bonsucro", "RTRS", "REDcert", "RSB", "Other"],
  },
  inspector_organisations: {
    label: "Inspector Organisations",
    description: "Organisations that carry out slurry store and environmental inspections",
    authority: "Internal",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: [
      "Internal",
      "Environment Agency",
      "AHDB",
      "ADAS",
      "Natural England",
      "SEPA",
      "Natural Resources Wales",
      "DAERA",
      "SAC Consulting",
      "Agri-EPI Centre",
      "Farm consultant / agronomist",
      "Insurance surveyor",
      "Other",
    ],
  },
  nvz_application_methods: {
    label: "NVZ Application Methods",
    description: "Methods for applying organic manures and slurry in Nitrate Vulnerable Zones",
    authority: "Environment Agency",
    authorityUrl: "https://www.gov.uk/guidance/nitrate-vulnerable-zones",
    reviewFrequency: "Annual",
    items: [
      "Trailing shoe",
      "Dribble bar",
      "Injected",
      "Band spread",
      "Broadcast (surface)",
      "Umbilical",
      "Tanker spread",
      "Spinner / broadcast",
      "Foliar",
      "Irrigation",
    ],
  },
  nvz_soil_types: {
    label: "NVZ Soil Types",
    description: "MAFF/AHDB standard soil texture classification for NVZ risk assessments",
    authority: "MAFF / AHDB",
    authorityUrl: "https://ahdb.org.uk/knowledge-library/soil-texture",
    reviewFrequency: "As needed",
    items: [
      "Sand",
      "Loamy Sand",
      "Sandy Loam",
      "Sandy Silt Loam",
      "Silt Loam",
      "Silt",
      "Loam",
      "Clay Loam",
      "Sandy Clay Loam",
      "Silty Clay Loam",
      "Sandy Clay",
      "Silty Clay",
      "Clay",
    ],
  },
  livestock_species: {
    label: "Livestock Species",
    description: "Manage species for herd/flock register. Expand to view and add named breeds for each species.",
    authority: "APHA / BCU",
    authorityUrl: "https://www.gov.uk/government/organisations/animal-and-plant-health-agency",
    reviewFrequency: "As needed",
    items: ["Cattle", "Sheep", "Pigs", "Poultry", "Goats", "Deer", "Horses", "Other"],
  },
  livestock_breeds: {
    label: "Livestock Breeds",
    description: "Named breeds for each livestock species — used in herd/flock records and movement documents",
    authority: "RBST / APHA",
    authorityUrl: "https://www.rbst.org.uk",
    reviewFrequency: "As needed",
    items: [
      // Cattle
      { label: "Aberdeen Angus", group: "Cattle" },
      { label: "Hereford", group: "Cattle" },
      { label: "Limousin", group: "Cattle" },
      { label: "Charolais", group: "Cattle" },
      { label: "Simmental", group: "Cattle" },
      { label: "Holstein-Friesian", group: "Cattle" },
      { label: "British Friesian", group: "Cattle" },
      { label: "Beef Shorthorn", group: "Cattle" },
      { label: "Longhorn", group: "Cattle" },
      { label: "Belted Galloway", group: "Cattle" },
      { label: "Galloway", group: "Cattle" },
      { label: "Highland", group: "Cattle" },
      { label: "Devon", group: "Cattle" },
      { label: "South Devon", group: "Cattle" },
      { label: "Red Poll", group: "Cattle" },
      { label: "Dexter", group: "Cattle" },
      { label: "Welsh Black", group: "Cattle" },
      { label: "British Blue", group: "Cattle" },
      { label: "Blonde d'Aquitaine", group: "Cattle" },
      { label: "Stabiliser", group: "Cattle" },
      // Sheep
      { label: "Suffolk", group: "Sheep" },
      { label: "Texel", group: "Sheep" },
      { label: "Mule", group: "Sheep" },
      { label: "Greyface Mule", group: "Sheep" },
      { label: "Swaledale", group: "Sheep" },
      { label: "Herdwick", group: "Sheep" },
      { label: "Cheviot", group: "Sheep" },
      { label: "North Country Cheviot", group: "Sheep" },
      { label: "Border Leicester", group: "Sheep" },
      { label: "Bluefaced Leicester", group: "Sheep" },
      { label: "Lleyn", group: "Sheep" },
      { label: "Beltex", group: "Sheep" },
      { label: "Hampshire Down", group: "Sheep" },
      { label: "Dorset Horn", group: "Sheep" },
      { label: "Poll Dorset", group: "Sheep" },
      { label: "Romney", group: "Sheep" },
      { label: "Jacob", group: "Sheep" },
      { label: "Soay", group: "Sheep" },
      { label: "Charollais", group: "Sheep" },
      { label: "Vendeen", group: "Sheep" },
      // Pigs
      { label: "Large White", group: "Pigs" },
      { label: "Landrace", group: "Pigs" },
      { label: "Duroc", group: "Pigs" },
      { label: "British Saddleback", group: "Pigs" },
      { label: "Berkshire", group: "Pigs" },
      { label: "Tamworth", group: "Pigs" },
      { label: "Oxford Sandy and Black", group: "Pigs" },
      { label: "Hampshire", group: "Pigs" },
      { label: "Pietrain", group: "Pigs" },
      { label: "Welsh", group: "Pigs" },
      // Poultry
      { label: "Ross 308", group: "Poultry" },
      { label: "Cobb 500", group: "Poultry" },
      { label: "Hubbard", group: "Poultry" },
      { label: "Lohmann Brown", group: "Poultry" },
      { label: "ISA Brown", group: "Poultry" },
      { label: "Hy-Line Brown", group: "Poultry" },
      { label: "Light Sussex", group: "Poultry" },
      { label: "Rhode Island Red", group: "Poultry" },
      { label: "Maran", group: "Poultry" },
      { label: "Norfolk Black", group: "Poultry" },
      { label: "Kelly Bronze", group: "Poultry" },
      { label: "Stag Bronze", group: "Poultry" },
      // Goats
      { label: "Saanen", group: "Goats" },
      { label: "Toggenburg", group: "Goats" },
      { label: "British Alpine", group: "Goats" },
      { label: "Anglo-Nubian", group: "Goats" },
      { label: "Boer", group: "Goats" },
      { label: "Golden Guernsey", group: "Goats" },
      { label: "Pygmy", group: "Goats" },
      // Deer
      { label: "Red Deer", group: "Deer" },
      { label: "Fallow Deer", group: "Deer" },
      { label: "Sika Deer", group: "Deer" },
      { label: "Roe Deer", group: "Deer" },
      // Horses
      { label: "Thoroughbred", group: "Horses" },
      { label: "Warmblood", group: "Horses" },
      { label: "Cob", group: "Horses" },
      { label: "Shire", group: "Horses" },
      { label: "Irish Draught", group: "Horses" },
      { label: "Cleveland Bay", group: "Horses" },
      { label: "Welsh Cob", group: "Horses" },
      { label: "Heavy Horse", group: "Horses" },
      // Other
      { label: "Other / Unknown", group: "Other" },
    ],
  },
  vineyard_grape_varieties: {
    label: "Vineyard Grape Varieties (UK)",
    description: "Wine grape varieties grown in UK vineyards",
    authority: "HMRC Vine Register / WineGB",
    authorityUrl: "https://www.winegb.co.uk",
    reviewFrequency: "Annual",
    items: [
      "Bacchus", "Chardonnay", "Dornfelder", "Huxelrebe",
      "Madeleine Angevine", "Müller-Thurgau", "Ortega", "Phoenix",
      "Pinot Blanc", "Pinot Gris", "Pinot Meunier", "Pinot Noir",
      "Regent", "Reichensteiner", "Rondo", "Seyval Blanc",
      "Siegerrebe", "Solaris", "Auxerrois", "Cabernet Cortis",
      "Cabernet Blanc", "Johanniter", "Lakhta", "Sauvignon Blanc", "Other",
    ],
  },
  vineyard_rootstocks: {
    label: "Vineyard Rootstocks",
    description: "Grapevine rootstock varieties in use in UK vineyards",
    authority: "WineGB / ENTAV-INRAE",
    authorityUrl: "https://www.winegb.co.uk",
    reviewFrequency: "Annual",
    items: [
      "5C Teleki", "SO4", "3309 Couderc", "101-14 Millardet",
      "5BB Kober", "125AA", "41B", "420A", "Gravesac",
      "Riparia Gloire de Montpellier", "161-49 Couderc",
      "Fercal", "Schwarzmann", "Own Rooted", "Other",
    ],
  },
  vineyard_training_systems: {
    label: "Vineyard Training Systems",
    description: "Vine training and trellis systems",
    authority: "WineGB",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: ["Double Guyot", "Single Guyot", "Cordon", "Scott Henry", "Lenz Moser", "VSP", "Other"],
  },
  vineyard_operation_types: {
    label: "Vineyard Operation Types",
    description: "Types of canopy management and cultural operations",
    authority: "WineGB Good Viticulture Practice",
    authorityUrl: null,
    reviewFrequency: "Annual",
    items: [
      "Winter Pruning", "Spur Thinning", "Bud Rubbing", "Shoot Thinning",
      "Tie Down / Cane Laying", "Wire Lifting", "Leaf Removal", "Topping / Hedging",
      "Green Harvest (Crop Thinning)", "Soil Cultivation", "Mulching", "Other",
    ],
  },
  vineyard_spray_application_methods: {
    label: "Vineyard Spray Application Methods",
    description: "Application equipment methods for vineyard PPP and plant protection",
    authority: "HSE / NPTC",
    authorityUrl: "https://www.hse.gov.uk/pesticides/",
    reviewFrequency: "Annual",
    items: [
      "Knapsack Sprayer", "Tractor-mounted Boom Sprayer",
      "Air-blast / Vineyard Sprayer", "Lean-to / Facing Sprayer",
      "Drone Application", "Hand-held Lance", "Other",
    ],
  },
  vineyard_spray_rate_units: {
    label: "Spray Rate Units",
    description: "Units for expressing spray product application rates",
    authority: "HSE / BCPC",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: ["L/ha", "mL/ha", "kg/ha", "g/ha", "fl oz/acre", "oz/acre", "Other"],
  },
  vineyard_spray_quantity_units: {
    label: "Spray Quantity Units",
    description: "Units for expressing total quantities of spray product used",
    authority: "Internal BDE",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: ["L", "mL", "kg", "g", "fl oz", "Other"],
  },
  vineyard_weather_conditions: {
    label: "Weather Conditions (Spray Diary)",
    description: "Descriptive weather conditions at time of spray application — required for spray records",
    authority: "HSE / NPTC",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: [
      "Clear and calm", "Overcast, dry, calm", "Light breeze (< 3 mph)",
      "Moderate breeze (3–5 mph)", "Overcast, light rain",
      "Hot and sunny (> 25°C)", "Cold (< 5°C)", "Frost risk",
      "High humidity (> 80%)", "Other",
    ],
  },
  vineyard_soil_analysis_types: {
    label: "Soil & Leaf Analysis Types",
    description: "Types of analytical testing for vineyard soils and plant tissue",
    authority: "WineGB / Organic certifiers",
    authorityUrl: null,
    reviewFrequency: "Annual",
    items: ["Soil Analysis", "Petiole (Leaf) Analysis", "Must Analysis", "Tissue Analysis"],
  },
  vineyard_laboratories: {
    label: "Analytical Laboratories (Viticulture)",
    description: "Laboratories used for soil, leaf, and must analysis",
    authority: "UKAS / Internal BDE",
    authorityUrl: "https://www.ukas.com",
    reviewFrequency: "Annual",
    items: [
      "NRM Group", "Lancrop Laboratories", "ADAS Analytical Services",
      "Eurofins Agro UK", "Agri-Food & Biosciences Institute (AFBI)",
      "RB209 Soil Analysis", "CIEL", "University of East Anglia Analytical",
      "Other",
    ],
  },
  organic_certifying_bodies: {
    label: "Organic Certifying Bodies (UK)",
    description: "UK-approved certifying bodies for organic production",
    authority: "DEFRA / UK Organic Regulation 2020",
    authorityUrl: "https://www.gov.uk/guidance/organic-farming",
    reviewFrequency: "Annual",
    items: [
      "Soil Association", "Organic Farmers & Growers (OF&G)",
      "Biodynamic Association (BDAA)", "Quality Welsh Food Certification (QWFC)",
      "Organic Trust (ROI)", "Other",
    ],
  },
  organic_land_use_types: {
    label: "Pre-conversion Land Use Types",
    description: "Previous land use history relevant to organic conversion records",
    authority: "UK Organic Regs 2020",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: [
      "Conventional arable", "Conventional grassland", "Conventional horticulture",
      "Set-aside / fallow", "Woodland / forestry", "Previously certified organic",
      "In-conversion", "Amenity / parkland", "Other",
    ],
  },
  organic_input_units: {
    label: "Organic Input Application Units",
    description: "Units for expressing quantities of organic inputs applied",
    authority: "Internal BDE",
    authorityUrl: null,
    reviewFrequency: "As needed",
    items: ["kg/ha", "g/ha", "L/ha", "mL/ha", "kg", "g", "L", "mL", "t/ha", "Other"],
  },
  organic_copper_products: {
    label: "Organic Copper-based Products",
    description: "Copper fungicide products permitted under UK Organic Regs 2020 Annex II",
    authority: "UK Organic Regs 2020 / HSE MAPP",
    authorityUrl: "https://www.hse.gov.uk/pesticides/",
    reviewFrequency: "Annual",
    items: [
      "Bordeaux Mixture WP", "Copper Hydroxide WP",
      "Copper Oxychloride WP", "Copper Sulfate (tribasic)",
      "Cuprofix Ultra 40 Disperss", "Funguran Progress",
      "Kocide Opti", "Nordox 75 WG", "Trophy WG", "Other",
    ],
  },
  spray_application_reasons: {
    label: "Spray Application Reasons",
    description: "Standard reasons for PPP application — required by the Plant Protection Products (Sustainable Use) Regulations 2012 and Red Tractor Combinable Crops standard",
    authority: "Red Tractor / PPP (Sustainable Use) Regulations 2012",
    authorityUrl: "https://www.legislation.gov.uk/uksi/2012/1657",
    reviewFrequency: "Annual",
    items: [
      { label: "Pre-emergence weed control", group: "Herbicide / Weed Control" },
      { label: "Post-emergence weed control", group: "Herbicide / Weed Control" },
      { label: "Grass weed control (blackgrass / brome / ryegrass)", group: "Herbicide / Weed Control" },
      { label: "Broad-leaved weed control", group: "Herbicide / Weed Control" },
      { label: "Wild oat control", group: "Herbicide / Weed Control" },
      { label: "Volunteer crop control", group: "Herbicide / Weed Control" },
      { label: "Disease control — preventative", group: "Fungicide / Disease Control" },
      { label: "Disease control — threshold exceeded", group: "Fungicide / Disease Control" },
      { label: "Septoria tritici blotch control", group: "Fungicide / Disease Control" },
      { label: "Yellow rust control", group: "Fungicide / Disease Control" },
      { label: "Brown rust control", group: "Fungicide / Disease Control" },
      { label: "Powdery mildew control", group: "Fungicide / Disease Control" },
      { label: "Fusarium / ear blight control", group: "Fungicide / Disease Control" },
      { label: "Ramularia / net blotch control (barley)", group: "Fungicide / Disease Control" },
      { label: "Sclerotinia control (OSR)", group: "Fungicide / Disease Control" },
      { label: "Lodging prevention (PGR)", group: "Growth Regulation" },
      { label: "Straw shortening / stem extension management", group: "Growth Regulation" },
      { label: "Pre-harvest desiccation", group: "Harvest Management" },
      { label: "Harvest aid / pre-harvest management", group: "Harvest Management" },
      { label: "Aphid control (BYDV risk)", group: "Pest Control" },
      { label: "Cabbage stem flea beetle control (OSR)", group: "Pest Control" },
      { label: "Slug control", group: "Pest Control" },
      { label: "Other pest control", group: "Pest Control" },
      { label: "Agronomist recommendation (BASIS/FACTS)", group: "Other" },
      { label: "Statutory / regulatory requirement", group: "Other" },
      { label: "Other", group: "Other" },
    ],
  },
  spray_bbch_stages: {
    label: "Growth Stages (BBCH Scale)",
    description: "Standard BBCH principal and secondary growth stages used for timing spray applications on arable and horticultural crops in the UK",
    authority: "BBCH Monograph — Federal Biological Research Centre for Agriculture and Forestry (BBA), Germany",
    authorityUrl: "https://www.julius-kuehn.de/media/Veroeffentlichungen/bbch%20epaper%20en/page.pdf",
    reviewFrequency: "Static",
    items: [
      { label: "BBCH 00 — Dry seed / dormant", group: "Germination" },
      { label: "BBCH 03 — Imbibition complete", group: "Germination" },
      { label: "BBCH 05 — Radicle emerged from seed", group: "Germination" },
      { label: "BBCH 07 — Coleoptile emerged from seed", group: "Germination" },
      { label: "BBCH 09 — Emergence (coleoptile through soil)", group: "Germination" },
      { label: "BBCH 10 — First leaf through coleoptile", group: "Leaf Development" },
      { label: "BBCH 11 — First leaf unfolded", group: "Leaf Development" },
      { label: "BBCH 12 — 2 leaves unfolded", group: "Leaf Development" },
      { label: "BBCH 13 — 3 leaves unfolded", group: "Leaf Development" },
      { label: "BBCH 14 — 4 leaves unfolded", group: "Leaf Development" },
      { label: "BBCH 15 — 5 leaves unfolded", group: "Leaf Development" },
      { label: "BBCH 16 — 6 leaves unfolded", group: "Leaf Development" },
      { label: "BBCH 19 — 9 or more leaves unfolded", group: "Leaf Development" },
      { label: "BBCH 20 — No tillers", group: "Tillering" },
      { label: "BBCH 21 — 1 tiller", group: "Tillering" },
      { label: "BBCH 22 — 2 tillers", group: "Tillering" },
      { label: "BBCH 23 — 3 tillers", group: "Tillering" },
      { label: "BBCH 25 — 5 tillers", group: "Tillering" },
      { label: "BBCH 29 — End of tillering", group: "Tillering" },
      { label: "BBCH 30 — Pseudo-stem erect / stem elongation begins", group: "Stem Elongation" },
      { label: "BBCH 31 — 1st node detectable (GS31)", group: "Stem Elongation" },
      { label: "BBCH 32 — 2nd node detectable (GS32)", group: "Stem Elongation" },
      { label: "BBCH 33 — 3rd node detectable (GS33)", group: "Stem Elongation" },
      { label: "BBCH 37 — Flag leaf just visible (GS37)", group: "Stem Elongation" },
      { label: "BBCH 39 — Flag leaf fully unrolled / ligule visible", group: "Stem Elongation" },
      { label: "BBCH 41 — Flag leaf sheath extending", group: "Booting" },
      { label: "BBCH 43 — Boot just visibly swollen", group: "Booting" },
      { label: "BBCH 45 — Boot swollen (GS45)", group: "Booting" },
      { label: "BBCH 47 — Flag leaf sheath opening", group: "Booting" },
      { label: "BBCH 49 — First awns visible (barley)", group: "Booting" },
      { label: "BBCH 51 — First spikelet / awn tip just visible (GS51)", group: "Ear / Head Emergence" },
      { label: "BBCH 55 — Half of ear emerged (GS55)", group: "Ear / Head Emergence" },
      { label: "BBCH 59 — Ear / head fully emerged (GS59)", group: "Ear / Head Emergence" },
      { label: "BBCH 61 — Beginning of anthesis / first flowers open", group: "Flowering" },
      { label: "BBCH 65 — Anthesis half-way (GS65)", group: "Flowering" },
      { label: "BBCH 69 — Anthesis complete", group: "Flowering" },
      { label: "BBCH 71 — Water / watery ripe (GS71)", group: "Milk Development" },
      { label: "BBCH 73 — Early milk (GS73)", group: "Milk Development" },
      { label: "BBCH 75 — Medium milk (GS75)", group: "Milk Development" },
      { label: "BBCH 77 — Late milk (GS77)", group: "Milk Development" },
      { label: "BBCH 83 — Early dough (GS83)", group: "Dough Development" },
      { label: "BBCH 85 — Soft dough (GS85)", group: "Dough Development" },
      { label: "BBCH 87 — Hard dough (GS87)", group: "Dough Development" },
      { label: "BBCH 91 — Grain hard, difficult to divide", group: "Ripening" },
      { label: "BBCH 92 — Grain hard", group: "Ripening" },
      { label: "BBCH 97 — Plant dead and collapsing", group: "Ripening" },
      { label: "BBCH 99 — Harvested product", group: "Ripening" },
    ],
  },
};

export async function seedLookupDefaults(): Promise<void> {
  for (const [key, def] of Object.entries(LOOKUP_DEFINITIONS)) {
    const existing = await db
      .select({ id: lookupItemsTable.id })
      .from(lookupItemsTable)
      .where(and(eq(lookupItemsTable.lookupKey, key), isNull(lookupItemsTable.tenantId)))
      .limit(1);

    if (existing.length > 0) continue;

    const rows = def.items.map((item, idx) => {
      if (typeof item === "string") {
        return {
          lookupKey: key,
          value: item,
          label: item,
          groupLabel: null,
          displayOrder: idx,
          isActive: true,
          isBdeManaged: true,
          tenantId: null,
        };
      }
      return {
        lookupKey: key,
        value: item.label,
        label: item.label,
        groupLabel: item.group ?? null,
        displayOrder: idx,
        isActive: true,
        isBdeManaged: true,
        tenantId: null,
      };
    });

    if (rows.length > 0) {
      await db.insert(lookupItemsTable).values(rows);
    }
  }
}
