/**
 * E2E: enterprise breakdown rows toggle the transaction filter.
 *
 * The financial response is fulfilled from a test-owned browser fixture so the
 * check never depends on enterprise-tagged records existing in the shared farm.
 */

import { expect, test } from "@playwright/test";
import { signInDashboard } from "./auth";

const TENANT_SLUG = "oakfield-farms";
const FARM_ID = 5;
const YEAR = new Date().getFullYear();

const FIXTURE_RECORDS = [
  {
    id: 9_291_001,
    transactionDate: `${YEAR}-03-14T12:00:00.000Z`,
    transactionType: "income",
    category: "Crop sales",
    description: "Enterprise fixture wheat sale",
    amountPence: 125_000,
    vatAmountPence: 0,
    enterprise: "Arable",
    vendorCustomer: "Fixture Grain Buyer",
    reference: "E2E-ARABLE",
    isAutoGenerated: false,
  },
  {
    id: 9_291_002,
    transactionDate: `${YEAR}-04-18T12:00:00.000Z`,
    transactionType: "expense",
    category: "Crop protection",
    description: "Enterprise fixture vineyard spray",
    amountPence: 25_000,
    vatAmountPence: 5_000,
    enterprise: "Viticulture",
    vendorCustomer: "Fixture Vineyard Supplier",
    reference: "E2E-VITICULTURE",
    isAutoGenerated: false,
  },
] as const;

async function openTransactionsTab(page: import("@playwright/test").Page) {
  await page.route(
    `**/api/farms/${FARM_ID}/financial-transactions`,
    route => route.fulfill({ json: { records: FIXTURE_RECORDS } }),
  );
  await page.route(
    `**/api/farms/${FARM_ID}/agri-env-projects`,
    route => route.fulfill({ json: { projects: [] } }),
  );

  await signInDashboard(page);
  await page.evaluate(
    ([slug, farmId]) => {
      localStorage.setItem("farmtrac_tenantSlug", slug);
      localStorage.setItem(
        "farmtrac-storage",
        JSON.stringify({ state: { tenantSlug: slug, farmId }, version: 0 }),
      );
      localStorage.setItem(`financial-active-tab-${farmId}`, "transactions");
      for (const filter of ["type", "source", "year", "enterprise"]) {
        localStorage.removeItem(
          `financial-transactions-${filter}-filter-${farmId}`,
        );
      }
    },
    [TENANT_SLUG, FARM_ID] as const,
  );

  await page.goto("/dashboard/financial", { waitUntil: "networkidle" });
  await expect(
    page.getByText("Income & Expenses by Enterprise", { exact: false }),
  ).toBeVisible({ timeout: 20_000 });
}

test("clicking an enterprise breakdown row applies and clears its filter", async ({
  page,
}) => {
  await openTransactionsTab(page);

  const arableRow = page.locator('tr[title="Filter to Arable transactions"]');
  const viticultureRow = page.locator(
    'tr[title="Filter to Viticulture transactions"]',
  );
  const arableTransaction = page.getByText(
    "Enterprise fixture wheat sale",
    { exact: true },
  );
  const viticultureTransaction = page.getByText(
    "Enterprise fixture vineyard spray",
    { exact: true },
  );

  await expect(arableRow).toBeVisible();
  await expect(viticultureRow).toBeVisible();
  await expect(arableTransaction).toBeVisible();
  await expect(viticultureTransaction).toBeVisible();
  await expect(arableRow).not.toHaveCSS("background-color", "rgb(240, 253, 244)");

  await arableRow.click();

  await expect(arableRow).toHaveCSS("background-color", "rgb(240, 253, 244)");
  await expect(arableTransaction).toBeVisible();
  await expect(viticultureTransaction).toHaveCount(0);

  await arableRow.click();

  await expect(arableRow).not.toHaveCSS("background-color", "rgb(240, 253, 244)");
  await expect(arableTransaction).toBeVisible();
  await expect(viticultureTransaction).toBeVisible();
});