// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-variants/CustomisableView.tsx": () => import("../components/mockups/home-variants/CustomisableView.tsx"),
  "./components/mockups/home-variants/ManagerView.tsx": () => import("../components/mockups/home-variants/ManagerView.tsx"),
  "./components/mockups/home-variants/OperativeView.tsx": () => import("../components/mockups/home-variants/OperativeView.tsx"),
  "./components/mockups/seed-store/AllocationTab.tsx": () => import("../components/mockups/seed-store/AllocationTab.tsx"),
  "./components/mockups/seed-store/InlineExpansion.tsx": () => import("../components/mockups/seed-store/InlineExpansion.tsx")
};
