/**
 * Global fetch interceptor to automatically attach the required `x-tenant-slug`
 * header to all API requests generated by the Orval client, as well as ensure
 * credentials are included for Replit Auth.
 */

const originalFetch = window.fetch;

window.fetch = async (...args) => {
  const [resource, config] = args;
  
  // Clone config to avoid mutating the original reference
  const newConfig: RequestInit = { ...config };
  
  // Initialize Headers object safely
  newConfig.headers = new Headers(config?.headers || {});
  
  // Retrieve the selected tenant slug from local storage
  const tenantSlug = localStorage.getItem('farmtrac_tenantSlug');
  
  if (tenantSlug) {
    (newConfig.headers as Headers).set('x-tenant-slug', tenantSlug);
  }
  
  // Always include credentials for cookie-based Replit Auth
  newConfig.credentials = 'include';
  
  return originalFetch(resource, newConfig);
};

export {};
