/**
 * Global fetch interceptor to automatically attach the required `x-tenant-slug`
 * header to all API requests generated by the Orval client, as well as ensure
 * Clerk session cookies are included for same-origin browser API requests.
 */

const originalFetch = window.fetch;

function isLocalRequest(resource: RequestInfo | URL): boolean {
  try {
    const url = typeof resource === "string" ? new URL(resource, window.location.origin) : resource instanceof Request ? new URL(resource.url) : resource;
    return url.origin === window.location.origin;
  } catch {
    return true;
  }
}

window.fetch = async (...args) => {
  const [resource, config] = args;

  if (!isLocalRequest(resource)) {
    return originalFetch(resource, config);
  }
  
  const newConfig: RequestInit = { ...config };
  
  newConfig.headers = new Headers(config?.headers || {});
  
  const tenantSlug = localStorage.getItem('farmtrac_tenantSlug');
  
  if (tenantSlug) {
    (newConfig.headers as Headers).set('x-tenant-slug', tenantSlug);
  }
  
  const bypassToken = import.meta.env.VITE_DEV_BYPASS_TOKEN;
  if (bypassToken) {
    (newConfig.headers as Headers).set('x-dev-bypass', bypassToken);
  }

  newConfig.credentials = 'include';
  
  return originalFetch(resource, newConfig);
};

export {};
