import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { herdFlockRegisterTable, livestockAnimalsTable } from "./livestock";

// ─── Beef Weigh-In & Performance Records ─────────────────────────────────────
export const beefWeighRecordsTable = pgTable("beef_weigh_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  weighDate: date("weigh_date").notNull(),
  weighType: text("weigh_type").notNull().default("routine"),
  weighedBy: text("weighed_by"),
  ageClassWeighed: text("age_class_weighed"),
  batchOrGroupRef: text("batch_or_group_ref"),
  numberWeighed: integer("number_weighed").notNull(),
  averageWeightKg: numeric("average_weight_kg", { precision: 7, scale: 2 }),
  lowestWeightKg: numeric("lowest_weight_kg", { precision: 7, scale: 2 }),
  highestWeightKg: numeric("highest_weight_kg", { precision: 7, scale: 2 }),
  targetWeightKg: numeric("target_weight_kg", { precision: 7, scale: 2 }),
  dlwgGPerDay: numeric("dlwg_g_per_day", { precision: 7, scale: 1 }),
  previousWeighDate: date("previous_weigh_date"),
  previousAverageWeightKg: numeric("previous_average_weight_kg", { precision: 7, scale: 2 }),
  daysOnFeed: integer("days_on_feed"),
  targetKillDate: date("target_kill_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Per-animal weigh entries linked to a weigh record ────────────────────────
export const beefAnimalWeighEntriesTable = pgTable("beef_animal_weigh_entries", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  weighRecordId: integer("weigh_record_id").notNull().references(() => beefWeighRecordsTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  earTagNumber: text("ear_tag_number"),
  weightKg: numeric("weight_kg", { precision: 7, scale: 2 }).notNull(),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Beef Finishing Records ───────────────────────────────────────────────────
export const beefFinishingRecordsTable = pgTable("beef_finishing_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  batchRef: text("batch_ref"),
  dateOffGrass: date("date_off_grass"),
  housedDate: date("housed_date"),
  numberOfAnimals: integer("number_of_animals").notNull(),
  averageStartWeightKg: numeric("average_start_weight_kg", { precision: 7, scale: 2 }),
  finishingSystem: text("finishing_system").notNull().default("cereal-based"),
  feedRegimeNotes: text("feed_regime_notes"),
  targetDaysOnFeed: integer("target_days_on_feed"),
  targetKillDate: date("target_kill_date"),
  targetCarcassWeightKg: numeric("target_carcass_weight_kg", { precision: 7, scale: 2 }),
  targetGradeSpec: text("target_grade_spec"),
  abattoirName: text("abattoir_name"),
  bookedKillDate: date("booked_kill_date"),
  actualKillDate: date("actual_kill_date"),
  status: text("status").notNull().default("in-progress"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Deadweight Settlement Notes ─────────────────────────────────────────────
export const beefDeadweightSettlementsTable = pgTable("beef_deadweight_settlements", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  finishingRecordId: integer("finishing_record_id").references(() => beefFinishingRecordsTable.id),
  killDate: date("kill_date").notNull(),
  abattoirName: text("abattoir_name").notNull(),
  abattoirRef: text("abattoir_ref"),
  numberOfHead: integer("number_of_head").notNull(),
  averageCarcassWeightKg: numeric("average_carcass_weight_kg", { precision: 7, scale: 2 }),
  totalCarcassWeightKg: numeric("total_carcass_weight_kg", { precision: 8, scale: 2 }),
  killingOutPercentage: numeric("killing_out_percentage", { precision: 5, scale: 2 }),
  dominantGrade: text("dominant_grade"),
  gradeBreakdown: text("grade_breakdown"),
  averagePricePerKgGbp: numeric("average_price_per_kg_gbp", { precision: 8, scale: 4 }),
  totalValueGbp: numeric("total_value_gbp", { precision: 10, scale: 2 }),
  deadweightLevyGbp: numeric("deadweight_levy_gbp", { precision: 8, scale: 2 }),
  transportCostGbp: numeric("transport_cost_gbp", { precision: 8, scale: 2 }),
  netPaymentGbp: numeric("net_payment_gbp", { precision: 10, scale: 2 }),
  settlementDate: date("settlement_date"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Beef Red Tractor Self-Assessment Checklist ───────────────────────────────
export const beefRedTractorChecklistTable = pgTable("beef_red_tractor_checklists", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  assessmentDate: date("assessment_date").notNull(),
  assessorName: text("assessor_name"),
  assessorOrganisation: text("assessor_organisation"),
  certificateNumber: text("certificate_number"),
  certificateExpiryDate: date("certificate_expiry_date"),
  cattleRegistrationCurrent: boolean("cattle_registration_current").default(false),
  bcmsRecordsComplete: boolean("bcms_records_complete").default(false),
  movementDocumentsOnFile: boolean("movement_documents_on_file").default(false),
  medicineRecordsComplete: boolean("medicine_records_complete").default(false),
  vetHealthPlanInPlace: boolean("vet_health_plan_in_place").default(false),
  withdrawalPeriodsRecorded: boolean("withdrawal_periods_recorded").default(false),
  tbTestingCurrent: boolean("tb_testing_current").default(false),
  mortalityRecordsComplete: boolean("mortality_records_complete").default(false),
  welfareChecksRecorded: boolean("welfare_checks_recorded").default(false),
  bcsRecorded: boolean("bcs_recorded").default(false),
  calvingRecordsComplete: boolean("calving_records_complete").default(false),
  feedRecordsComplete: boolean("feed_records_complete").default(false),
  waterAccessAdequate: boolean("water_access_adequate").default(false),
  biosecurityPlanInPlace: boolean("biosecurity_plan_in_place").default(false),
  staffTrainingRecords: boolean("staff_training_records").default(false),
  manureManagementPlan: boolean("manure_management_plan").default(false),
  overallStatus: text("overall_status").notNull().default("in-progress"),
  nonConformancesCount: integer("non_conformances_count").default(0),
  nonConformanceDetails: text("non_conformance_details"),
  correctiveActionDeadline: date("corrective_action_deadline"),
  nextAssessmentDue: date("next_assessment_due"),
  notes: text("notes"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
