import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

export const carbonAuditsTable = pgTable("carbon_audits", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  auditYear: integer("audit_year").notNull(),
  auditDate: date("audit_date").notNull(),
  conductedBy: text("conducted_by").notNull(),
  auditorType: text("auditor_type"),
  auditorStaffId: integer("auditor_staff_id"),
  auditorCompany: text("auditor_company"),
  auditorSupplierId: integer("auditor_supplier_id"),
  auditTool: text("audit_tool"),
  supplyChainRequirement: text("supply_chain_requirement"),
  verificationStatus: text("verification_status"),
  totalScope1TonnesCo2e: numeric("total_scope1_tonnes_co2e", { precision: 10, scale: 3 }),
  totalScope2TonnesCo2e: numeric("total_scope2_tonnes_co2e", { precision: 10, scale: 3 }),
  totalScope3TonnesCo2e: numeric("total_scope3_tonnes_co2e", { precision: 10, scale: 3 }),
  totalTonnesCo2e: numeric("total_tonnes_co2e", { precision: 10, scale: 3 }),
  sequestrationTonnesCo2e: numeric("sequestration_tonnes_co2e", { precision: 10, scale: 3 }),
  netTonnesCo2e: numeric("net_tonnes_co2e", { precision: 10, scale: 3 }),
  intensityPerTonneProd: numeric("intensity_per_tonne_prod", { precision: 10, scale: 3 }),
  reductionTargetPct: numeric("reduction_target_pct", { precision: 5, scale: 1 }),
  certificationBody: text("certification_body"),
  linkedPoReference: text("linked_po_reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const carbonEmissionsRecordsTable = pgTable("carbon_emissions_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  auditId: integer("audit_id").references(() => carbonAuditsTable.id),
  emissionYear: integer("emission_year").notNull(),
  category: text("category").notNull(),
  subcategory: text("subcategory"),
  activityDescription: text("activity_description").notNull(),
  quantity: numeric("quantity", { precision: 12, scale: 3 }),
  unit: text("unit"),
  emissionFactorSource: text("emission_factor_source"),
  tonnesCo2e: numeric("tonnes_co2e", { precision: 10, scale: 4 }).notNull(),
  scope: text("scope").notNull(),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const carbonSequestrationTable = pgTable("carbon_sequestration", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  auditId: integer("audit_id").references(() => carbonAuditsTable.id),
  sequestrationYear: integer("sequestration_year").notNull(),
  featureType: text("feature_type").notNull(),
  featureName: text("feature_name"),
  areaHaOrLengthM: numeric("area_ha_or_length_m", { precision: 10, scale: 3 }),
  unit: text("unit"),
  sequestrationFactorSource: text("sequestration_factor_source"),
  tonnesCo2eSequestered: numeric("tonnes_co2e_sequestered", { precision: 10, scale: 4 }).notNull(),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const carbonReductionActionsTable = pgTable("carbon_reduction_actions", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  actionTitle: text("action_title").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  targetReductionTonnesCo2e: numeric("target_reduction_tonnes_co2e", { precision: 8, scale: 3 }),
  plannedStartDate: date("planned_start_date"),
  plannedCompletionDate: date("planned_completion_date"),
  actualCompletionDate: date("actual_completion_date"),
  status: text("status").notNull().default("planned"),
  estimatedCost: numeric("estimated_cost", { precision: 10, scale: 2 }),
  fundingSource: text("funding_source"),
  fundingType: text("funding_type"),
  fundingGrantName: text("funding_grant_name"),
  fundingGrantReference: text("funding_grant_reference"),
  responsiblePerson: text("responsible_person"),
  targetSourceType: text("target_source_type"),
  contractorName: text("contractor_name"),
  contractorCompany: text("contractor_company"),
  contractorType: text("contractor_type"),
  contractorSupplierId: integer("contractor_supplier_id"),
  linkedPoReference: text("linked_po_reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const renewableEnergyProductionTable = pgTable("renewable_energy_production", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  productionYear: integer("production_year").notNull(),
  periodStart: date("period_start").notNull(),
  periodEnd: date("period_end").notNull(),
  technologyType: text("technology_type").notNull(),
  systemName: text("system_name"),
  installedCapacityKw: numeric("installed_capacity_kw", { precision: 8, scale: 2 }),
  generationKwh: numeric("generation_kwh", { precision: 10, scale: 2 }).notNull(),
  selfConsumedKwh: numeric("self_consumed_kwh", { precision: 10, scale: 2 }),
  exportedKwh: numeric("exported_kwh", { precision: 10, scale: 2 }),
  exportTariffPencePerKwh: numeric("export_tariff_pence_per_kwh", { precision: 6, scale: 2 }),
  exportRevenueGbp: numeric("export_revenue_gbp", { precision: 10, scale: 2 }),
  fitRocReference: text("fit_roc_reference"),
  co2AvoidedTonnes: numeric("co2_avoided_tonnes", { precision: 8, scale: 3 }),
  meterReadingStart: numeric("meter_reading_start", { precision: 12, scale: 2 }),
  meterReadingEnd: numeric("meter_reading_end", { precision: 12, scale: 2 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const biodiversityNetGainTable = pgTable("biodiversity_net_gain", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  assessmentDate: date("assessment_date").notNull(),
  recordType: text("record_type").notNull().default("baseline"),
  // Who carried out the assessment
  assessorType: text("assessor_type"),
  assessorName: text("assessor_name"),
  assessorOrganisation: text("assessor_organisation"),
  assessmentTool: text("assessment_tool").notNull().default("Defra Metric 4.0"),
  // Habitat
  habitatType: text("habitat_type").notNull(),
  habitatDescription: text("habitat_description"),
  areaHa: numeric("area_ha", { precision: 8, scale: 4 }).notNull(),
  // Baseline condition & units (from original survey / Defra Metric tool)
  baselineCondition: text("baseline_condition").notNull(),
  baselineUnits: numeric("baseline_units", { precision: 8, scale: 3 }),
  // Target committed in management agreement
  targetCondition: text("target_condition"),
  targetUnits: numeric("target_units", { precision: 8, scale: 3 }),
  netGainUnits: numeric("net_gain_units", { precision: 8, scale: 3 }),
  // Monitoring results (post-creation / annual-monitoring / final-assessment)
  achievedCondition: text("achieved_condition"),
  achievedUnits: numeric("achieved_units", { precision: 8, scale: 3 }),
  complianceStatus: text("compliance_status"),
  remedialActionNotes: text("remedial_action_notes"),
  // Legal agreement
  legalAgreementType: text("legal_agreement_type"),
  planningReference: text("planning_reference"),
  managementCommitmentYears: integer("management_commitment_years"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const sustainabilityReportsTable = pgTable("sustainability_reports", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  reportYear: integer("report_year").notNull(),
  reportTitle: text("report_title").notNull(),
  reportType: text("report_type"),
  generatedDate: date("generated_date").notNull(),
  status: text("status").notNull().default("draft"),
  // Supply chain customer
  supplyChainCustomer: text("supply_chain_customer"),
  contactNameAtCustomer: text("contact_name_at_customer"),
  deadlineDate: date("deadline_date"),
  // Submission tracking
  submittedToCustomer: boolean("submitted_to_customer").default(false),
  submissionMethod: text("submission_method"),
  submissionDate: date("submission_date"),
  customerReference: text("customer_reference"),
  acknowledgedDate: date("acknowledged_date"),
  // Key metrics from the report
  totalEmissionsTonnesCo2e: numeric("total_emissions_tonnes_co2e", { precision: 10, scale: 3 }),
  sequestrationTonnesCo2e: numeric("sequestration_tonnes_co2e", { precision: 10, scale: 3 }),
  netPositionTonnesCo2e: numeric("net_position_tonnes_co2e", { precision: 10, scale: 3 }),
  // Report source / preparer
  preparedBy: text("prepared_by"),
  certifyingBody: text("certifying_body"),
  certificateReference: text("certificate_reference"),
  // Storage
  reportUrl: text("report_url"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
