import { pgTable, text, serial, integer, timestamp, boolean, varchar, jsonb, uniqueIndex, numeric } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const tenantsTable = pgTable("tenants", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  contactEmail: text("contact_email").notNull(),
  contactPhone: text("contact_phone"),
  address: text("address"),
  isActive: boolean("is_active").notNull().default(true),
  stripeCustomerId: text("stripe_customer_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const farmsTable = pgTable("farms", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  name: text("name").notNull(),
  address: text("address"),
  postcode: text("postcode"),
  cphNumber: text("cph_number"),
  gridReference: text("grid_reference"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  what3words: text("what3words"),
  emergencyContactName: text("emergency_contact_name"),
  emergencyContactRelationship: text("emergency_contact_relationship"),
  emergencyContactPhone: text("emergency_contact_phone"),
  emergencyContactEmail: text("emergency_contact_email"),
  totalAcreage: integer("total_acreage"),
  sectorArable: boolean("sector_arable").notNull().default(false),
  sectorBeef: boolean("sector_beef").notNull().default(false),
  sectorDairy: boolean("sector_dairy").notNull().default(false),
  sectorPigs: boolean("sector_pigs").notNull().default(false),
  sectorPoultry: boolean("sector_poultry").notNull().default(false),
  sectorHorticulture: boolean("sector_horticulture").notNull().default(false),
  sectorSheep: boolean("sector_sheep").notNull().default(false),
  sectorEggs: boolean("sector_eggs").notNull().default(false),
  sectorGoats: boolean("sector_goats").notNull().default(false),
  sectorEquine: boolean("sector_equine").notNull().default(false),
  sectorViticulture: boolean("sector_viticulture").notNull().default(false),
  redTractorId: text("red_tractor_id"),
  sbiNumber: text("sbi_number"),
  totalHectares: numeric("total_hectares", { precision: 10, scale: 2 }),
  isNvzDesignated: boolean("is_nvz_designated").notNull().default(false),
  farmManager: text("farm_manager"),
  holdingType: text("holding_type"),
  assuranceBody: text("assurance_body"),
  eaml2Email: text("eaml2_email"),
  flockMark: text("flock_mark"),
  herdMark: text("herd_mark"),
  bcmsHoldingNumber: text("bcms_holding_number"),
  country: text("country").notNull().default("england"),
  scotEidNumber: text("scot_eid_number"),
  eidCymruNumber: text("eid_cymru_number"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const rolesTable = pgTable("roles", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").references(() => tenantsTable.id),
  name: text("name").notNull(),
  description: text("description"),
  isSystemRole: boolean("is_system_role").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const modulesTable = pgTable("modules", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  monthlyPricePence: integer("monthly_price_pence").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  requiresSector: text("requires_sector"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const permissionsTable = pgTable("permissions", {
  id: serial("id").primaryKey(),
  roleId: integer("role_id").notNull().references(() => rolesTable.id),
  moduleId: integer("module_id").notNull().references(() => modulesTable.id),
  farmId: integer("farm_id").references(() => farmsTable.id),
  canRead: boolean("can_read").notNull().default(true),
  canWrite: boolean("can_write").notNull().default(false),
  canDelete: boolean("can_delete").notNull().default(false),
  canApprove: boolean("can_approve").notNull().default(false),
});

export const userTenantsTable = pgTable("user_tenants", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  roleId: integer("role_id").notNull().references(() => rolesTable.id),
  isSuperAdmin: boolean("is_super_admin").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  receiveAlerts: boolean("receive_alerts").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => [
  uniqueIndex("user_tenant_unique").on(table.userId, table.tenantId),
]);

export const staffFarmAssignmentsTable = pgTable("staff_farm_assignments", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  roleId: integer("role_id").references(() => rolesTable.id),
  farmRole: text("farm_role").notNull().default("operator"),
  accessType: text("access_type").notNull().default("full"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("staff_farm_unique").on(table.userId, table.farmId),
]);

export const subscriptionsTable = pgTable("subscriptions", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  moduleId: integer("module_id").notNull().references(() => modulesTable.id),
  stripeSubscriptionId: text("stripe_subscription_id"),
  stripeSubscriptionItemId: text("stripe_subscription_item_id"),
  status: text("status").notNull().default("active"),
  currentPeriodStart: timestamp("current_period_start", { withTimezone: true }),
  currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const notificationsTable = pgTable("notifications", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  type: text("type").notNull(),
  severity: text("severity").notNull().default("warning"),
  title: text("title").notNull(),
  message: text("message").notNull(),
  isRead: boolean("is_read").notNull().default(false),
  relatedModule: text("related_module"),
  relatedId: integer("related_id"),
  dedupeKey: text("dedupe_key").unique(),
  readAt: timestamp("read_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const userInvitationsTable = pgTable("user_invitations", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  farmId: integer("farm_id").references(() => farmsTable.id),
  email: text("email").notNull(),
  firstName: text("first_name"),
  lastName: text("last_name"),
  roleId: integer("role_id").notNull().references(() => rolesTable.id),
  farmRole: text("farm_role").notNull().default("operator"),
  accessType: text("access_type").notNull().default("full"),
  token: text("token").notNull().unique(),
  invitedBy: varchar("invited_by").notNull(),
  staffMemberId: integer("staff_member_id"),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const invoicesTable = pgTable("invoices", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  invoiceNumber: text("invoice_number").notNull().unique(),
  status: text("status").notNull().default("draft"),
  billingPeriodStart: timestamp("billing_period_start", { withTimezone: true }).notNull(),
  billingPeriodEnd: timestamp("billing_period_end", { withTimezone: true }).notNull(),
  invoiceDate: timestamp("invoice_date", { withTimezone: true }).notNull(),
  dueDate: timestamp("due_date", { withTimezone: true }).notNull(),
  billingName: text("billing_name").notNull(),
  billingAddress: text("billing_address"),
  billingEmail: text("billing_email").notNull(),
  lineItems: jsonb("line_items").notNull().default([]),
  netAmountPence: integer("net_amount_pence").notNull(),
  vatRatePct: integer("vat_rate_pct").notNull().default(20),
  vatAmountPence: integer("vat_amount_pence").notNull(),
  grossAmountPence: integer("gross_amount_pence").notNull(),
  notes: text("notes"),
  paymentMethod: text("payment_method"),
  paymentReference: text("payment_reference"),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const farmMembersTable = pgTable("farm_members", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  linkedUserId: varchar("linked_user_id"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  jobTitle: text("job_title"),
  employedFrom: timestamp("employed_from", { withTimezone: true }),
  employedTo: timestamp("employed_to", { withTimezone: true }),
  farmRole: text("farm_role").notNull().default("operator"),
  accessType: text("access_type").notNull().default("none"),
  invitationStatus: text("invitation_status").notNull().default("not_invited"),
  isActive: boolean("is_active").notNull().default(true),
  notes: text("notes"),
  niNumber: text("ni_number"),
  payrollNumber: text("payroll_number"),
  nokName: text("nok_name"),
  nokRelationship: text("nok_relationship"),
  nokPhone: text("nok_phone"),
  nokEmail: text("nok_email"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
