import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

export const diversificationActivitiesTable = pgTable("diversification_activities", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  activityName: text("activity_name").notNull(),
  activityType: text("activity_type").notNull(),
  startDate: date("start_date").notNull(),
  planningPermissionRef: text("planning_permission_ref"),
  planningPermissionGranted: boolean("planning_permission_granted"),
  insurancePolicyNumber: text("insurance_policy_number"),
  insuranceRenewalDate: date("insurance_renewal_date"),
  annualTurnover: numeric("annual_turnover", { precision: 12, scale: 2 }),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const farmShopProductsTable = pgTable("farm_shop_products", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  productName: text("product_name").notNull(),
  category: text("category").notNull(),
  description: text("description"),
  unitOfSale: text("unit_of_sale"),
  pricePerUnit: numeric("price_per_unit", { precision: 8, scale: 2 }),
  costPrice: numeric("cost_price", { precision: 8, scale: 2 }),
  currentStock: numeric("current_stock", { precision: 10, scale: 2 }).default("0"),
  reorderLevel: numeric("reorder_level", { precision: 10, scale: 2 }).default("0"),
  allergens: text("allergens").array(),
  countryOfOrigin: text("country_of_origin"),
  bestBeforeDays: integer("best_before_days"),
  storageRequirements: text("storage_requirements"),
  foodBusinessRegNumber: text("food_business_reg_number"),
  active: boolean("active").default(true),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const farmShopSuppliersTable = pgTable("farm_shop_suppliers", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  supplierName: text("supplier_name").notNull(),
  contactName: text("contact_name"),
  phone: text("phone"),
  email: text("email"),
  address: text("address"),
  accountRef: text("account_ref"),
  paymentTerms: text("payment_terms"),
  notes: text("notes"),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const farmShopPurchasesTable = pgTable("farm_shop_purchases", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  supplierId: integer("supplier_id").references(() => farmShopSuppliersTable.id),
  productId: integer("product_id").references(() => farmShopProductsTable.id),
  productName: text("product_name").notNull(),
  purchaseDate: date("purchase_date").notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull(),
  unitOfPurchase: text("unit_of_purchase"),
  costPerUnit: numeric("cost_per_unit", { precision: 8, scale: 2 }).notNull(),
  totalCost: numeric("total_cost", { precision: 12, scale: 2 }).notNull(),
  invoiceRef: text("invoice_ref"),
  deliveryDate: date("delivery_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const farmShopSalesSessionsTable = pgTable("farm_shop_sales_sessions", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  saleDate: date("sale_date").notNull(),
  notes: text("notes"),
  totalNet: numeric("total_net", { precision: 12, scale: 2 }).notNull().default("0"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const farmShopSaleItemsTable = pgTable("farm_shop_sale_items", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").notNull().references(() => farmShopSalesSessionsTable.id),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  productId: integer("product_id").references(() => farmShopProductsTable.id),
  productName: text("product_name").notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull(),
  unitOfSale: text("unit_of_sale"),
  pricePerUnit: numeric("price_per_unit", { precision: 8, scale: 2 }).notNull(),
  lineTotal: numeric("line_total", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const farmShopHygieneInspectionsTable = pgTable("farm_shop_hygiene_inspections", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  inspectionDate: date("inspection_date").notNull(),
  inspectorName: text("inspector_name"),
  inspectorOrganisation: text("inspector_organisation"),
  inspectionType: text("inspection_type").notNull(),
  hygieneRating: integer("hygiene_rating"),
  findingsSummary: text("findings_summary"),
  correctiveActions: text("corrective_actions"),
  reinspectionRequired: boolean("reinspection_required").default(false),
  reinspectionDate: date("reinspection_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const equineRecordsTable = pgTable("equine_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  horseName: text("horse_name").notNull(),
  passportNumber: text("passport_number"),
  uelnNumber: text("ueln_number"),
  breed: text("breed"),
  colour: text("colour"),
  sex: text("sex"),
  dateOfBirth: date("date_of_birth"),
  microchipNumber: text("microchip_number"),
  ownerName: text("owner_name"),
  liveryType: text("livery_type"),
  box: text("box"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const equineHealthEventsTable = pgTable("equine_health_events", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  horseId: integer("horse_id").notNull().references(() => equineRecordsTable.id),
  eventDate: date("event_date").notNull(),
  eventType: text("event_type").notNull(),
  vetOrFarrierName: text("vet_or_farrier_name"),
  treatmentGiven: text("treatment_given"),
  productUsed: text("product_used"),
  batchNumber: text("batch_number"),
  withdrawalPeriodDays: integer("withdrawal_period_days"),
  cost: numeric("cost", { precision: 8, scale: 2 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const renewableEnergyInstallationsTable = pgTable("renewable_energy_installations", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  installationName: text("installation_name").notNull(),
  technologyType: text("technology_type").notNull(),
  installedCapacityKw: numeric("installed_capacity_kw", { precision: 8, scale: 2 }),
  installationDate: date("installation_date"),
  installerName: text("installer_name"),
  gridConnectionRef: text("grid_connection_ref"),
  fitOrSegContractRef: text("fit_or_seg_contract_ref"),
  tariffProvider: text("tariff_provider"),
  tariffRatePence: numeric("tariff_rate_pence", { precision: 6, scale: 2 }),
  maintenanceContractor: text("maintenance_contractor"),
  nextServiceDate: date("next_service_date"),
  notes: text("notes"),
  panelCount: integer("panel_count"),
  mcsCertificateNumber: text("mcs_certificate_number"),
  installerMcsNumber: text("installer_mcs_number"),
  buildingName: text("building_name"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const renewableEnergyMeterReadingsTable = pgTable("renewable_energy_meter_readings", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  installationId: integer("installation_id").notNull().references(() => renewableEnergyInstallationsTable.id),
  readingDate: date("reading_date").notNull(),
  meterReference: text("meter_reference"),
  generationKwh: numeric("generation_kwh", { precision: 10, scale: 2 }),
  exportKwh: numeric("export_kwh", { precision: 10, scale: 2 }),
  selfConsumedKwh: numeric("self_consumed_kwh", { precision: 10, scale: 2 }),
  fitPaymentPeriod: text("fit_payment_period"),
  fitPaymentAmount: numeric("fit_payment_amount", { precision: 8, scale: 2 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const solarExportPaymentsTable = pgTable("solar_export_payments", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  installationId: integer("installation_id").references(() => renewableEnergyInstallationsTable.id),
  paymentDate: date("payment_date").notNull(),
  periodFrom: date("period_from"),
  periodTo: date("period_to"),
  exportKwh: numeric("export_kwh", { precision: 10, scale: 2 }),
  rateUsedPencePerKwh: numeric("rate_used_pence_per_kwh", { precision: 6, scale: 2 }),
  paymentAmountPence: integer("payment_amount_pence").notNull(),
  paymentReference: text("payment_reference"),
  supplierName: text("supplier_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const diversificationIncomeRecordsTable = pgTable("diversification_income_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  activityId: integer("activity_id").references(() => diversificationActivitiesTable.id),
  incomeDate: date("income_date").notNull(),
  incomeType: text("income_type").notNull(),
  description: text("description"),
  amountNet: numeric("amount_net", { precision: 12, scale: 2 }).notNull(),
  vatRate: text("vat_rate").notNull().default("exempt"),
  vatAmount: numeric("vat_amount", { precision: 10, scale: 2 }),
  customerName: text("customer_name"),
  invoiceRef: text("invoice_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const shootingAndGameRecordsTable = pgTable("shooting_and_game_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  shootDate: date("shoot_date").notNull(),
  shootType: text("shoot_type").notNull(),
  organiser: text("organiser"),
  numberOfGuns: integer("number_of_guns"),
  gamekeeperName: text("gamekeeper_name"),
  bagsPheasant: integer("bags_pheasant").default(0),
  bagsPartridge: integer("bags_partridge").default(0),
  bagsGrouse: integer("bags_grouse").default(0),
  bagsDuck: integer("bags_duck").default(0),
  bagsWoodcock: integer("bags_woodcock").default(0),
  bagsOther: integer("bags_other").default(0),
  totalBag: integer("total_bag").default(0),
  gameDealer: text("game_dealer"),
  incomeLeaseFee: numeric("income_lease_fee", { precision: 10, scale: 2 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
