import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { fieldsTable } from "./fields-crops";

export const environmentalFeaturesTable = pgTable("environmental_features", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  fieldId: integer("field_id").references(() => fieldsTable.id),
  featureType: text("feature_type").notNull(),
  description: text("description"),
  areaHectares: numeric("area_hectares", { precision: 10, scale: 4 }),
  isEnclosed: boolean("is_enclosed").notNull().default(false),
  lengthMetres: numeric("length_metres", { precision: 10, scale: 2 }),
  managementPractice: text("management_practice"),
  dateRecorded: timestamp("date_recorded", { withTimezone: true }).notNull().defaultNow(),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const environmentalAssessmentsTable = pgTable("environmental_assessments", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  assessorName: text("assessor_name").notNull(),
  assessorOrganisation: text("assessor_organisation"),
  assessmentDate: timestamp("assessment_date", { withTimezone: true }).notNull(),
  outcome: text("outcome").notNull().default("pass"),
  conditions: text("conditions"),
  nextAssessmentDue: timestamp("next_assessment_due", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const agriEnvironmentSchemeRecordsTable = pgTable("agri_environment_scheme_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  schemeName: text("scheme_name").notNull(),
  agreementNumber: text("agreement_number"),
  startDate: timestamp("start_date", { withTimezone: true }).notNull(),
  endDate: timestamp("end_date", { withTimezone: true }),
  annualPaymentPence: integer("annual_payment_pence"),
  obligations: text("obligations"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const environmentalManagementEventsTable = pgTable("environmental_management_events", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  featureId: integer("feature_id").references(() => environmentalFeaturesTable.id, { onDelete: "set null" }),
  featureName: text("feature_name"),
  featureType: text("feature_type"),
  eventDate: timestamp("event_date", { withTimezone: true }).notNull(),
  eventType: text("event_type").notNull(),
  description: text("description"),
  operator: text("operator"),
  contractorUsed: boolean("contractor_used").default(false),
  contractorName: text("contractor_name"),
  followUpActionsNeeded: text("follow_up_actions_needed"),
  schemeId: integer("scheme_id").references(() => agriEnvironmentSchemeRecordsTable.id, { onDelete: "set null" }),
  schemeName: text("scheme_name"),
  fulfilsSchemeObligation: boolean("fulfils_scheme_obligation").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sfiAgreementsTable = pgTable("sfi_agreements", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  agreementNumber: text("agreement_number").notNull(),
  schemeName: text("scheme_name").notNull(),
  agreementStartDate: date("agreement_start_date").notNull(),
  agreementEndDate: date("agreement_end_date").notNull(),
  totalAnnualPayment: numeric("total_annual_payment", { precision: 10, scale: 2 }),
  managingBody: text("managing_body"),
  agentOrAdvisorName: text("agent_or_advisor_name"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sfiActionsTable = pgTable("sfi_actions", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  agreementId: integer("agreement_id").references(() => sfiAgreementsTable.id),
  actionCode: text("action_code").notNull(),
  actionTitle: text("action_title").notNull(),
  landParcelReference: text("land_parcel_reference"),
  eligibleAreaHa: numeric("eligible_area_ha", { precision: 8, scale: 3 }),
  annualPaymentPerHa: numeric("annual_payment_per_ha", { precision: 8, scale: 2 }),
  annualPaymentAmount: numeric("annual_payment_amount", { precision: 10, scale: 2 }),
  evidenceRequired: text("evidence_required"),
  lastEvidenceDate: date("last_evidence_date"),
  nextEvidenceDate: date("next_evidence_date"),
  complianceStatus: text("compliance_status").notNull().default("compliant"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const slurryStoresTable = pgTable("slurry_stores", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  storeName: text("store_name").notNull(),
  storeType: text("store_type").notNull(),
  capacityM3: numeric("capacity_m3", { precision: 8, scale: 1 }),
  material: text("material"),
  status: text("status").default("Compliant"),
  designStandard: text("design_standard"),
  requiredStorageMonths: integer("required_storage_months"),
  freeboard: text("freeboard"),
  liningType: text("lining_type"),
  constructionYear: integer("construction_year"),
  lastInspectionDate: date("last_inspection_date"),
  nextInspectionDue: date("next_inspection_due"),
  agencyRegistrationNumber: text("agency_registration_number"),
  leakDetectionSystem: boolean("leak_detection_system").default(false),
  coverType: text("cover_type"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const slurryStoreInspectionsTable = pgTable("slurry_store_inspections", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  storeId: integer("store_id").notNull().references(() => slurryStoresTable.id, { onDelete: "cascade" }),
  inspectionDate: date("inspection_date").notNull(),
  inspectorName: text("inspector_name"),
  inspectorOrganisation: text("inspector_organisation"),
  outcome: text("outcome").notNull(),
  freeboardOk: boolean("freeboard_ok"),
  freeboardMm: numeric("freeboard_mm", { precision: 6, scale: 0 }),
  leaksOrDamageFound: boolean("leaks_or_damage_found").default(false),
  deficiencies: text("deficiencies"),
  actionsRequired: text("actions_required"),
  nextInspectionDue: date("next_inspection_due"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const slurrySpreadingRecordsTable = pgTable("slurry_spreading_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  storeId: integer("store_id").references(() => slurryStoresTable.id),
  spreadingDate: date("spreading_date").notNull(),
  fieldId: integer("field_id"),
  fieldDescription: text("field_description"),
  fieldAreaHa: numeric("field_area_ha", { precision: 8, scale: 3 }),
  manureType: text("manure_type"),
  applicationMethod: text("application_method"),
  incorporationMethod: text("incorporation_method"),
  volumeAppliedM3: numeric("volume_applied_m3", { precision: 10, scale: 2 }),
  nitrogenAppliedKgHa: numeric("nitrogen_applied_kg_ha", { precision: 8, scale: 2 }),
  soilTemp: numeric("soil_temp_c", { precision: 5, scale: 1 }),
  groundConditions: text("ground_conditions"),
  windSpeed: text("wind_speed"),
  rainInLast24h: boolean("rain_in_last_24h").default(false),
  rainForecast48h: boolean("rain_forecast_48h").default(false),
  bufferFromWaterM: numeric("buffer_from_water_m", { precision: 6, scale: 0 }),
  withinNvzClosedPeriod: boolean("within_nvz_closed_period").default(false),
  operatorName: text("operator_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const slurryStoreFillEventsTable = pgTable("slurry_store_fill_events", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  storeId: integer("store_id").notNull().references(() => slurryStoresTable.id, { onDelete: "cascade" }),
  eventDate: date("event_date").notNull(),
  volumeM3: numeric("volume_m3", { precision: 10, scale: 2 }).notNull(),
  sourceDescription: text("source_description"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
