import { pgTable, text, serial, integer, timestamp, boolean } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

export const equipmentTable = pgTable("equipment", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  assetNumber: text("asset_number"),
  name: text("name").notNull(),
  type: text("type").notNull(),
  make: text("make"),
  model: text("model"),
  serialNumber: text("serial_number"),
  registrationNumber: text("registration_number"),
  yearOfManufacture: integer("year_of_manufacture"),
  purchaseDate: timestamp("purchase_date", { withTimezone: true }),
  purchasePricePence: integer("purchase_price_pence"),
  currentValuePence: integer("current_value_pence"),
  currentHours: integer("current_hours"),
  odometerKm: integer("odometer_km"),
  status: text("status").notNull().default("active"),
  location: text("location"),
  notes: text("notes"),
  photos: text("photos"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const equipmentMaintenanceLogsTable = pgTable("equipment_maintenance_logs", {
  id: serial("id").primaryKey(),
  equipmentId: integer("equipment_id").notNull().references(() => equipmentTable.id),
  maintenanceType: text("maintenance_type").notNull(),
  description: text("description").notNull(),
  performedBy: text("performed_by"),
  performedDate: timestamp("performed_date", { withTimezone: true }).notNull(),
  nextDueDate: timestamp("next_due_date", { withTimezone: true }),
  costPence: integer("cost_pence"),
  partsUsed: text("parts_used"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const equipmentCalibrationRecordsTable = pgTable("equipment_calibration_records", {
  id: serial("id").primaryKey(),
  equipmentId: integer("equipment_id").notNull().references(() => equipmentTable.id),
  calibrationType: text("calibration_type").notNull(),
  calibrationDate: timestamp("calibration_date", { withTimezone: true }).notNull(),
  nextDueDate: timestamp("next_due_date", { withTimezone: true }),
  calibratedBy: text("calibrated_by"),
  certificateReference: text("certificate_reference"),
  resultPass: boolean("result_pass"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const equipmentOffboardingRecordsTable = pgTable("equipment_offboarding_records", {
  id: serial("id").primaryKey(),
  equipmentId: integer("equipment_id").notNull().references(() => equipmentTable.id),
  offboardingDate: timestamp("offboarding_date", { withTimezone: true }).notNull(),
  reason: text("reason").notNull(),
  method: text("method"),
  salePricePence: integer("sale_price_pence"),
  buyerDetails: text("buyer_details"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopJobsTable = pgTable("workshop_jobs", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  equipmentId: integer("equipment_id").references(() => equipmentTable.id),
  jobNumber: text("job_number"),
  jobType: text("job_type").notNull().default("repair"),
  title: text("title").notNull(),
  description: text("description"),
  priority: text("priority").notNull().default("medium"),
  status: text("status").notNull().default("open"),
  reportedBy: text("reported_by"),
  assignedTo: text("assigned_to"),
  openedAt: timestamp("opened_at", { withTimezone: true }).notNull().defaultNow(),
  estimatedCompletionDate: timestamp("estimated_completion_date", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  labourHours: integer("labour_hours"),
  labourCostPence: integer("labour_cost_pence"),
  partsCostPence: integer("parts_cost_pence"),
  partsUsed: text("parts_used"),
  rootCause: text("root_cause"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
