import { pgTable, text, serial, integer, timestamp, boolean, numeric, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { suppliersTable, stockItemsTable } from "./stock-suppliers";
import { farmLocationsTable } from "./farm-locations";
import { storageLocationsTable } from "./fields-crops";
import { farmCustomersTable, serviceInvoicesTable } from "./farm-services";

export const equipmentTable = pgTable("equipment", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  assetNumber: text("asset_number"),
  name: text("name").notNull(),
  type: text("type").notNull(),
  make: text("make"),
  model: text("model"),
  serialNumber: text("serial_number"),
  registrationNumber: text("registration_number"),
  yearOfManufacture: integer("year_of_manufacture"),
  purchaseDate: timestamp("purchase_date", { withTimezone: true }),
  purchasePricePence: integer("purchase_price_pence"),
  currentValuePence: integer("current_value_pence"),
  currentHours: integer("current_hours"),
  odometerKm: integer("odometer_km"),
  status: text("status").notNull().default("active"),
  location: text("location"),
  notes: text("notes"),
  photos: text("photos"),
  isActive: boolean("is_active").notNull().default(true),
  disposalMethod: text("disposal_method"),
  disposalDate: timestamp("disposal_date", { withTimezone: true }),
  disposalPricePence: integer("disposal_price_pence"),
  disposalBuyerOrContractor: text("disposal_buyer_or_contractor"),
  wasteTransferNoteRef: text("waste_transfer_note_ref"),
  disposalNotes: text("disposal_notes"),
  complianceCategory: text("compliance_category"),
  puwerLastAssessmentDate: date("puwer_last_assessment_date"),
  puwerNextReviewDate: date("puwer_next_review_date"),
  puwerAssessor: text("puwer_assessor"),
  puwerOutcome: text("puwer_outcome"),
  puwerNotes: text("puwer_notes"),
  lolerLastExamDate: date("loler_last_exam_date"),
  lolerNextExamDate: date("loler_next_exam_date"),
  lolerExaminer: text("loler_examiner"),
  lolerOutcome: text("loler_outcome"),
  lolerReportRef: text("loler_report_ref"),
  lolerNotes: text("loler_notes"),
  pssrLastExamDate: date("pssr_last_exam_date"),
  pssrNextExamDate: date("pssr_next_exam_date"),
  pssrExaminer: text("pssr_examiner"),
  pssrWrittenSchemeRef: text("pssr_written_scheme_ref"),
  pssrOutcome: text("pssr_outcome"),
  pssrNotes: text("pssr_notes"),
  insurerName: text("insurer_name"),
  insurancePolicyRef: text("insurance_policy_ref"),
  insuranceRenewalDate: date("insurance_renewal_date"),
  insurancePremiumPence: integer("insurance_premium_pence"),
  depreciationMethod: text("depreciation_method"),
  depreciationRatePct: integer("depreciation_rate_pct"),
  gpsTracked: boolean("gps_tracked").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const equipmentMaintenanceLogsTable = pgTable("equipment_maintenance_logs", {
  id: serial("id").primaryKey(),
  equipmentId: integer("equipment_id").notNull().references(() => equipmentTable.id),
  maintenanceType: text("maintenance_type").notNull(),
  description: text("description").notNull(),
  performedBy: text("performed_by"),
  performedDate: timestamp("performed_date", { withTimezone: true }).notNull(),
  nextDueDate: timestamp("next_due_date", { withTimezone: true }),
  costPence: integer("cost_pence"),
  partsUsed: text("parts_used"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const equipmentCalibrationRecordsTable = pgTable("equipment_calibration_records", {
  id: serial("id").primaryKey(),
  equipmentId: integer("equipment_id").notNull().references(() => equipmentTable.id),
  calibrationType: text("calibration_type").notNull(),
  calibrationDate: timestamp("calibration_date", { withTimezone: true }).notNull(),
  nextDueDate: timestamp("next_due_date", { withTimezone: true }),
  calibratedBy: text("calibrated_by"),
  certificateReference: text("certificate_reference"),
  resultPass: boolean("result_pass"),
  notes: text("notes"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const equipmentOffboardingRecordsTable = pgTable("equipment_offboarding_records", {
  id: serial("id").primaryKey(),
  equipmentId: integer("equipment_id").notNull().references(() => equipmentTable.id),
  offboardingDate: timestamp("offboarding_date", { withTimezone: true }).notNull(),
  reason: text("reason").notNull(),
  method: text("method"),
  salePricePence: integer("sale_price_pence"),
  buyerDetails: text("buyer_details"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopJobsTable = pgTable("workshop_jobs", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  equipmentId: integer("equipment_id").references(() => equipmentTable.id),
  jobNumber: text("job_number"),
  jobType: text("job_type").notNull().default("repair"),
  title: text("title").notNull(),
  description: text("description"),
  priority: text("priority").notNull().default("medium"),
  status: text("status").notNull().default("open"),
  reportedBy: text("reported_by"),
  assignedTo: text("assigned_to"),
  openedAt: timestamp("opened_at", { withTimezone: true }).notNull().defaultNow(),
  estimatedCompletionDate: timestamp("estimated_completion_date", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  labourHours: integer("labour_hours"),
  labourCostPence: integer("labour_cost_pence"),
  partsCostPence: integer("parts_cost_pence"),
  partsUsed: text("parts_used"),
  rootCause: text("root_cause"),
  notes: text("notes"),
  customerId: integer("customer_id").references(() => farmCustomersTable.id),
  serviceInvoiceId: integer("service_invoice_id").references(() => serviceInvoicesTable.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const workshopPatTestsTable = pgTable("workshop_pat_tests", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  itemName: text("item_name").notNull(),
  equipmentId: integer("equipment_id").references(() => equipmentTable.id),
  location: text("location"),
  buildingId: integer("building_id").references(() => farmLocationsTable.id, { onDelete: "set null" }),
  subLocation: text("sub_location"),
  testDate: timestamp("test_date", { withTimezone: true }),
  testerName: text("tester_name"),
  testerCompany: text("tester_company"),
  certificateNumber: text("certificate_number"),
  result: text("result").notNull().default("pass"),
  nextDueDate: timestamp("next_due_date", { withTimezone: true }),
  notes: text("notes"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopPatEquipmentTable = pgTable("workshop_pat_equipment", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  assetNumber: text("asset_number"),
  itemName: text("item_name").notNull(),
  description: text("description"),
  make: text("make"),
  model: text("model"),
  serialNumber: text("serial_number"),
  buildingId: integer("building_id").references(() => farmLocationsTable.id, { onDelete: "set null" }),
  subLocation: text("sub_location"),
  location: text("location"),
  lastTestDate: timestamp("last_test_date", { withTimezone: true }),
  testerName: text("tester_name"),
  testerCompany: text("tester_company"),
  nextTestDue: timestamp("next_test_due", { withTimezone: true }),
  status: text("status").notNull().default("active"),
  disposalDate: timestamp("disposal_date", { withTimezone: true }),
  disposalReason: text("disposal_reason"),
  disposalNotes: text("disposal_notes"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopPatTestRecordsTable = pgTable("workshop_pat_test_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  equipmentId: integer("equipment_id").notNull().references(() => workshopPatEquipmentTable.id, { onDelete: "cascade" }),
  testDate: timestamp("test_date", { withTimezone: true }).notNull(),
  testerName: text("tester_name"),
  testerCompany: text("tester_company"),
  certificateNumber: text("certificate_number"),
  result: text("result").notNull().default("pass"),
  nextDueDate: timestamp("next_due_date", { withTimezone: true }),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopFireExtinguishersTable = pgTable("workshop_fire_extinguishers", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  location: text("location").notNull(),
  buildingId: integer("building_id").references(() => farmLocationsTable.id, { onDelete: "set null" }),
  subLocation: text("sub_location"),
  type: text("type").notNull(),
  capacityKg: text("capacity_kg"),
  serialNumber: text("serial_number"),
  lastServiceDate: timestamp("last_service_date", { withTimezone: true }),
  engineerName: text("engineer_name"),
  engineerCompany: text("engineer_company"),
  nextServiceDue: timestamp("next_service_due", { withTimezone: true }),
  notes: text("notes"),
  status: text("status").notNull().default("active"),
  disposalDate: timestamp("disposal_date", { withTimezone: true }),
  disposalReason: text("disposal_reason"),
  disposalNotes: text("disposal_notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopFireExtinguisherServicesTable = pgTable("workshop_fire_extinguisher_services", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  extinguisherId: integer("extinguisher_id").notNull().references(() => workshopFireExtinguishersTable.id, { onDelete: "cascade" }),
  serviceDate: timestamp("service_date", { withTimezone: true }).notNull(),
  serviceType: text("service_type").notNull().default("annual_check"),
  engineerName: text("engineer_name"),
  engineerCompany: text("engineer_company"),
  certificateNumber: text("certificate_number"),
  result: text("result").notNull().default("pass"),
  nextServiceDue: timestamp("next_service_due", { withTimezone: true }),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const grainStorageBinsTable = pgTable("grain_storage_bins", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  binName: text("bin_name").notNull(),
  binType: text("bin_type").notNull(),
  capacityTonnes: numeric("capacity_tonnes", { precision: 8, scale: 1 }),
  dryingSystem: text("drying_system"),
  aerationSystem: boolean("aeration_system").default(false),
  temperatureMonitoring: boolean("temperature_monitoring").default(false),
  sensorCount: integer("sensor_count"),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const grainQualityTestsTable = pgTable("grain_quality_tests", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  locationId: integer("location_id").references(() => storageLocationsTable.id),
  binId: integer("bin_id").references(() => grainStorageBinsTable.id),
  testDate: date("test_date").notNull(),
  cropType: text("crop_type").notNull(),
  variety: text("variety"),
  harvestYear: integer("harvest_year"),
  moisturePercent: numeric("moisture_percent", { precision: 5, scale: 2 }),
  specificWeightKgHl: numeric("specific_weight_kg_hl", { precision: 5, scale: 1 }),
  proteinPercent: numeric("protein_percent", { precision: 5, scale: 2 }),
  hagbergFallingNumber: integer("hagberg_falling_number"),
  screeningsPercent: numeric("screenings_percent", { precision: 5, scale: 2 }),
  mycotoxinDonPpb: numeric("mycotoxin_don_ppb", { precision: 8, scale: 1 }),
  mycotoxinZonPpb: numeric("mycotoxin_zon_ppb", { precision: 8, scale: 1 }),
  pestResidueTest: boolean("pest_residue_test").default(false),
  pestResidueResult: text("pest_residue_result"),
  testingLab: text("testing_lab"),
  labSupplierId: integer("lab_supplier_id").references(() => suppliersTable.id),
  certificateReference: text("certificate_reference"),
  overallGrade: text("overall_grade"),
  customer: text("customer"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const grainTemperatureLogsTable = pgTable("grain_temperature_logs", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  locationId: integer("location_id").references(() => storageLocationsTable.id),
  binId: integer("bin_id").references(() => grainStorageBinsTable.id),
  logDate: date("log_date").notNull(),
  logTime: text("log_time"),
  temperatureC: numeric("temperature_c", { precision: 5, scale: 1 }).notNull(),
  sensorPosition: text("sensor_position"),
  moisturePercent: numeric("moisture_percent", { precision: 5, scale: 2 }),
  aerationRunning: boolean("aeration_running").default(false),
  dryingRunning: boolean("drying_running").default(false),
  recordedBy: text("recorded_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopPartDocumentsTable = pgTable("workshop_part_documents", {
  id: serial("id").primaryKey(),
  stockItemId: integer("stock_item_id").notNull().references(() => stockItemsTable.id, { onDelete: "cascade" }),
  filename: text("filename").notNull(),
  storageKey: text("storage_key").notNull(),
  mimeType: text("mime_type"),
  fileSizeBytes: integer("file_size_bytes"),
  uploadedBy: text("uploaded_by"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopJobDocumentsTable = pgTable("workshop_job_documents", {
  id: serial("id").primaryKey(),
  jobId: integer("job_id").notNull().references(() => workshopJobsTable.id, { onDelete: "cascade" }),
  filename: text("filename").notNull(),
  storageKey: text("storage_key").notNull(),
  mimeType: text("mime_type"),
  fileSizeBytes: integer("file_size_bytes"),
  uploadedBy: text("uploaded_by"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopGoodsReturnsTable = pgTable("workshop_goods_returns", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  returnRef: text("return_ref").notNull(),
  supplierRtnNumber: text("supplier_rtn_number"),
  stockItemId: integer("stock_item_id").references(() => stockItemsTable.id),
  stockItemName: text("stock_item_name"),
  supplierId: integer("supplier_id").references(() => suppliersTable.id),
  quantity: numeric("quantity").notNull(),
  unit: text("unit"),
  unitCostPence: integer("unit_cost_pence"),
  returnReasonCode: text("return_reason_code").notNull().default("faulty"),
  returnReason: text("return_reason"),
  status: text("status").notNull().default("raised"),
  raisedBy: text("raised_by"),
  raisedAt: timestamp("raised_at", { withTimezone: true }).notNull().defaultNow(),
  dispatchedAt: timestamp("dispatched_at", { withTimezone: true }),
  creditAmountPence: integer("credit_amount_pence"),
  creditReceivedAt: timestamp("credit_received_at", { withTimezone: true }),
  originalDeliveryRef: text("original_delivery_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const workshopStocktakeSessionsTable = pgTable("workshop_stocktake_sessions", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  stocktakeDate: date("stocktake_date").notNull(),
  status: text("status").notNull().default("draft"),
  notes: text("notes"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  itemCount: integer("item_count").default(0),
  countedCount: integer("counted_count").default(0),
  totalVarianceValue: numeric("total_variance_value", { precision: 12, scale: 2 }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopStocktakeItemsTable = pgTable("workshop_stocktake_items", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").notNull().references(() => workshopStocktakeSessionsTable.id),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  stockItemId: integer("stock_item_id").references(() => stockItemsTable.id),
  partName: text("part_name").notNull(),
  partNumber: text("part_number"),
  unit: text("unit"),
  location: text("location"),
  expectedQty: numeric("expected_qty", { precision: 10, scale: 2 }).notNull(),
  countedQty: numeric("counted_qty", { precision: 10, scale: 2 }),
  variance: numeric("variance", { precision: 10, scale: 2 }),
  unitCostPence: integer("unit_cost_pence"),
  varianceValue: numeric("variance_value", { precision: 12, scale: 2 }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const equipmentDefectReportsTable = pgTable("equipment_defect_reports", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  defectRef: text("defect_ref"),
  equipmentId: integer("equipment_id").references(() => equipmentTable.id),
  equipmentName: text("equipment_name").notNull(),
  reportedDate: timestamp("reported_date", { withTimezone: true }).notNull(),
  reportedBy: text("reported_by"),
  defectDescription: text("defect_description").notNull(),
  severity: text("severity").notNull().default("minor"),
  status: text("status").notNull().default("reported"),
  actionTaken: text("action_taken"),
  resolvedDate: timestamp("resolved_date", { withTimezone: true }),
  resolvedBy: text("resolved_by"),
  notes: text("notes"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  mobileId: text("mobile_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopSettingsTable = pgTable("workshop_settings", {
  farmId: integer("farm_id").primaryKey().references(() => farmsTable.id, { onDelete: "cascade" }),
  labourRatePence: integer("labour_rate_pence").notNull().default(5000),
  labourChargeUnitMinutes: integer("labour_charge_unit_minutes").notNull().default(15),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const workshopLabourEntriesTable = pgTable("workshop_labour_entries", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id, { onDelete: "cascade" }),
  jobId: integer("job_id").notNull().references(() => workshopJobsTable.id, { onDelete: "cascade" }),
  entryDate: text("entry_date").notNull(),
  description: text("description"),
  chargeUnits: integer("charge_units").notNull().default(1),
  ratePence: integer("rate_pence").notNull(),
  costPence: integer("cost_pence").notNull(),
  performedBy: text("performed_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workshopRowsTable = pgTable("workshop_rows", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  description: text("description"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const workshopBaysTable = pgTable("workshop_bays", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id, { onDelete: "cascade" }),
  rowId: integer("row_id"),
  name: text("name").notNull(),
  description: text("description"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const workshopShelvesTable = pgTable("workshop_shelves", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id, { onDelete: "cascade" }),
  bayId: integer("bay_id").notNull().references(() => workshopBaysTable.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  qrToken: text("qr_token").notNull(),
  capacity: text("capacity"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
