import { pgTable, text, serial, integer, timestamp, boolean, numeric, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { storageLocationsTable } from "./fields-crops";

export const farmCustomersTable = pgTable("farm_customers", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  name: text("name").notNull(),
  contactName: text("contact_name"),
  contactPhone: text("contact_phone"),
  contactEmail: text("contact_email"),
  address: text("address"),
  holdingNumber: text("holding_number"),
  vatNumber: text("vat_number"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const serviceAgreementsTable = pgTable("service_agreements", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  customerId: integer("customer_id").notNull().references(() => farmCustomersTable.id),
  agreementType: text("agreement_type").notNull().default("grain_storage"),
  title: text("title").notNull(),
  referenceNumber: text("reference_number"),
  startDate: date("start_date"),
  endDate: date("end_date"),
  status: text("status").notNull().default("active"),
  areaHa: numeric("area_ha", { precision: 10, scale: 4 }),
  annualRentPence: integer("annual_rent_pence"),
  rentPerHaPence: integer("rent_per_ha_pence"),
  paymentFrequency: text("payment_frequency"),
  nextPaymentDate: date("next_payment_date"),
  storageLocationId: integer("storage_location_id").references(() => storageLocationsTable.id),
  maxTonnesContracted: numeric("max_tonnes_contracted", { precision: 10, scale: 2 }),
  storageRatePptWeek: numeric("storage_rate_ppt_week", { precision: 8, scale: 4 }),
  intakeChargePpt: numeric("intake_charge_ppt", { precision: 8, scale: 4 }),
  outloadingChargePpt: numeric("outloading_charge_ppt", { precision: 8, scale: 4 }),
  dryingChargePpt: numeric("drying_charge_ppt", { precision: 8, scale: 4 }),
  dayRatePence: integer("day_rate_pence"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const thirdPartyGrainIntakesTable = pgTable("third_party_grain_intakes", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  customerId: integer("customer_id").notNull().references(() => farmCustomersTable.id),
  agreementId: integer("agreement_id").references(() => serviceAgreementsTable.id),
  storageLocationId: integer("storage_location_id").references(() => storageLocationsTable.id),
  intakeDate: date("intake_date").notNull(),
  commodity: text("commodity").notNull(),
  variety: text("variety"),
  quantityTonnes: numeric("quantity_tonnes", { precision: 10, scale: 2 }).notNull(),
  moisturePercent: numeric("moisture_percent", { precision: 5, scale: 2 }),
  screeningsPercent: numeric("screenings_percent", { precision: 5, scale: 2 }),
  specificWeightKgHl: numeric("specific_weight_kg_hl", { precision: 5, scale: 2 }),
  grade: text("grade"),
  lotReference: text("lot_reference"),
  deliveryNoteRef: text("delivery_note_ref"),
  vehicleReg: text("vehicle_reg"),
  haulier: text("haulier"),
  bayOrBin: text("bay_or_bin"),
  status: text("status").notNull().default("in_store"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const thirdPartyGrainMovementsTable = pgTable("third_party_grain_movements", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  intakeId: integer("intake_id").notNull().references(() => thirdPartyGrainIntakesTable.id),
  movementDate: date("movement_date").notNull(),
  movementType: text("movement_type").notNull(),
  quantityTonnes: numeric("quantity_tonnes", { precision: 10, scale: 2 }).notNull(),
  destination: text("destination"),
  vehicleReg: text("vehicle_reg"),
  haulier: text("haulier"),
  deliveryNoteRef: text("delivery_note_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const serviceInvoicesTable = pgTable("service_invoices", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  customerId: integer("customer_id").notNull().references(() => farmCustomersTable.id),
  agreementId: integer("agreement_id").references(() => serviceAgreementsTable.id),
  invoiceNumber: text("invoice_number"),
  invoiceDate: date("invoice_date").notNull(),
  dueDate: date("due_date"),
  status: text("status").notNull().default("draft"),
  subtotalPence: integer("subtotal_pence").notNull().default(0),
  vatRatePercent: numeric("vat_rate_percent", { precision: 5, scale: 2 }).notNull().default("20"),
  vatPence: integer("vat_pence").notNull().default(0),
  totalPence: integer("total_pence").notNull().default(0),
  paymentDate: date("payment_date"),
  paymentMethod: text("payment_method"),
  paymentReference: text("payment_reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const serviceInvoiceLinesTable = pgTable("service_invoice_lines", {
  id: serial("id").primaryKey(),
  invoiceId: integer("invoice_id").notNull().references(() => serviceInvoicesTable.id),
  description: text("description").notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }),
  unit: text("unit"),
  unitPricePence: integer("unit_price_pence").notNull(),
  lineTotalPence: integer("line_total_pence").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
