import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { suppliersTable } from "./stock-suppliers";

export const horticultureBlocksTable = pgTable("horticulture_blocks", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  blockName: text("block_name").notNull(),
  blockCode: text("block_code"),
  areaHa: numeric("area_ha", { precision: 8, scale: 3 }),
  soilType: text("soil_type"),
  irrigationSystem: text("irrigation_system"),
  waterSource: text("water_source"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticultureCropsTable = pgTable("horticulture_crops", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  blockId: integer("block_id").references(() => horticultureBlocksTable.id),
  cropName: text("crop_name").notNull(),
  variety: text("variety"),
  sowingDate: date("sowing_date"),
  transplantingDate: date("transplanting_date"),
  expectedHarvestDate: date("expected_harvest_date"),
  seedSupplier: text("seed_supplier"),
  seedLotNumber: text("seed_lot_number"),
  seedTreated: boolean("seed_treated").default(false),
  seedTreatmentDetails: text("seed_treatment_details"),
  growingMethod: text("growing_method"),
  status: text("status").notNull().default("growing"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticultureWaterTestsTable = pgTable("horticulture_water_tests", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  testDate: date("test_date").notNull(),
  waterSource: text("water_source").notNull(),
  testingLab: text("testing_lab"),
  labSupplierId: integer("lab_supplier_id").references(() => suppliersTable.id),
  sampleReference: text("sample_reference"),
  ecoli: text("ecoli"),
  totalColiform: text("total_coliform"),
  salmonella: text("salmonella"),
  cryptosporidium: text("cryptosporidium"),
  ph: numeric("ph", { precision: 4, scale: 1 }),
  turbidity: numeric("turbidity", { precision: 8, scale: 2 }),
  nitratesMgL: numeric("nitrates_mg_l", { precision: 8, scale: 2 }),
  overallResult: text("overall_result").notNull(),
  correctiveAction: text("corrective_action"),
  nextTestDueDate: date("next_test_due_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticultureHarvestRecordsTable = pgTable("horticulture_harvest_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  cropId: integer("crop_id").references(() => horticultureCropsTable.id),
  harvestDate: date("harvest_date").notNull(),
  harvestBatchRef: text("harvest_batch_ref").notNull(),
  blockId: integer("block_id").references(() => horticultureBlocksTable.id),
  quantityKg: numeric("quantity_kg", { precision: 10, scale: 2 }).notNull(),
  gradeA: numeric("grade_a_kg", { precision: 10, scale: 2 }),
  gradeB: numeric("grade_b_kg", { precision: 10, scale: 2 }),
  waste: numeric("waste_kg", { precision: 10, scale: 2 }),
  harvestedBy: text("harvested_by"),
  supervisorName: text("supervisor_name"),
  weatherConditions: text("weather_conditions"),
  temperature: numeric("temperature", { precision: 5, scale: 1 }),
  preHarvestInterval: integer("pre_harvest_interval_days"),
  destination: text("destination"),
  customerReference: text("customer_reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticulturePackhouseRecordsTable = pgTable("horticulture_packhouse_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  harvestBatchRef: text("harvest_batch_ref").notNull(),
  packingDate: date("packing_date").notNull(),
  productName: text("product_name").notNull(),
  traceabilityCode: text("traceability_code").notNull(),
  quantityPackedKg: numeric("quantity_packed_kg", { precision: 10, scale: 2 }),
  packFormat: text("pack_format"),
  labelChecked: boolean("label_checked").default(false),
  metalDetectorCheck: boolean("metal_detector_check").default(false),
  temperatureAtPacking: numeric("temperature_at_packing", { precision: 5, scale: 1 }),
  coldStoreTemperature: numeric("cold_store_temperature", { precision: 5, scale: 1 }),
  dispatchDate: date("dispatch_date"),
  customerName: text("customer_name"),
  despatchNoteNumber: text("despatch_note_number"),
  allergenCheck: boolean("allergen_check").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const allergenManagementRecordsTable = pgTable("allergen_management_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  reviewDate: date("review_date").notNull(),
  reviewedBy: text("reviewed_by").notNull(),
  allergensOnSite: text("allergens_on_site").array(),
  crossContaminationRisk: text("cross_contamination_risk").notNull(),
  controlMeasures: text("control_measures"),
  staffTrainingDate: date("staff_training_date"),
  labellingVerified: boolean("labelling_verified").default(false),
  nextReviewDate: date("next_review_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
