import { pgTable, text, serial, integer, timestamp, numeric, boolean, date, jsonb } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { suppliersTable } from "./stock-suppliers";

export const horticultureBlocksTable = pgTable("horticulture_blocks", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  blockName: text("block_name").notNull(),
  blockCode: text("block_code"),
  areaHa: numeric("area_ha", { precision: 8, scale: 3 }),
  soilType: text("soil_type"),
  irrigationSystem: text("irrigation_system"),
  waterSource: text("water_source"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticultureCropsTable = pgTable("horticulture_crops", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  blockId: integer("block_id").references(() => horticultureBlocksTable.id),
  cropName: text("crop_name").notNull(),
  variety: text("variety"),
  sowingDate: date("sowing_date"),
  transplantingDate: date("transplanting_date"),
  expectedHarvestDate: date("expected_harvest_date"),
  seedSupplier: text("seed_supplier"),
  seedLotNumber: text("seed_lot_number"),
  seedTreated: boolean("seed_treated").default(false),
  seedTreatmentDetails: text("seed_treatment_details"),
  growingMethod: text("growing_method"),
  status: text("status").notNull().default("growing"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticultureWaterTestsTable = pgTable("horticulture_water_tests", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  testDate: date("test_date").notNull(),
  waterSource: text("water_source").notNull(),
  testingLab: text("testing_lab"),
  labSupplierId: integer("lab_supplier_id").references(() => suppliersTable.id),
  sampleReference: text("sample_reference"),
  ecoli: text("ecoli"),
  totalColiform: text("total_coliform"),
  salmonella: text("salmonella"),
  cryptosporidium: text("cryptosporidium"),
  ph: numeric("ph", { precision: 4, scale: 1 }),
  turbidity: numeric("turbidity", { precision: 8, scale: 2 }),
  nitratesMgL: numeric("nitrates_mg_l", { precision: 8, scale: 2 }),
  overallResult: text("overall_result").notNull(),
  correctiveAction: text("corrective_action"),
  nextTestDueDate: date("next_test_due_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticultureHarvestRecordsTable = pgTable("horticulture_harvest_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  cropId: integer("crop_id").references(() => horticultureCropsTable.id),
  harvestDate: date("harvest_date").notNull(),
  harvestBatchRef: text("harvest_batch_ref").notNull(),
  blockId: integer("block_id").references(() => horticultureBlocksTable.id),
  quantityKg: numeric("quantity_kg", { precision: 10, scale: 2 }).notNull(),
  gradeA: numeric("grade_a_kg", { precision: 10, scale: 2 }),
  gradeB: numeric("grade_b_kg", { precision: 10, scale: 2 }),
  waste: numeric("waste_kg", { precision: 10, scale: 2 }),
  harvestedBy: text("harvested_by"),
  supervisorName: text("supervisor_name"),
  weatherConditions: text("weather_conditions"),
  temperature: numeric("temperature", { precision: 5, scale: 1 }),
  preHarvestInterval: integer("pre_harvest_interval_days"),
  destination: text("destination"),
  customerReference: text("customer_reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const freshProduceIntakeTable = pgTable("fresh_produce_intake", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  harvestRecordId: integer("harvest_record_id").references(() => horticultureHarvestRecordsTable.id),
  intakeDate: date("intake_date").notNull(),
  harvestBatchRef: text("harvest_batch_ref").notNull(),
  productName: text("product_name").notNull(),
  quantityKg: numeric("quantity_kg", { precision: 10, scale: 2 }),
  conditionOnArrival: text("condition_on_arrival"),
  intakeTemperatureC: numeric("intake_temperature_c", { precision: 5, scale: 1 }),
  targetStorageTemperatureC: numeric("target_storage_temperature_c", { precision: 5, scale: 1 }),
  preCoolingStartTime: text("pre_cooling_start_time"),
  preCoolingEndTime: text("pre_cooling_end_time"),
  achievedTemperatureC: numeric("achieved_temperature_c", { precision: 5, scale: 1 }),
  storageLocation: text("storage_location"),
  receivedBy: text("received_by"),
  foreignBodyCheck: boolean("foreign_body_check").default(false),
  pestDamageCheck: boolean("pest_damage_check").default(false),
  accepted: boolean("accepted").default(true),
  rejectionReason: text("rejection_reason"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const horticulturePackhouseRecordsTable = pgTable("horticulture_packhouse_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  harvestRecordId: integer("harvest_record_id").references(() => horticultureHarvestRecordsTable.id),
  intakeRecordId: integer("intake_record_id").references(() => freshProduceIntakeTable.id),
  harvestBatchRef: text("harvest_batch_ref").notNull(),
  packingDate: date("packing_date").notNull(),
  productName: text("product_name").notNull(),
  traceabilityCode: text("traceability_code").notNull(),
  quantityPackedKg: numeric("quantity_packed_kg", { precision: 10, scale: 2 }),
  packFormat: text("pack_format"),
  labelChecked: boolean("label_checked").default(false),
  metalDetectorCheck: boolean("metal_detector_check").default(false),
  temperatureAtPacking: numeric("temperature_at_packing", { precision: 5, scale: 1 }),
  coldStoreTemperature: numeric("cold_store_temperature", { precision: 5, scale: 1 }),
  dispatchDate: date("dispatch_date"),
  customerName: text("customer_name"),
  despatchNoteNumber: text("despatch_note_number"),
  allergenCheck: boolean("allergen_check").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const allergenManagementRecordsTable = pgTable("allergen_management_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  reviewDate: date("review_date").notNull(),
  reviewedBy: text("reviewed_by").notNull(),
  allergensOnSite: text("allergens_on_site").array(),
  crossContaminationRisk: text("cross_contamination_risk").notNull(),
  controlMeasures: text("control_measures"),
  staffTrainingDate: date("staff_training_date"),
  labellingVerified: boolean("labelling_verified").default(false),
  nextReviewDate: date("next_review_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Block Boundaries ──────────────────────────────────────────────────────
export const horticultureBlockBoundariesTable = pgTable("horticulture_block_boundaries", {
  id: serial("id").primaryKey(),
  blockId: integer("block_id").notNull().references(() => horticultureBlocksTable.id, { onDelete: "cascade" }),
  polygonPoints: jsonb("polygon_points").notNull(),
  capturedAt: timestamp("captured_at", { withTimezone: true }).notNull().defaultNow(),
  capturedBy: text("captured_by"),
});

// ─── Organic Fresh Produce ─────────────────────────────────────────────────
export const organicFreshProduceBlockStatusTable = pgTable("organic_fresh_produce_block_status", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  blockId: integer("block_id").references(() => horticultureBlocksTable.id),
  blockName: text("block_name").notNull(),
  certifyingBody: text("certifying_body"),
  conversionStartDate: date("conversion_start_date"),
  fullyOrganicDate: date("fully_organic_date"),
  status: text("status").notNull().default("in-conversion"),
  landUseBeforeConversion: text("land_use_before_conversion"),
  previousSyntheticInputs: text("previous_synthetic_inputs"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const organicFreshProduceInputLogTable = pgTable("organic_fresh_produce_input_log", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  blockId: integer("block_id").references(() => horticultureBlocksTable.id),
  applicationDate: date("application_date").notNull(),
  inputName: text("input_name").notNull(),
  inputType: text("input_type"),
  approvedByBody: text("approved_by_body"),
  isApproved: boolean("is_approved").default(true),
  quantityApplied: numeric("quantity_applied", { precision: 10, scale: 3 }),
  quantityUnit: text("quantity_unit"),
  purposeOfUse: text("purpose_of_use"),
  appliedBy: text("applied_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const organicFreshProduceCertificatesTable = pgTable("organic_fresh_produce_certificates", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  certifyingBody: text("certifying_body").notNull(),
  certificateNumber: text("certificate_number").notNull(),
  issueDate: date("issue_date").notNull(),
  expiryDate: date("expiry_date"),
  scope: text("scope"),
  productsIncluded: text("products_included"),
  annualRenewalDue: date("annual_renewal_due"),
  status: text("status").notNull().default("active"),
  documentRef: text("document_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const organicFreshProduceBuyerDeclarationsTable = pgTable("organic_fresh_produce_buyer_declarations", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  declarationDate: date("declaration_date").notNull(),
  buyerName: text("buyer_name").notNull(),
  buyerAddress: text("buyer_address"),
  productDescription: text("product_description").notNull(),
  quantityKg: numeric("quantity_kg", { precision: 10, scale: 2 }),
  certifyingBody: text("certifying_body"),
  certificateNumber: text("certificate_number"),
  declaredBy: text("declared_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
