import { pgTable, text, serial, integer, timestamp, numeric, boolean, jsonb, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

export const herdFlockRegisterTable = pgTable("herd_flock_register", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  name: text("name").notNull(),
  type: text("type").notNull(),
  breed: text("breed"),
  herdNumber: text("herd_number"),
  registrationDocumentUrl: text("registration_document_url"),
  registrationDocumentName: text("registration_document_name"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const livestockAnimalsTable = pgTable("livestock_animals", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  tagNumber: text("tag_number"),
  earTagNumber: text("ear_tag_number"),
  eidNumber: text("eid_number"),
  species: text("species").notNull(),
  breed: text("breed"),
  sex: text("sex"),
  dateOfBirth: timestamp("date_of_birth", { withTimezone: true }),
  damId: integer("dam_id"),
  sireId: integer("sire_id"),
  acquisitionDate: timestamp("acquisition_date", { withTimezone: true }),
  acquisitionSource: text("acquisition_source"),
  animalCode: text("animal_code"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const animalDocumentsTable = pgTable("animal_documents", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  animalId: integer("animal_id").notNull().references(() => livestockAnimalsTable.id),
  title: text("title").notNull(),
  documentType: text("document_type").notNull().default("other"),
  documentUrl: text("document_url").notNull(),
  documentName: text("document_name"),
  notes: text("notes"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const livestockMovementsTable = pgTable("livestock_movements", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  movementType: text("movement_type").notNull(),
  movementDate: timestamp("movement_date", { withTimezone: true }).notNull(),
  fromLocation: text("from_location"),
  toLocation: text("to_location"),
  numberOfAnimals: integer("number_of_animals").default(1),
  licenceNumber: text("licence_number"),
  bcmsSubmissionRef: text("bcms_submission_ref"),
  legalNotificationSubmitted: boolean("legal_notification_submitted").notNull().default(false),
  legalNotificationDate: timestamp("legal_notification_date", { withTimezone: true }),
  species: text("species"),
  earTagNumbers: text("ear_tag_numbers"),
  transporterDetails: text("transporter_details"),
  reason: text("reason"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const livestockMedicineRecordsTable = pgTable("livestock_medicine_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  medicineRef: text("medicine_ref"),
  medicineName: text("medicine_name").notNull(),
  batchNumber: text("batch_number"),
  dosage: text("dosage"),
  administrationRoute: text("administration_route"),
  administeredBy: text("administered_by"),
  administeredDate: timestamp("administered_date", { withTimezone: true }).notNull(),
  withdrawalPeriodDays: integer("withdrawal_period_days"),
  withdrawalEndDate: timestamp("withdrawal_end_date", { withTimezone: true }),
  reason: text("reason"),
  vetName: text("vet_name"),
  treatmentScope: text("treatment_scope"),
  treatedAnimalTags: text("treated_animal_tags"),
  treatedAnimalCount: integer("treated_animal_count"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const livestockFeedRecordsTable = pgTable("livestock_feed_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  feedType: text("feed_type").notNull(),
  supplier: text("supplier"),
  batchNumber: text("batch_number"),
  quantityKg: numeric("quantity_kg", { precision: 10, scale: 2 }),
  feedDate: timestamp("feed_date", { withTimezone: true }).notNull(),
  notes: text("notes"),
  feedStockItemId: integer("feed_stock_item_id"),
  deliveryId: integer("delivery_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const livestockWaterRecordsTable = pgTable("livestock_water_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  waterSource: text("water_source").notNull(),
  testDate: timestamp("test_date", { withTimezone: true }),
  testResult: text("test_result"),
  testPass: boolean("test_pass"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const fallenStockContractorsTable = pgTable("fallen_stock_contractors", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  name: text("name").notNull(),
  approvalNumber: text("approval_number").notNull(),
  operatorType: text("operator_type").notNull().default("nfas-collector"),
  contactName: text("contact_name"),
  phone: text("phone"),
  email: text("email"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const livestockMortalityTable = pgTable("livestock_mortality", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  contractorId: integer("contractor_id").references(() => fallenStockContractorsTable.id),
  tagNumber: text("tag_number"),
  species: text("species").notNull(),
  breed: text("breed"),
  dateOfDeath: timestamp("date_of_death", { withTimezone: true }).notNull(),
  causeOfDeath: text("cause_of_death").notNull(),
  disposalMethod: text("disposal_method").notNull(),
  disposalOperator: text("disposal_operator"),
  disposalRef: text("disposal_ref"),
  veterinaryAttended: boolean("veterinary_attended").notNull().default(false),
  vetName: text("vet_name"),
  postMortemCarriedOut: boolean("post_mortem_carried_out").notNull().default(false),
  postMortemFindings: text("post_mortem_findings"),
  bcmsNotified: boolean("bcms_notified").notNull().default(false),
  bcmsNotificationRef: text("bcms_notification_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const vetHealthPlansTable = pgTable("vet_health_plans", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  planYear: integer("plan_year").notNull(),
  vetName: text("vet_name").notNull(),
  practiceName: text("practice_name"),
  practicePhone: text("practice_phone"),
  practiceAddress: text("practice_address"),
  planDate: timestamp("plan_date", { withTimezone: true }).notNull(),
  reviewDate: timestamp("review_date", { withTimezone: true }),
  healthPriorities: text("health_priorities"),
  vaccinationProtocol: text("vaccination_protocol"),
  biosecurityMeasures: text("biosecurity_measures"),
  wormingProtocol: text("worming_protocol"),
  flukeTreatment: text("fluke_treatment"),
  mastitisPrevention: text("mastitis_prevention"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const dairyMilkRecordsTable = pgTable("dairy_milk_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  recordDate: timestamp("record_date", { withTimezone: true }).notNull(),
  recordType: text("record_type").notNull().default("bulk-tank"),
  sessionType: text("session_type"),
  yieldLitres: numeric("yield_litres", { precision: 10, scale: 2 }),
  sccThousands: integer("scc_thousands"),
  tbcCfuMl: integer("tbc_cfu_ml"),
  fatPercent: numeric("fat_percent", { precision: 5, scale: 2 }),
  proteinPercent: numeric("protein_percent", { precision: 5, scale: 2 }),
  lactosePercent: numeric("lactose_percent", { precision: 5, scale: 2 }),
  milkTemperatureCelsius: numeric("milk_temperature_celsius", { precision: 5, scale: 2 }),
  antibioticResidueTestResult: text("antibiotic_residue_test_result"),
  collectorReference: text("collector_reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const dairyMastitisRecordsTable = pgTable("dairy_mastitis_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  earTagNumber: text("ear_tag_number"),
  onsetDate: timestamp("onset_date", { withTimezone: true }).notNull(),
  quartersAffected: text("quarters_affected"),
  clinicalGrade: text("clinical_grade"),
  bacterialCultureResult: text("bacterial_culture_result"),
  treatmentProduct: text("treatment_product"),
  treatmentStartDate: timestamp("treatment_start_date", { withTimezone: true }),
  treatmentDurationDays: integer("treatment_duration_days"),
  withdrawalEndDate: timestamp("withdrawal_end_date", { withTimezone: true }),
  outcome: text("outcome"),
  outcomeDate: timestamp("outcome_date", { withTimezone: true }),
  vetConsulted: boolean("vet_consulted").notNull().default(false),
  vetName: text("vet_name"),
  sccAtOnset: integer("scc_at_onset"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const dairyCalvingRecordsTable = pgTable("dairy_calving_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  cowAnimalId: integer("cow_animal_id").references(() => livestockAnimalsTable.id),
  cowEarTag: text("cow_ear_tag"),
  calvingDate: timestamp("calving_date", { withTimezone: true }).notNull(),
  calvingEaseScore: integer("calving_ease_score"),
  numberOfCalves: integer("number_of_calves").notNull().default(1),
  calfOutcome: text("calf_outcome"),
  calfSex: text("calf_sex"),
  calfEarTag: text("calf_ear_tag"),
  sireBreed: text("sire_breed"),
  calfBreed: text("calf_breed"),
  calfBirthWeightKg: numeric("calf_birth_weight_kg", { precision: 6, scale: 2 }),
  colostrumGivenWithin2Hours: boolean("colostrum_given_within_2_hours"),
  colostrumGivenWithin6Hours: boolean("colostrum_given_within_6_hours"),
  colostrumVolumeFirstFeedLitres: numeric("colostrum_volume_first_feed_litres", { precision: 5, scale: 2 }),
  colostrumQualityBrix: numeric("colostrum_quality_brix", { precision: 5, scale: 2 }),
  colostrumSource: text("colostrum_source"),
  cowComplications: text("cow_complications"),
  assistanceRequired: boolean("assistance_required").notNull().default(false),
  vetAttended: boolean("vet_attended").notNull().default(false),
  vetName: text("vet_name"),
  calfDisposition: text("calf_disposition"),
  bcmsPassportApplied: boolean("bcms_passport_applied").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const dairyBcsRecordsTable = pgTable("dairy_bcs_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  earTagNumber: text("ear_tag_number"),
  assessmentDate: timestamp("assessment_date", { withTimezone: true }).notNull(),
  lifeStage: text("life_stage"),
  bcsScore: numeric("bcs_score", { precision: 3, scale: 1 }),
  assessedBy: text("assessed_by"),
  targetScore: numeric("target_score", { precision: 3, scale: 1 }),
  actionRequired: boolean("action_required").notNull().default(false),
  actionTaken: text("action_taken"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const dairyMobilityScoringsTable = pgTable("dairy_mobility_scorings", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  assessmentDate: timestamp("assessment_date", { withTimezone: true }).notNull(),
  assessedBy: text("assessed_by"),
  totalCowsScored: integer("total_cows_scored").notNull(),
  score0Count: integer("score_0_count").notNull().default(0),
  score1Count: integer("score_1_count").notNull().default(0),
  score2Count: integer("score_2_count").notNull().default(0),
  score3Count: integer("score_3_count").notNull().default(0),
  lamenessPrevalencePercent: numeric("lameness_prevalence_percent", { precision: 5, scale: 2 }),
  actionTaken: text("action_taken"),
  nextAssessmentDue: timestamp("next_assessment_due", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const dairyBulkTankRecordsTable = pgTable("dairy_bulk_tank_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  recordDate: timestamp("record_date", { withTimezone: true }).notNull(),
  recordType: text("record_type").notNull(),
  tankTemperatureCelsius: numeric("tank_temperature_celsius", { precision: 5, scale: 2 }),
  tankCleaned: boolean("tank_cleaned"),
  cleaningProductUsed: text("cleaning_product_used"),
  cleaningProductBatch: text("cleaning_product_batch"),
  antibioticResidueTestRef: text("antibiotic_residue_test_ref"),
  antibioticResidueResult: text("antibiotic_residue_result"),
  tankerDriverName: text("tanker_driver_name"),
  collectionRef: text("collection_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const dairyDctRecordsTable = pgTable("dairy_dct_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  cowEarTag: text("cow_ear_tag"),
  dryOffDate: timestamp("dry_off_date", { withTimezone: true }).notNull(),
  protocol: text("protocol").notNull(),
  antibioticTubeProduct: text("antibiotic_tube_product"),
  antibioticTubeBatch: text("antibiotic_tube_batch"),
  antibioticTubeWithdrawalMilkDays: integer("antibiotic_tube_withdrawal_milk_days"),
  antibioticTubeWithdrawalMeatDays: integer("antibiotic_tube_withdrawal_meat_days"),
  teatSealantProduct: text("teat_sealant_product"),
  teatSealantBatch: text("teat_sealant_batch"),
  treatmentJustification: text("treatment_justification"),
  sccAtDryOff: integer("scc_at_dry_off"),
  mastitisEpisodes12Months: integer("mastitis_episodes_12_months"),
  administeredBy: text("administered_by"),
  vetAuthorisation: boolean("vet_authorisation").notNull().default(false),
  vetName: text("vet_name"),
  expectedCalvingDate: timestamp("expected_calving_date", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const strawInventoryTable = pgTable("straw_inventory", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  sireRegisterId: integer("sire_register_id"),
  sireName: text("sire_name").notNull(),
  sireBreed: text("sire_breed"),
  sireSpecies: text("sire_species").notNull().default("Cattle"),
  supplierName: text("supplier_name"),
  batchNumber: text("batch_number").notNull(),
  strawsReceived: integer("straws_received").notNull().default(0),
  storageLocation: text("storage_location"),
  deliveryDate: date("delivery_date"),
  unitCostPence: integer("unit_cost_pence"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const aiReproductionRecordsTable = pgTable("ai_reproduction_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  animalId: integer("animal_id"),
  earTag: text("ear_tag").notNull(),
  serviceDate: date("service_date").notNull(),
  serviceType: text("service_type").notNull(),
  sireRegisterId: integer("sire_register_id"),
  strawInventoryId: integer("straw_inventory_id"),
  bullOrSireName: text("bull_or_sire_name"),
  sireStuNumber: text("sire_stu_number"),
  sireBreed: text("sire_breed"),
  strawBatchNumber: text("straw_batch_number"),
  aiTechnicianName: text("ai_technician_name"),
  bullingObservedDate: date("bulling_observed_date"),
  expectedCalvingDate: date("expected_calving_date"),
  pregnancyDiagnosisDate: date("pregnancy_diagnosis_date"),
  pregnancyResult: text("pregnancy_result"),
  veterinarianName: text("veterinarian_name"),
  returnToServiceDate: date("return_to_service_date"),
  actualCalvingDate: date("actual_calving_date"),
  calvingOutcome: text("calving_outcome"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const vetPrescriptionRecordsTable = pgTable("vet_prescription_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  prescriptionDate: date("prescription_date").notNull(),
  vetName: text("vet_name").notNull(),
  vrcPracticeName: text("vrc_practice_name"),
  rcvsPracticeNumber: text("rcvs_practice_number"),
  productName: text("product_name").notNull(),
  activeIngredient: text("active_ingredient"),
  vmtNumber: text("vmt_number"),
  dosageAndFrequency: text("dosage_and_frequency").notNull(),
  routeOfAdministration: text("route_of_administration").notNull(),
  quantityAuthorised: text("quantity_authorised").notNull(),
  validityDays: integer("validity_days"),
  expiryDate: date("expiry_date"),
  targetSpecies: text("target_species").notNull(),
  indicationOrDiagnosis: text("indication_or_diagnosis").notNull(),
  cascadeJustification: text("cascade_justification"),
  isCascade: boolean("is_cascade").default(false),
  withdrawalPeriodMeat: integer("withdrawal_period_meat_days"),
  withdrawalPeriodMilk: integer("withdrawal_period_milk_days"),
  withdrawalPeriodEggs: integer("withdrawal_period_eggs_days"),
  dispensedQuantity: text("dispensed_quantity"),
  dispensedDate: date("dispensed_date"),
  treatmentScope: text("treatment_scope"),
  treatmentDate: date("treatment_date"),
  administeredBy: text("administered_by"),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  animalId: integer("animal_id").references(() => livestockAnimalsTable.id),
  treatedAnimalTags: text("treated_animal_tags"),
  treatedAnimalCount: integer("treated_animal_count"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const livestockDailyChecksTable = pgTable("livestock_daily_checks", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  checkRef: text("check_ref"),
  herdName: text("herd_name"),
  checkDate: timestamp("check_date", { withTimezone: true }).notNull(),
  checkedBy: text("checked_by"),
  overallCondition: text("overall_condition"),
  sickCount: integer("sick_count").default(0),
  mortalityCount: integer("mortality_count").default(0),
  feedOk: boolean("feed_ok").default(true),
  waterOk: boolean("water_ok").default(true),
  shelterOk: boolean("shelter_ok").default(true),
  actionTaken: text("action_taken"),
  status: text("status").notNull().default("open"),
  notes: text("notes"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  mobileId: text("mobile_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sireRegisterTable = pgTable("sire_register", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  name: text("name").notNull(),
  species: text("species").notNull(),
  breed: text("breed"),
  tagNumber: text("tag_number"),
  passportNumber: text("passport_number"),
  dateOfBirth: date("date_of_birth"),
  ownershipType: text("ownership_type").notNull().default("owned"),
  supplierName: text("supplier_name"),
  supplierContact: text("supplier_contact"),
  hireStartDate: date("hire_start_date"),
  hireEndDate: date("hire_end_date"),
  returnDate: date("return_date"),
  bvdStatus: text("bvd_status"),
  fertilityTestDate: date("fertility_test_date"),
  fertilityTestResult: text("fertility_test_result"),
  scrapieGenotype: text("scrapie_genotype"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const herdHealthEventsTable = pgTable("herd_health_events", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  herdId: integer("herd_id").references(() => herdFlockRegisterTable.id),
  eventDate: timestamp("event_date", { withTimezone: true }).notNull(),
  eventType: text("event_type").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  vetName: text("vet_name"),
  actionTaken: text("action_taken"),
  followUpRequired: boolean("follow_up_required").notNull().default(false),
  followUpDate: timestamp("follow_up_date", { withTimezone: true }),
  followUpCompleted: boolean("follow_up_completed").notNull().default(false),
  recordedBy: text("recorded_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
