import { pgTable, serial, integer, text, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

export const farmPlannerEventsTable = pgTable("farm_planner_events", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  title: text("title").notNull(),
  description: text("description"),
  eventDate: timestamp("event_date", { withTimezone: true }).notNull(),
  endDate: timestamp("end_date", { withTimezone: true }),
  colour: text("colour").notNull().default("slate"),
  estimatedDurationHours: numeric("estimated_duration_hours", { precision: 5, scale: 2 }),
  startTime: text("start_time"),
  endTime: text("end_time"),
  reqTractors: integer("req_tractors").notNull().default(0),
  reqImplements: integer("req_implements").notNull().default(0),
  reqVehicles: integer("req_vehicles").notNull().default(0),
  reqSprayers: integer("req_sprayers").notNull().default(0),
  reqTrailers: integer("req_trailers").notNull().default(0),
  reqStaff: integer("req_staff").notNull().default(0),
  reqOther: integer("req_other").notNull().default(0),
  reqOtherNotes: text("req_other_notes"),
  reqMaterials: text("req_materials"),
  reqCommitted: boolean("req_committed").notNull().default(false),
  reqCommittedBy: text("req_committed_by"),
  reqCommittedAt: timestamp("req_committed_at", { withTimezone: true }),
  // Actuals (Plan vs Actual / As-Built)
  actualDate: date("actual_date"),
  actualTractors: integer("actual_tractors").notNull().default(0),
  actualImplements: integer("actual_implements").notNull().default(0),
  actualVehicles: integer("actual_vehicles").notNull().default(0),
  actualSprayers: integer("actual_sprayers").notNull().default(0),
  actualTrailers: integer("actual_trailers").notNull().default(0),
  actualStaff: integer("actual_staff").notNull().default(0),
  actualMaterials: text("actual_materials"),
  actualNotes: text("actual_notes"),
  actualStatus: text("actual_status"),
  actualCompletedAt: timestamp("actual_completed_at", { withTimezone: true }),
  actualCompletedBy: text("actual_completed_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
