import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

export const poultryHousesTable = pgTable("poultry_houses", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  houseName: text("house_name").notNull(),
  houseType: text("house_type").notNull(),
  species: text("species").notNull(),
  productionSystem: text("production_system").notNull(),
  approvedCapacity: integer("approved_capacity").notNull(),
  lengthM: numeric("length_m", { precision: 6, scale: 1 }),
  widthM: numeric("width_m", { precision: 6, scale: 1 }),
  ventilationType: text("ventilation_type"),
  waterSystem: text("water_system"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const poultryFlocksTable = pgTable("poultry_flocks", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  houseId: integer("house_id").references(() => poultryHousesTable.id),
  flockNumber: text("flock_number").notNull(),
  species: text("species").notNull(),
  breed: text("breed"),
  productionSystem: text("production_system").notNull(),
  placementDate: date("placement_date").notNull(),
  placementCount: integer("placement_count").notNull(),
  hatcheryName: text("hatchery_name"),
  hatcheryApprovalNumber: text("hatchery_approval_number"),
  status: text("status").notNull().default("active"),
  depletionDate: date("depletion_date"),
  depletionCount: integer("depletion_count"),
  depletionReason: text("depletion_reason"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const poultryDailyMortalityTable = pgTable("poultry_daily_mortality", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  flockId: integer("flock_id").notNull().references(() => poultryFlocksTable.id),
  recordDate: date("record_date").notNull(),
  mortalityCount: integer("mortality_count").notNull().default(0),
  culledCount: integer("culled_count").notNull().default(0),
  runningTotalMortality: integer("running_total_mortality"),
  mortalityPercentage: numeric("mortality_percentage", { precision: 5, scale: 2 }),
  mainCause: text("main_cause"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const poultryTreatmentsTable = pgTable("poultry_treatments", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  flockId: integer("flock_id").notNull().references(() => poultryFlocksTable.id),
  treatmentDate: date("treatment_date").notNull(),
  productName: text("product_name").notNull(),
  activeIngredient: text("active_ingredient"),
  condition: text("condition").notNull(),
  routeOfAdministration: text("route_of_administration").notNull(),
  doseRate: text("dose_rate"),
  durationDays: integer("duration_days"),
  batchNumber: text("batch_number"),
  expiryDate: date("expiry_date"),
  prescribedBy: text("prescribed_by"),
  withdrawalPeriodDays: integer("withdrawal_period_days"),
  withdrawalClearDate: date("withdrawal_clear_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const poultryHouseCleanoutsTable = pgTable("poultry_house_cleanouts", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  houseId: integer("house_id").notNull().references(() => poultryHousesTable.id),
  flockId: integer("flock_id").references(() => poultryFlocksTable.id),
  cleanoutStartDate: date("cleanout_start_date").notNull(),
  cleanoutEndDate: date("cleanout_end_date"),
  litterRemovalDate: date("litter_removal_date"),
  disinfectantUsed: text("disinfectant_used"),
  disinfectantSupplier: text("disinfectant_supplier"),
  disinfectantApprovalNumber: text("disinfectant_approval_number"),
  applicationMethod: text("application_method"),
  contactTimeMins: integer("contact_time_mins"),
  swabsTaken: boolean("swabs_taken").default(false),
  swabResults: text("swab_results"),
  standingTimeDays: integer("standing_time_days"),
  completedBy: text("completed_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const poultryEnvironmentalLogsTable = pgTable("poultry_environmental_logs", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  flockId: integer("flock_id").notNull().references(() => poultryFlocksTable.id),
  logDate: date("log_date").notNull(),
  logTime: text("log_time"),
  temperatureMin: numeric("temperature_min", { precision: 5, scale: 1 }),
  temperatureMax: numeric("temperature_max", { precision: 5, scale: 1 }),
  humidity: numeric("humidity", { precision: 5, scale: 1 }),
  co2Ppm: integer("co2_ppm"),
  ammoniaPpm: numeric("ammonia_ppm", { precision: 5, scale: 1 }),
  ventilationRate: text("ventilation_rate"),
  lightingHours: numeric("lighting_hours", { precision: 4, scale: 1 }),
  stockingDensity: numeric("stocking_density", { precision: 6, scale: 2 }),
  alarmActivated: boolean("alarm_activated").default(false),
  alarmDetails: text("alarm_details"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const poultryFciDocumentsTable = pgTable("poultry_fci_documents", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  flockId: integer("flock_id").notNull().references(() => poultryFlocksTable.id),
  documentDate: date("document_date").notNull(),
  catchingDate: date("catching_date"),
  destinationAbattoir: text("destination_abattoir"),
  numberOfBirds: integer("number_of_birds").notNull(),
  catchingContractor: text("catching_contractor"),
  anyDiseaseOrCondition: boolean("any_disease_or_condition").default(false),
  diseaseDetails: text("disease_details"),
  medicationsLast7Days: boolean("medications_last_7_days").default(false),
  medicationDetails: text("medication_details"),
  withdrawalPeriodClear: boolean("withdrawal_period_clear").default(true),
  lastFeedWithdrawalHours: integer("last_feed_withdrawal_hours"),
  signedByFarmer: boolean("signed_by_farmer").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
