import { pgTable, text, serial, integer, timestamp, boolean } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { suppliersTable } from "./stock-suppliers";
import { fieldsTable } from "./fields-crops";
import { farmInsuranceTable } from "./insurance";

export const flyTippingIncidentsTable = pgTable("fly_tipping_incidents", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  discoveredAt: text("discovered_at").notNull(),
  locationDescription: text("location_description").notNull(),
  latitude: text("latitude"),
  longitude: text("longitude"),
  wasteTypes: text("waste_types"),
  estimatedQuantity: text("estimated_quantity"),
  isHazardous: boolean("is_hazardous").notNull().default(false),
  accessPoint: text("access_point"),
  policeReported: boolean("police_reported").notNull().default(false),
  policeRefNumber: text("police_ref_number"),
  councilReported: boolean("council_reported").notNull().default(false),
  councilRefNumber: text("council_ref_number"),
  eaReported: boolean("ea_reported").notNull().default(false),
  eaRefNumber: text("ea_ref_number"),
  clearanceStatus: text("clearance_status").notNull().default("pending"),
  clearanceContractor: text("clearance_contractor"),
  clearanceDate: text("clearance_date"),
  wasteTransferNoteRef: text("waste_transfer_note_ref"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const flyTippingPhotosTable = pgTable("fly_tipping_photos", {
  id: serial("id").primaryKey(),
  incidentId: integer("incident_id").notNull().references(() => flyTippingIncidentsTable.id, { onDelete: "cascade" }),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const riskAssessmentsTable = pgTable("risk_assessments", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  title: text("title").notNull(),
  area: text("area"),
  hazardDescription: text("hazard_description").notNull(),
  riskLevel: text("risk_level"),
  controlMeasures: text("control_measures"),
  assessedBy: text("assessed_by"),
  assessmentDate: timestamp("assessment_date", { withTimezone: true }).notNull(),
  reviewDate: timestamp("review_date", { withTimezone: true }),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const coshhRecordsTable = pgTable("coshh_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  substanceName: text("substance_name").notNull(),
  manufacturer: text("manufacturer"),
  hazardClassification: text("hazard_classification"),
  usageArea: text("usage_area"),
  storageLocation: text("storage_location"),
  controlMeasures: text("control_measures"),
  ppe: text("ppe"),
  emergencyProcedures: text("emergency_procedures"),
  assessedBy: text("assessed_by"),
  assessmentDate: timestamp("assessment_date", { withTimezone: true }).notNull(),
  reviewDate: timestamp("review_date", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const wasteDisposalRecordsTable = pgTable("waste_disposal_records", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  wasteType: text("waste_type").notNull(),
  quantity: text("quantity"),
  disposalMethod: text("disposal_method").notNull(),
  disposalDate: timestamp("disposal_date", { withTimezone: true }).notNull(),
  carrierId: integer("carrier_id").references(() => suppliersTable.id),
  carrierName: text("carrier_name"),
  carrierLicence: text("carrier_licence"),
  carrierRegistrationType: text("carrier_registration_type"),
  ewcCode: text("ewc_code"),
  destinationSite: text("destination_site"),
  wasteTransferNote: text("waste_transfer_note"),
  receiptPhotoPath: text("receipt_photo_path"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Accident Book ────────────────────────────────────────────────────────────
export const accidentBookTable = pgTable("accident_book", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  incidentDate: text("incident_date").notNull(),
  incidentTime: text("incident_time"),
  incidentLocation: text("incident_location").notNull(),
  personName: text("person_name").notNull(),
  personType: text("person_type").notNull().default("employee"),
  jobTitle: text("job_title"),
  natureOfIncident: text("nature_of_incident").notNull(),
  natureOfInjury: text("nature_of_injury"),
  bodyPartAffected: text("body_part_affected"),
  firstAidGiven: boolean("first_aid_given").notNull().default(false),
  firstAidDetails: text("first_aid_details"),
  firstAiderName: text("first_aider_name"),
  hospitalAttended: boolean("hospital_attended").notNull().default(false),
  hospitalName: text("hospital_name"),
  timeLostDays: text("time_lost_days"),
  riddorReportable: boolean("riddor_reportable").notNull().default(false),
  riddorCategory: text("riddor_category"),
  riddorReference: text("riddor_reference"),
  riddorReportedDate: text("riddor_reported_date"),
  witnesses: text("witnesses"),
  correctiveAction: text("corrective_action"),
  signedOffBy: text("signed_off_by"),
  signOffDate: text("sign_off_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const unauthorizedEncampmentsTable = pgTable("unauthorized_encampments", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  discoveredAt: text("discovered_at").notNull(),
  locationDescription: text("location_description").notNull(),
  fieldId: integer("field_id").references(() => fieldsTable.id),
  fieldParcel: text("field_parcel"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  entryPoint: text("entry_point"),
  vehicleCount: integer("vehicle_count"),
  personCount: integer("person_count"),
  caravanCount: integer("caravan_count"),
  vehicleDescriptions: text("vehicle_descriptions"),
  landDamageDescription: text("land_damage_description"),
  cropsAffected: boolean("crops_affected").notNull().default(false),
  estimatedDamage: text("estimated_damage"),
  policeNotified: boolean("police_notified").notNull().default(false),
  policeRefNumber: text("police_ref_number"),
  policeAction: text("police_action"),
  councilNotified: boolean("council_notified").notNull().default(false),
  councilRefNumber: text("council_ref_number"),
  legalActionTaken: boolean("legal_action_taken").notNull().default(false),
  legalActionDetails: text("legal_action_details"),
  solicitorInstructed: boolean("solicitor_instructed").notNull().default(false),
  courtOrderObtained: boolean("court_order_obtained").notNull().default(false),
  courtOrderRef: text("court_order_ref"),
  vacatedAt: text("vacated_at"),
  landConditionAfter: text("land_condition_after"),
  insuranceClaimMade: boolean("insurance_claim_made").notNull().default(false),
  insurancePolicyId: integer("insurance_policy_id").references(() => farmInsuranceTable.id),
  insuranceClaimRef: text("insurance_claim_ref"),
  remediationRequired: boolean("remediation_required").notNull().default(false),
  remediationNotes: text("remediation_notes"),
  remediationCost: text("remediation_cost"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const encampmentPhotosTable = pgTable("encampment_photos", {
  id: serial("id").primaryKey(),
  incidentId: integer("incident_id").notNull().references(() => unauthorizedEncampmentsTable.id, { onDelete: "cascade" }),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const accidentBookPhotosTable = pgTable("accident_book_photos", {
  id: serial("id").primaryKey(),
  recordId: integer("record_id").notNull().references(() => accidentBookTable.id, { onDelete: "cascade" }),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});
