import { pgTable, text, serial, integer, timestamp, numeric, boolean, date } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";

// ─── Livestock Settlement Notes (abattoir kill sheets) ───────────────────────
export const livestockSettlementNotesTable = pgTable("livestock_settlement_notes", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  killDate: date("kill_date").notNull(),
  abattoirName: text("abattoir_name").notNull(),
  abattoirRef: text("abattoir_ref"),
  species: text("species").notNull(),
  numberOfHead: integer("number_of_head").notNull(),
  averageCarcassWeightKg: numeric("average_carcass_weight_kg", { precision: 7, scale: 2 }),
  totalCarcassWeightKg: numeric("total_carcass_weight_kg", { precision: 8, scale: 2 }),
  killingOutPercentage: numeric("killing_out_percentage", { precision: 5, scale: 2 }),
  dominantGrade: text("dominant_grade"),
  gradeBreakdown: text("grade_breakdown"),
  averagePricePerKgGbp: numeric("average_price_per_kg_gbp", { precision: 8, scale: 4 }),
  totalValueGbp: numeric("total_value_gbp", { precision: 10, scale: 2 }),
  levyDeductionGbp: numeric("levy_deduction_gbp", { precision: 8, scale: 2 }),
  transportCostGbp: numeric("transport_cost_gbp", { precision: 8, scale: 2 }),
  otherDeductionsGbp: numeric("other_deductions_gbp", { precision: 8, scale: 2 }),
  netPaymentGbp: numeric("net_payment_gbp", { precision: 10, scale: 2 }),
  settlementDate: date("settlement_date"),
  paymentReceived: boolean("payment_received").notNull().default(false),
  paymentReceivedDate: date("payment_received_date"),
  linkedMovementRef: text("linked_movement_ref"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Grain Settlement Notes ───────────────────────────────────────────────────
export const grainSettlementNotesTable = pgTable("grain_settlement_notes", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  settlementDate: date("settlement_date").notNull(),
  merchantName: text("merchant_name").notNull(),
  contractRef: text("contract_ref"),
  commodity: text("commodity").notNull(),
  quantityTonnes: numeric("quantity_tonnes", { precision: 8, scale: 3 }).notNull(),
  pricePerTonneGbp: numeric("price_per_tonne_gbp", { precision: 8, scale: 2 }),
  totalValueGbp: numeric("total_value_gbp", { precision: 10, scale: 2 }),
  premiumOrDiscountGbp: numeric("premium_or_discount_gbp", { precision: 8, scale: 2 }),
  premiumOrDiscountReason: text("premium_or_discount_reason"),
  levyDeductionGbp: numeric("levy_deduction_gbp", { precision: 8, scale: 2 }),
  storageCostGbp: numeric("storage_cost_gbp", { precision: 8, scale: 2 }),
  otherDeductionsGbp: numeric("other_deductions_gbp", { precision: 8, scale: 2 }),
  netPaymentGbp: numeric("net_payment_gbp", { precision: 10, scale: 2 }),
  paymentDueDate: date("payment_due_date"),
  paymentReceived: boolean("payment_received").notNull().default(false),
  paymentReceivedDate: date("payment_received_date"),
  linkedHaulageRef: text("linked_haulage_ref"),
  qualitySpec: text("quality_spec"),
  documentPath: text("document_path"),
  documentName: text("document_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
