import { pgTable, text, serial, integer, timestamp, numeric, boolean } from "drizzle-orm/pg-core";
import { farmsTable } from "./core";
import { fieldsTable } from "./fields-crops";
import { equipmentTable } from "./equipment";

export const weatherStationsTable = pgTable("weather_stations", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  name: text("name").notNull(),
  stationType: text("station_type").notNull(),
  locationType: text("location_type"),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  linkedFieldId: integer("linked_field_id").references(() => fieldsTable.id),
  manufacturer: text("manufacturer"),
  model: text("model"),
  serialNumber: text("serial_number"),
  installDate: timestamp("install_date", { withTimezone: true }),
  isActive: boolean("is_active").notNull().default(true),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const weatherReadingsTable = pgTable("weather_readings", {
  id: serial("id").primaryKey(),
  stationId: integer("station_id").references(() => weatherStationsTable.id),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  fieldId: integer("field_id").references(() => fieldsTable.id),
  linkedSprayApplicationId: integer("linked_spray_application_id"),
  readingTimestamp: timestamp("reading_timestamp", { withTimezone: true }).notNull(),
  entryMode: text("entry_mode"),
  dataSource: text("data_source"),
  temperatureC: numeric("temperature_c", { precision: 5, scale: 1 }),
  temperatureHighC: numeric("temperature_high_c", { precision: 5, scale: 1 }),
  temperatureLowC: numeric("temperature_low_c", { precision: 5, scale: 1 }),
  humidityPercent: numeric("humidity_percent", { precision: 5, scale: 1 }),
  windSpeedKmh: numeric("wind_speed_kmh", { precision: 5, scale: 1 }),
  windDirection: text("wind_direction"),
  rainfallMm: numeric("rainfall_mm", { precision: 7, scale: 2 }),
  pressureHpa: numeric("pressure_hpa", { precision: 7, scale: 2 }),
  conditions: text("conditions"),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const vehicleWeatherDevicesTable = pgTable("vehicle_weather_devices", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  name: text("name").notNull(),
  manufacturer: text("manufacturer"),
  model: text("model"),
  serialNumber: text("serial_number"),
  installationType: text("installation_type").notNull().default("portable"),
  calibrationDate: timestamp("calibration_date", { withTimezone: true }),
  calibrationDueDate: timestamp("calibration_due_date", { withTimezone: true }),
  apiDeviceId: text("api_device_id"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const vehicleWeatherReadingsTable = pgTable("vehicle_weather_readings", {
  id: serial("id").primaryKey(),
  farmId: integer("farm_id").notNull().references(() => farmsTable.id),
  equipmentId: integer("equipment_id").references(() => equipmentTable.id),
  deviceId: integer("device_id").references(() => vehicleWeatherDevicesTable.id),
  vehicleName: text("vehicle_name").notNull(),
  vehicleRegistration: text("vehicle_registration"),
  readingTimestamp: timestamp("reading_timestamp", { withTimezone: true }).notNull(),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  fieldDescription: text("field_description"),
  temperatureC: numeric("temperature_c", { precision: 5, scale: 1 }),
  humidityPercent: numeric("humidity_percent", { precision: 5, scale: 1 }),
  windSpeedKmh: numeric("wind_speed_kmh", { precision: 5, scale: 1 }),
  windDirection: text("wind_direction"),
  rainfallMm: numeric("rainfall_mm", { precision: 7, scale: 2 }),
  leafWetness: text("leaf_wetness"),
  dataSource: text("data_source").notNull().default("manual"),
  linkedSprayApplicationId: integer("linked_spray_application_id"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
